// Country display names from Unicode CLDR (unicode.org/license.html).
const Map<String, Map<String, String>> countryNames =
    <String, Map<String, String>>{
      'ar': <String, String>{
        'AC': 'جزيرة أسينشيون',
        'AD': 'أندورا',
        'AE': 'الإمارات العربية المتحدة',
        'AF': 'أفغانستان',
        'AG': 'أنتيغوا وبربودا',
        'AI': 'أنغويلا',
        'AL': 'ألبانيا',
        'AM': 'أرمينيا',
        'AO': 'أنغولا',
        'AQ': 'أنتاركتيكا',
        'AR': 'الأرجنتين',
        'AS': 'ساموا الأمريكية',
        'AT': 'النمسا',
        'AU': 'أستراليا',
        'AW': 'أروبا',
        'AX': 'جزر آلاند',
        'AZ': 'أذربيجان',
        'BA': 'البوسنة والهرسك',
        'BB': 'بربادوس',
        'BD': 'بنغلاديش',
        'BE': 'بلجيكا',
        'BF': 'بوركينا فاسو',
        'BG': 'بلغاريا',
        'BH': 'البحرين',
        'BI': 'بوروندي',
        'BJ': 'بنين',
        'BL': 'سان بارتليمي',
        'BM': 'برمودا',
        'BN': 'بروناي',
        'BO': 'بوليفيا',
        'BQ': 'هولندا الكاريبية',
        'BR': 'البرازيل',
        'BS': 'جزر البهاما',
        'BT': 'بوتان',
        'BV': 'جزيرة بوفيه',
        'BW': 'بوتسوانا',
        'BY': 'بيلاروس',
        'BZ': 'بليز',
        'CA': 'كندا',
        'CC': 'جزر كوكوس (كيلينغ)',
        'CD': 'الكونغو - كينشاسا',
        'CF': 'جمهورية أفريقيا الوسطى',
        'CG': 'الكونغو - برازافيل',
        'CH': 'سويسرا',
        'CI': 'ساحل العاج',
        'CK': 'جزر كوك',
        'CL': 'تشيلي',
        'CM': 'الكاميرون',
        'CN': 'الصين',
        'CO': 'كولومبيا',
        'CP': 'جزيرة كليبيرتون',
        'CQ': 'سارك',
        'CR': 'كوستاريكا',
        'CU': 'كوبا',
        'CV': 'الرأس الأخضر',
        'CW': 'كوراساو',
        'CX': 'جزيرة كريسماس',
        'CY': 'قبرص',
        'CZ': 'التشيك',
        'DE': 'ألمانيا',
        'DG': 'دييغو غارسيا',
        'DJ': 'جيبوتي',
        'DK': 'الدانمرك',
        'DM': 'دومينيكا',
        'DO': 'جمهورية الدومينيكان',
        'DZ': 'الجزائر',
        'EA': 'سيوتا وميليلا',
        'EC': 'الإكوادور',
        'EE': 'إستونيا',
        'EG': 'مصر',
        'EH': 'الصحراء الغربية',
        'ER': 'إريتريا',
        'ES': 'إسبانيا',
        'ET': 'إثيوبيا',
        'FI': 'فنلندا',
        'FJ': 'فيجي',
        'FK': 'جزر فوكلاند',
        'FM': 'ميكرونيزيا',
        'FO': 'جزر فارو',
        'FR': 'فرنسا',
        'GA': 'الغابون',
        'GB': 'المملكة المتحدة',
        'GD': 'غرينادا',
        'GE': 'جورجيا',
        'GF': 'غويانا الفرنسية',
        'GG': 'غيرنزي',
        'GH': 'غانا',
        'GI': 'جبل طارق',
        'GL': 'غرينلاند',
        'GM': 'غامبيا',
        'GN': 'غينيا',
        'GP': 'غوادلوب',
        'GQ': 'غينيا الاستوائية',
        'GR': 'اليونان',
        'GS': 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
        'GT': 'غواتيمالا',
        'GU': 'غوام',
        'GW': 'غينيا بيساو',
        'GY': 'غيانا',
        'HK': 'هونغ كونغ الصينية (منطقة إدارية خاصة)',
        'HM': 'جزيرة هيرد وجزر ماكدونالد',
        'HN': 'هندوراس',
        'HR': 'كرواتيا',
        'HT': 'هايتي',
        'HU': 'هنغاريا',
        'IC': 'جزر الكناري',
        'ID': 'إندونيسيا',
        'IE': 'أيرلندا',
        'IL': 'إسرائيل',
        'IM': 'جزيرة مان',
        'IN': 'الهند',
        'IO': 'الإقليم البريطاني في المحيط الهندي',
        'IQ': 'العراق',
        'IR': 'إيران',
        'IS': 'آيسلندا',
        'IT': 'إيطاليا',
        'JE': 'جيرسي',
        'JM': 'جامايكا',
        'JO': 'الأردن',
        'JP': 'اليابان',
        'KE': 'كينيا',
        'KG': 'قيرغيزستان',
        'KH': 'كمبوديا',
        'KI': 'كيريباتي',
        'KM': 'جزر القمر',
        'KN': 'سانت كيتس ونيفيس',
        'KP': 'كوريا الشمالية',
        'KR': 'كوريا الجنوبية',
        'KW': 'الكويت',
        'KY': 'جزر كايمان',
        'KZ': 'كازاخستان',
        'LA': 'لاوس',
        'LB': 'لبنان',
        'LC': 'سانت لوسيا',
        'LI': 'ليختنشتاين',
        'LK': 'سريلانكا',
        'LR': 'ليبيريا',
        'LS': 'ليسوتو',
        'LT': 'ليتوانيا',
        'LU': 'لوكسمبورغ',
        'LV': 'لاتفيا',
        'LY': 'ليبيا',
        'MA': 'المغرب',
        'MC': 'موناكو',
        'MD': 'مولدوفا',
        'ME': 'الجبل الأسود',
        'MF': 'سان مارتن',
        'MG': 'مدغشقر',
        'MH': 'جزر مارشال',
        'MK': 'مقدونيا الشمالية',
        'ML': 'مالي',
        'MM': 'ميانمار (بورما)',
        'MN': 'منغوليا',
        'MO': 'منطقة ماكاو الإدارية الخاصة',
        'MP': 'جزر ماريانا الشمالية',
        'MQ': 'جزر المارتينيك',
        'MR': 'موريتانيا',
        'MS': 'مونتسرات',
        'MT': 'مالطا',
        'MU': 'موريشيوس',
        'MV': 'جزر المالديف',
        'MW': 'ملاوي',
        'MX': 'المكسيك',
        'MY': 'ماليزيا',
        'MZ': 'موزمبيق',
        'NA': 'ناميبيا',
        'NC': 'كاليدونيا الجديدة',
        'NE': 'النيجر',
        'NF': 'جزيرة نورفولك',
        'NG': 'نيجيريا',
        'NI': 'نيكاراغوا',
        'NL': 'هولندا',
        'NO': 'النرويج',
        'NP': 'نيبال',
        'NR': 'ناورو',
        'NU': 'نيوي',
        'NZ': 'نيوزيلندا',
        'OM': 'عُمان',
        'PA': 'بنما',
        'PE': 'بيرو',
        'PF': 'بولينيزيا الفرنسية',
        'PG': 'بابوا غينيا الجديدة',
        'PH': 'الفلبين',
        'PK': 'باكستان',
        'PL': 'بولندا',
        'PM': 'سان بيير ومكويلون',
        'PN': 'جزر بيتكيرن',
        'PR': 'بورتوريكو',
        'PS': 'الأراضي الفلسطينية',
        'PT': 'البرتغال',
        'PW': 'بالاو',
        'PY': 'باراغواي',
        'QA': 'قطر',
        'RE': 'روينيون',
        'RO': 'رومانيا',
        'RS': 'صربيا',
        'RU': 'روسيا',
        'RW': 'رواندا',
        'SA': 'المملكة العربية السعودية',
        'SB': 'جزر سليمان',
        'SC': 'سيشل',
        'SD': 'السودان',
        'SE': 'السويد',
        'SG': 'سنغافورة',
        'SH': 'سانت هيلينا',
        'SI': 'سلوفينيا',
        'SJ': 'سفالبارد وجان ماين',
        'SK': 'سلوفاكيا',
        'SL': 'سيراليون',
        'SM': 'سان مارينو',
        'SN': 'السنغال',
        'SO': 'الصومال',
        'SR': 'سورينام',
        'SS': 'جنوب السودان',
        'ST': 'ساو تومي وبرينسيبي',
        'SV': 'السلفادور',
        'SX': 'سانت مارتن',
        'SY': 'سوريا',
        'SZ': 'إسواتيني',
        'TA': 'تريستان دا كونا',
        'TC': 'جزر توركس وكايكوس',
        'TD': 'تشاد',
        'TF': 'الأقاليم الجنوبية الفرنسية',
        'TG': 'توغو',
        'TH': 'تايلاند',
        'TJ': 'طاجيكستان',
        'TK': 'توكيلاو',
        'TL': 'تيمور - ليشتي',
        'TM': 'تركمانستان',
        'TN': 'تونس',
        'TO': 'تونغا',
        'TR': 'تركيا',
        'TT': 'ترينيداد وتوباغو',
        'TV': 'توفالو',
        'TW': 'تايوان',
        'TZ': 'تنزانيا',
        'UA': 'أوكرانيا',
        'UG': 'أوغندا',
        'UM': 'جزر الولايات المتحدة النائية',
        'US': 'الولايات المتحدة',
        'UY': 'أورغواي',
        'UZ': 'أوزبكستان',
        'VA': 'الفاتيكان',
        'VC': 'سانت فنسنت وجزر غرينادين',
        'VE': 'فنزويلا',
        'VG': 'جزر فيرجن البريطانية',
        'VI': 'جزر فيرجن الأمريكية',
        'VN': 'فيتنام',
        'VU': 'فانواتو',
        'WF': 'جزر والس وفوتونا',
        'WS': 'ساموا',
        'XK': 'كوسوفو',
        'YE': 'اليمن',
        'YT': 'مايوت',
        'ZA': 'جنوب أفريقيا',
        'ZM': 'زامبيا',
        'ZW': 'زيمبابوي',
      },
      'bn': <String, String>{
        'AC': 'অ্যাসেনশন দ্বীপপুঞ্জ',
        'AD': 'আন্ডোরা',
        'AE': 'সংযুক্ত আরব আমিরাত',
        'AF': 'আফগানিস্তান',
        'AG': 'অ্যান্টিগুয়া ও বারবুডা',
        'AI': 'অ্যাঙ্গুইলা',
        'AL': 'আলবেনিয়া',
        'AM': 'আর্মেনিয়া',
        'AO': 'অ্যাঙ্গোলা',
        'AQ': 'অ্যান্টার্কটিকা',
        'AR': 'আর্জেন্টিনা',
        'AS': 'আমেরিকান সামোয়া',
        'AT': 'অস্ট্রিয়া',
        'AU': 'অস্ট্রেলিয়া',
        'AW': 'আরুবা',
        'AX': 'অলান্ড দ্বীপপুঞ্জ',
        'AZ': 'আজারবাইজান',
        'BA': 'বসনিয়া ও হার্জেগোভিনা',
        'BB': 'বার্বাডোজ',
        'BD': 'বাংলাদেশ',
        'BE': 'বেলজিয়াম',
        'BF': 'বুরকিনা ফাসো',
        'BG': 'বুলগেরিয়া',
        'BH': 'বাহারিন',
        'BI': 'বুরুন্ডি',
        'BJ': 'বেনিন',
        'BL': 'সেন্ট বার্থেলেমি',
        'BM': 'বারমুডা',
        'BN': 'ব্রুনেই',
        'BO': 'বলিভিয়া',
        'BQ': 'ক্যারিবিয়ান নেদারল্যান্ডস',
        'BR': 'ব্রাজিল',
        'BS': 'বাহামা দ্বীপপুঞ্জ',
        'BT': 'ভুটান',
        'BV': 'বোভেট দ্বীপ',
        'BW': 'বতসোয়ানা',
        'BY': 'বেলারুশ',
        'BZ': 'বেলিজ',
        'CA': 'কানাডা',
        'CC': 'কোকোস (কিলিং) দ্বীপপুঞ্জ',
        'CD': 'কঙ্গো-কিনশাসা',
        'CF': 'মধ্য আফ্রিকান প্রজাতন্ত্র',
        'CG': 'কঙ্গো - ব্রাজাভিল',
        'CH': 'সুইজারল্যান্ড',
        'CI': 'কোট ডি‘আইভোর',
        'CK': 'কুক দ্বীপপুঞ্জ',
        'CL': 'চিলি',
        'CM': 'ক্যামেরুন',
        'CN': 'চীন',
        'CO': 'কলম্বিয়া',
        'CP': 'ক্লিপারটন দ্বীপপুঞ্জ',
        'CQ': 'সার্ক দ্বীপ',
        'CR': 'কোস্টারিকা',
        'CU': 'কিউবা',
        'CV': 'কেপ ভার্দে',
        'CW': 'কুরাসাও',
        'CX': 'ক্রিসমাস দ্বীপ',
        'CY': 'সাইপ্রাস',
        'CZ': 'চেকিয়া',
        'DE': 'জার্মানি',
        'DG': 'দিয়েগো গার্সিয়া',
        'DJ': 'জিবুতি',
        'DK': 'ডেনমার্ক',
        'DM': 'ডোমিনিকা',
        'DO': 'ডোমেনিকান প্রজাতন্ত্র',
        'DZ': 'আলজেরিয়া',
        'EA': 'কুউটা এবং মেলিলা',
        'EC': 'ইকুয়েডর',
        'EE': 'এস্তোনিয়া',
        'EG': 'মিশর',
        'EH': 'পশ্চিম সাহারা',
        'ER': 'ইরিত্রিয়া',
        'ES': 'স্পেন',
        'ET': 'ইথিওপিয়া',
        'FI': 'ফিনল্যান্ড',
        'FJ': 'ফিজি',
        'FK': 'ফকল্যান্ড দ্বীপপুঞ্জ',
        'FM': 'মাইক্রোনেশিয়া',
        'FO': 'ফ্যারো দ্বীপপুঞ্জ',
        'FR': 'ফ্রান্স',
        'GA': 'গ্যাবন',
        'GB': 'যুক্তরাজ্য',
        'GD': 'গ্রেনাডা',
        'GE': 'জর্জিয়া',
        'GF': 'ফরাসী গায়ানা',
        'GG': 'গার্নসি',
        'GH': 'ঘানা',
        'GI': 'জিব্রাল্টার',
        'GL': 'গ্রীনল্যান্ড',
        'GM': 'গাম্বিয়া',
        'GN': 'গিনি',
        'GP': 'গুয়াদেলৌপ',
        'GQ': 'নিরক্ষীয় গিনি',
        'GR': 'গ্রীস',
        'GS': 'দক্ষিণ জর্জিয়া ও দক্ষিণ স্যান্ডউইচ দ্বীপপুঞ্জ',
        'GT': 'গুয়াতেমালা',
        'GU': 'গুয়াম',
        'GW': 'গিনি-বিসাউ',
        'GY': 'গিয়ানা',
        'HK': 'হংকং এসএআর চীনা',
        'HM': 'হার্ড এবং ম্যাকডোনাল্ড দ্বীপপুঞ্জ',
        'HN': 'হন্ডুরাস',
        'HR': 'ক্রোয়েশিয়া',
        'HT': 'হাইতি',
        'HU': 'হাঙ্গেরি',
        'IC': 'ক্যানারি দ্বীপপুঞ্জ',
        'ID': 'ইন্দোনেশিয়া',
        'IE': 'আয়ারল্যান্ড',
        'IL': 'ইজরায়েল',
        'IM': 'আইল অফ ম্যান',
        'IN': 'ভারত',
        'IO': 'ব্রিটিশ ভারত মহাসাগরীয় অঞ্চল',
        'IQ': 'ইরাক',
        'IR': 'ইরান',
        'IS': 'আইসল্যান্ড',
        'IT': 'ইতালি',
        'JE': 'জার্সি',
        'JM': 'জামাইকা',
        'JO': 'জর্ডন',
        'JP': 'জাপান',
        'KE': 'কেনিয়া',
        'KG': 'কিরগিজিস্তান',
        'KH': 'কম্বোডিয়া',
        'KI': 'কিরিবাতি',
        'KM': 'কমোরোস',
        'KN': 'সেন্ট কিটস ও নেভিস',
        'KP': 'উত্তর কোরিয়া',
        'KR': 'দক্ষিণ কোরিয়া',
        'KW': 'কুয়েত',
        'KY': 'কেম্যান দ্বীপপুঞ্জ',
        'KZ': 'কাজাখস্তান',
        'LA': 'লাওস',
        'LB': 'লেবানন',
        'LC': 'সেন্ট লুসিয়া',
        'LI': 'লিচেনস্টেইন',
        'LK': 'শ্রীলঙ্কা',
        'LR': 'লাইবেরিয়া',
        'LS': 'লেসোথো',
        'LT': 'লিথুয়ানিয়া',
        'LU': 'লাক্সেমবার্গ',
        'LV': 'লাটভিয়া',
        'LY': 'লিবিয়া',
        'MA': 'মরক্কো',
        'MC': 'মোনাকো',
        'MD': 'মলডোভা',
        'ME': 'মন্টিনিগ্রো',
        'MF': 'সেন্ট মার্টিন',
        'MG': 'মাদাগাস্কার',
        'MH': 'মার্শাল দ্বীপপুঞ্জ',
        'MK': 'উত্তর ম্যাসেডোনিয়া',
        'ML': 'মালি',
        'MM': 'মায়ানমার (বার্মা)',
        'MN': 'মঙ্গোলিয়া',
        'MO': 'ম্যাকাও এসএআর চীন',
        'MP': 'উত্তরাঞ্চলীয় মারিয়ানা দ্বীপপুঞ্জ',
        'MQ': 'মার্টিনিক',
        'MR': 'মরিতানিয়া',
        'MS': 'মন্টসেরাট',
        'MT': 'মাল্টা',
        'MU': 'মরিশাস',
        'MV': 'মালদ্বীপ',
        'MW': 'মালাউই',
        'MX': 'মেক্সিকো',
        'MY': 'মালয়েশিয়া',
        'MZ': 'মোজাম্বিক',
        'NA': 'নামিবিয়া',
        'NC': 'নিউ ক্যালেডোনিয়া',
        'NE': 'নাইজার',
        'NF': 'নরফোক দ্বীপ',
        'NG': 'নাইজেরিয়া',
        'NI': 'নিকারাগুয়া',
        'NL': 'নেদারল্যান্ডস',
        'NO': 'নরওয়ে',
        'NP': 'নেপাল',
        'NR': 'নাউরু',
        'NU': 'নিউয়ে',
        'NZ': 'নিউজিল্যান্ড',
        'OM': 'ওমান',
        'PA': 'পানামা',
        'PE': 'পেরু',
        'PF': 'ফরাসী পলিনেশিয়া',
        'PG': 'পাপুয়া নিউ গিনি',
        'PH': 'ফিলিপাইন',
        'PK': 'পাকিস্তান',
        'PL': 'পোল্যান্ড',
        'PM': 'সেন্ট পিয়ের ও মিকুয়েলন',
        'PN': 'পিটকেয়ার্ন দ্বীপপুঞ্জ',
        'PR': 'পুয়ের্তো রিকো',
        'PS': 'প্যালেস্টাইন ভূখণ্ড',
        'PT': 'পর্তুগাল',
        'PW': 'পালাউ',
        'PY': 'প্যারাগুয়ে',
        'QA': 'কাতার',
        'RE': 'রিইউনিয়ন',
        'RO': 'রোমানিয়া',
        'RS': 'সার্বিয়া',
        'RU': 'রাশিয়া',
        'RW': 'রুয়ান্ডা',
        'SA': 'সৌদি আরব',
        'SB': 'সলোমন দ্বীপপুঞ্জ',
        'SC': 'সিসিলি',
        'SD': 'সুদান',
        'SE': 'সুইডেন',
        'SG': 'সিঙ্গাপুর',
        'SH': 'সেন্ট হেলেনা',
        'SI': 'স্লোভানিয়া',
        'SJ': 'স্বালবার্ড ও জান মেয়েন',
        'SK': 'স্লোভাকিয়া',
        'SL': 'সিয়েরা লিওন',
        'SM': 'সান মারিনো',
        'SN': 'সেনেগাল',
        'SO': 'সোমালিয়া',
        'SR': 'সুরিনাম',
        'SS': 'দক্ষিণ সুদান',
        'ST': 'সাওটোমা ও প্রিন্সিপি',
        'SV': 'এল সালভেদর',
        'SX': 'সিন্ট মার্টেন',
        'SY': 'সিরিয়া',
        'SZ': 'ইসওয়াতিনি',
        'TA': 'ট্রিস্টান ডা কুনহা',
        'TC': 'তুর্কস ও কাইকোস দ্বীপপুঞ্জ',
        'TD': 'চাদ',
        'TF': 'ফরাসী দক্ষিণাঞ্চল',
        'TG': 'টোগো',
        'TH': 'থাইল্যান্ড',
        'TJ': 'তাজিকিস্তান',
        'TK': 'টোকেলাউ',
        'TL': 'তিমুর-লেস্তে',
        'TM': 'তুর্কমেনিস্তান',
        'TN': 'তিউনিসিয়া',
        'TO': 'টোঙ্গা',
        'TR': 'তুরস্ক',
        'TT': 'ত্রিনিদাদ ও টোবাগো',
        'TV': 'টুভালু',
        'TW': 'তাইওয়ান',
        'TZ': 'তাঞ্জানিয়া',
        'UA': 'ইউক্রেন',
        'UG': 'উগান্ডা',
        'UM': 'যুক্তরাষ্ট্রের পার্শ্ববর্তী দ্বীপপুঞ্জ',
        'US': 'মার্কিন যুক্তরাষ্ট্র',
        'UY': 'উরুগুয়ে',
        'UZ': 'উজবেকিস্তান',
        'VA': 'ভ্যাটিকান সিটি',
        'VC': 'সেন্ট ভিনসেন্ট ও গ্রেনাডিনস',
        'VE': 'ভেনেজুয়েলা',
        'VG': 'ব্রিটিশ ভার্জিন দ্বীপপুঞ্জ',
        'VI': 'মার্কিন যুক্তরাষ্ট্রীয় ভার্জিন দ্বীপপুঞ্জ',
        'VN': 'ভিয়েতনাম',
        'VU': 'ভানুয়াটু',
        'WF': 'ওয়ালিস ও ফুটুনা',
        'WS': 'সামোয়া',
        'XK': 'কসোভো',
        'YE': 'ইয়েমেন',
        'YT': 'মায়োত্তে',
        'ZA': 'দক্ষিণ আফ্রিকা',
        'ZM': 'জাম্বিয়া',
        'ZW': 'জিম্বাবোয়ে',
      },
      'de': <String, String>{
        'AC': 'Ascension',
        'AD': 'Andorra',
        'AE': 'Vereinigte Arabische Emirate',
        'AF': 'Afghanistan',
        'AG': 'Antigua und Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albanien',
        'AM': 'Armenien',
        'AO': 'Angola',
        'AQ': 'Antarktis',
        'AR': 'Argentinien',
        'AS': 'Amerikanisch-Samoa',
        'AT': 'Österreich',
        'AU': 'Australien',
        'AW': 'Aruba',
        'AX': 'Ålandinseln',
        'AZ': 'Aserbaidschan',
        'BA': 'Bosnien und Herzegowina',
        'BB': 'Barbados',
        'BD': 'Bangladesch',
        'BE': 'Belgien',
        'BF': 'Burkina Faso',
        'BG': 'Bulgarien',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'St. Barthélemy',
        'BM': 'Bermuda',
        'BN': 'Brunei Darussalam',
        'BO': 'Bolivien',
        'BQ': 'Karibische Niederlande',
        'BR': 'Brasilien',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Bouvetinsel',
        'BW': 'Botsuana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Kanada',
        'CC': 'Kokosinseln',
        'CD': 'Kongo-Kinshasa',
        'CF': 'Zentralafrikanische Republik',
        'CG': 'Kongo-Brazzaville',
        'CH': 'Schweiz',
        'CI': 'Côte d’Ivoire',
        'CK': 'Cookinseln',
        'CL': 'Chile',
        'CM': 'Kamerun',
        'CN': 'China',
        'CO': 'Kolumbien',
        'CP': 'Clipperton-Insel',
        'CQ': 'Sark',
        'CR': 'Costa Rica',
        'CU': 'Kuba',
        'CV': 'Cabo Verde',
        'CW': 'Curaçao',
        'CX': 'Weihnachtsinsel',
        'CY': 'Zypern',
        'CZ': 'Tschechien',
        'DE': 'Deutschland',
        'DG': 'Diego Garcia',
        'DJ': 'Dschibuti',
        'DK': 'Dänemark',
        'DM': 'Dominica',
        'DO': 'Dominikanische Republik',
        'DZ': 'Algerien',
        'EA': 'Ceuta und Melilla',
        'EC': 'Ecuador',
        'EE': 'Estland',
        'EG': 'Ägypten',
        'EH': 'Westsahara',
        'ER': 'Eritrea',
        'ES': 'Spanien',
        'ET': 'Äthiopien',
        'FI': 'Finnland',
        'FJ': 'Fidschi',
        'FK': 'Falklandinseln',
        'FM': 'Mikronesien',
        'FO': 'Färöer',
        'FR': 'Frankreich',
        'GA': 'Gabun',
        'GB': 'Vereinigtes Königreich',
        'GD': 'Grenada',
        'GE': 'Georgien',
        'GF': 'Französisch-Guayana',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Grönland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Äquatorialguinea',
        'GR': 'Griechenland',
        'GS': 'Südgeorgien und die Südlichen Sandwichinseln',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Sonderverwaltungsregion Hongkong',
        'HM': 'Heard und McDonaldinseln',
        'HN': 'Honduras',
        'HR': 'Kroatien',
        'HT': 'Haiti',
        'HU': 'Ungarn',
        'IC': 'Kanarische Inseln',
        'ID': 'Indonesien',
        'IE': 'Irland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'Indien',
        'IO': 'Britisches Territorium im Indischen Ozean',
        'IQ': 'Irak',
        'IR': 'Iran',
        'IS': 'Island',
        'IT': 'Italien',
        'JE': 'Jersey',
        'JM': 'Jamaika',
        'JO': 'Jordanien',
        'JP': 'Japan',
        'KE': 'Kenia',
        'KG': 'Kirgisistan',
        'KH': 'Kambodscha',
        'KI': 'Kiribati',
        'KM': 'Komoren',
        'KN': 'St. Kitts und Nevis',
        'KP': 'Nordkorea',
        'KR': 'Südkorea',
        'KW': 'Kuwait',
        'KY': 'Kaimaninseln',
        'KZ': 'Kasachstan',
        'LA': 'Laos',
        'LB': 'Libanon',
        'LC': 'St. Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Litauen',
        'LU': 'Luxemburg',
        'LV': 'Lettland',
        'LY': 'Libyen',
        'MA': 'Marokko',
        'MC': 'Monaco',
        'MD': 'Republik Moldau',
        'ME': 'Montenegro',
        'MF': 'St. Martin',
        'MG': 'Madagaskar',
        'MH': 'Marshallinseln',
        'MK': 'Nordmazedonien',
        'ML': 'Mali',
        'MM': 'Myanmar',
        'MN': 'Mongolei',
        'MO': 'Sonderverwaltungsregion Macau',
        'MP': 'Nördliche Marianen',
        'MQ': 'Martinique',
        'MR': 'Mauretanien',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Malediven',
        'MW': 'Malawi',
        'MX': 'Mexiko',
        'MY': 'Malaysia',
        'MZ': 'Mosambik',
        'NA': 'Namibia',
        'NC': 'Neukaledonien',
        'NE': 'Niger',
        'NF': 'Norfolkinsel',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Niederlande',
        'NO': 'Norwegen',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'Neuseeland',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'Französisch-Polynesien',
        'PG': 'Papua-Neuguinea',
        'PH': 'Philippinen',
        'PK': 'Pakistan',
        'PL': 'Polen',
        'PM': 'St. Pierre und Miquelon',
        'PN': 'Pitcairninseln',
        'PR': 'Puerto Rico',
        'PS': 'Palästinensische Autonomiegebiete',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Katar',
        'RE': 'Réunion',
        'RO': 'Rumänien',
        'RS': 'Serbien',
        'RU': 'Russland',
        'RW': 'Ruanda',
        'SA': 'Saudi-Arabien',
        'SB': 'Salomonen',
        'SC': 'Seychellen',
        'SD': 'Sudan',
        'SE': 'Schweden',
        'SG': 'Singapur',
        'SH': 'St. Helena',
        'SI': 'Slowenien',
        'SJ': 'Spitzbergen und Jan Mayen',
        'SK': 'Slowakei',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'SS': 'Südsudan',
        'ST': 'São Tomé und Príncipe',
        'SV': 'El Salvador',
        'SX': 'Sint Maarten',
        'SY': 'Syrien',
        'SZ': 'Eswatini',
        'TA': 'Tristan da Cunha',
        'TC': 'Turks- und Caicosinseln',
        'TD': 'Tschad',
        'TF': 'Französische Süd- und Antarktisgebiete',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tadschikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-Leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunesien',
        'TO': 'Tonga',
        'TR': 'Türkei',
        'TT': 'Trinidad und Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tansania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'UM': 'Amerikanische Überseeinseln',
        'US': 'Vereinigte Staaten',
        'UY': 'Uruguay',
        'UZ': 'Usbekistan',
        'VA': 'Vatikanstadt',
        'VC': 'St. Vincent und die Grenadinen',
        'VE': 'Venezuela',
        'VG': 'Britische Jungferninseln',
        'VI': 'Amerikanische Jungferninseln',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis und Futuna',
        'WS': 'Samoa',
        'XK': 'Kosovo',
        'YE': 'Jemen',
        'YT': 'Mayotte',
        'ZA': 'Südafrika',
        'ZM': 'Sambia',
        'ZW': 'Simbabwe',
      },
      'en': <String, String>{
        'AC': 'Ascension Island',
        'AD': 'Andorra',
        'AE': 'United Arab Emirates',
        'AF': 'Afghanistan',
        'AG': 'Antigua & Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AO': 'Angola',
        'AQ': 'Antarctica',
        'AR': 'Argentina',
        'AS': 'American Samoa',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Åland Islands',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia & Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgium',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'St. Barthélemy',
        'BM': 'Bermuda',
        'BN': 'Brunei',
        'BO': 'Bolivia',
        'BQ': 'Caribbean Netherlands',
        'BR': 'Brazil',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Bouvet Island',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Canada',
        'CC': 'Cocos (Keeling) Islands',
        'CD': 'Congo - Kinshasa',
        'CF': 'Central African Republic',
        'CG': 'Congo - Brazzaville',
        'CH': 'Switzerland',
        'CI': 'Côte d’Ivoire',
        'CK': 'Cook Islands',
        'CL': 'Chile',
        'CM': 'Cameroon',
        'CN': 'China',
        'CO': 'Colombia',
        'CP': 'Clipperton Island',
        'CQ': 'Sark',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CW': 'Curaçao',
        'CX': 'Christmas Island',
        'CY': 'Cyprus',
        'CZ': 'Czechia',
        'DE': 'Germany',
        'DG': 'Diego Garcia',
        'DJ': 'Djibouti',
        'DK': 'Denmark',
        'DM': 'Dominica',
        'DO': 'Dominican Republic',
        'DZ': 'Algeria',
        'EA': 'Ceuta & Melilla',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egypt',
        'EH': 'Western Sahara',
        'ER': 'Eritrea',
        'ES': 'Spain',
        'ET': 'Ethiopia',
        'FI': 'Finland',
        'FJ': 'Fiji',
        'FK': 'Falkland Islands',
        'FM': 'Micronesia',
        'FO': 'Faroe Islands',
        'FR': 'France',
        'GA': 'Gabon',
        'GB': 'United Kingdom',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'French Guiana',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Equatorial Guinea',
        'GR': 'Greece',
        'GS': 'South Georgia & South Sandwich Islands',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong SAR China',
        'HM': 'Heard & McDonald Islands',
        'HN': 'Honduras',
        'HR': 'Croatia',
        'HT': 'Haiti',
        'HU': 'Hungary',
        'IC': 'Canary Islands',
        'ID': 'Indonesia',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'India',
        'IO': 'British Indian Ocean Territory',
        'IQ': 'Iraq',
        'IR': 'Iran',
        'IS': 'Iceland',
        'IT': 'Italy',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordan',
        'JP': 'Japan',
        'KE': 'Kenya',
        'KG': 'Kyrgyzstan',
        'KH': 'Cambodia',
        'KI': 'Kiribati',
        'KM': 'Comoros',
        'KN': 'St. Kitts & Nevis',
        'KP': 'North Korea',
        'KR': 'South Korea',
        'KW': 'Kuwait',
        'KY': 'Cayman Islands',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lebanon',
        'LC': 'St. Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'LY': 'Libya',
        'MA': 'Morocco',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MF': 'St. Martin',
        'MG': 'Madagascar',
        'MH': 'Marshall Islands',
        'MK': 'North Macedonia',
        'ML': 'Mali',
        'MM': 'Myanmar (Burma)',
        'MN': 'Mongolia',
        'MO': 'Macao SAR China',
        'MP': 'Northern Mariana Islands',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexico',
        'MY': 'Malaysia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'New Caledonia',
        'NE': 'Niger',
        'NF': 'Norfolk Island',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Netherlands',
        'NO': 'Norway',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'New Zealand',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'French Polynesia',
        'PG': 'Papua New Guinea',
        'PH': 'Philippines',
        'PK': 'Pakistan',
        'PL': 'Poland',
        'PM': 'St. Pierre & Miquelon',
        'PN': 'Pitcairn Islands',
        'PR': 'Puerto Rico',
        'PS': 'Palestinian Territories',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Réunion',
        'RO': 'Romania',
        'RS': 'Serbia',
        'RU': 'Russia',
        'RW': 'Rwanda',
        'SA': 'Saudi Arabia',
        'SB': 'Solomon Islands',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Sweden',
        'SG': 'Singapore',
        'SH': 'St. Helena',
        'SI': 'Slovenia',
        'SJ': 'Svalbard & Jan Mayen',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'SS': 'South Sudan',
        'ST': 'São Tomé & Príncipe',
        'SV': 'El Salvador',
        'SX': 'Sint Maarten',
        'SY': 'Syria',
        'SZ': 'Eswatini',
        'TA': 'Tristan da Cunha',
        'TC': 'Turks & Caicos Islands',
        'TD': 'Chad',
        'TF': 'French Southern Territories',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-Leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TR': 'Türkiye',
        'TT': 'Trinidad & Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'UM': 'U.S. Outlying Islands',
        'US': 'United States',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Vatican City',
        'VC': 'St. Vincent & Grenadines',
        'VE': 'Venezuela',
        'VG': 'British Virgin Islands',
        'VI': 'U.S. Virgin Islands',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis & Futuna',
        'WS': 'Samoa',
        'XK': 'Kosovo',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'South Africa',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe',
      },
      'es': <String, String>{
        'AC': 'Isla de la Ascensión',
        'AD': 'Andorra',
        'AE': 'Emiratos Árabes Unidos',
        'AF': 'Afganistán',
        'AG': 'Antigua y Barbuda',
        'AI': 'Anguila',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AO': 'Angola',
        'AQ': 'Antártida',
        'AR': 'Argentina',
        'AS': 'Samoa Americana',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Islas Aland',
        'AZ': 'Azerbaiyán',
        'BA': 'Bosnia y Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladés',
        'BE': 'Bélgica',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Baréin',
        'BI': 'Burundi',
        'BJ': 'Benín',
        'BL': 'San Bartolomé',
        'BM': 'Bermudas',
        'BN': 'Brunéi',
        'BO': 'Bolivia',
        'BQ': 'Caribe neerlandés',
        'BR': 'Brasil',
        'BS': 'Bahamas',
        'BT': 'Bután',
        'BV': 'Isla Bouvet',
        'BW': 'Botsuana',
        'BY': 'Bielorrusia',
        'BZ': 'Belice',
        'CA': 'Canadá',
        'CC': 'Islas Cocos',
        'CD': 'República Democrática del Congo',
        'CF': 'República Centroafricana',
        'CG': 'Congo',
        'CH': 'Suiza',
        'CI': 'Côte d’Ivoire',
        'CK': 'Islas Cook',
        'CL': 'Chile',
        'CM': 'Camerún',
        'CN': 'China',
        'CO': 'Colombia',
        'CP': 'Isla Clipperton',
        'CQ': 'Sark',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cabo Verde',
        'CW': 'Curazao',
        'CX': 'Isla de Navidad',
        'CY': 'Chipre',
        'CZ': 'Chequia',
        'DE': 'Alemania',
        'DG': 'Diego García',
        'DJ': 'Yibuti',
        'DK': 'Dinamarca',
        'DM': 'Dominica',
        'DO': 'República Dominicana',
        'DZ': 'Argelia',
        'EA': 'Ceuta y Melilla',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Egipto',
        'EH': 'Sáhara Occidental',
        'ER': 'Eritrea',
        'ES': 'España',
        'ET': 'Etiopía',
        'FI': 'Finlandia',
        'FJ': 'Fiyi',
        'FK': 'Islas Malvinas',
        'FM': 'Micronesia',
        'FO': 'Islas Feroe',
        'FR': 'Francia',
        'GA': 'Gabón',
        'GB': 'Reino Unido',
        'GD': 'Granada',
        'GE': 'Georgia',
        'GF': 'Guayana Francesa',
        'GG': 'Guernesey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Groenlandia',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadalupe',
        'GQ': 'Guinea Ecuatorial',
        'GR': 'Grecia',
        'GS': 'Islas Georgia del Sur y Sandwich del Sur',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bisáu',
        'GY': 'Guyana',
        'HK': 'RAE de Hong Kong (China)',
        'HM': 'Islas Heard y McDonald',
        'HN': 'Honduras',
        'HR': 'Croacia',
        'HT': 'Haití',
        'HU': 'Hungría',
        'IC': 'Canarias',
        'ID': 'Indonesia',
        'IE': 'Irlanda',
        'IL': 'Israel',
        'IM': 'Isla de Man',
        'IN': 'India',
        'IO': 'Territorio Británico del Océano Índico',
        'IQ': 'Irak',
        'IR': 'Irán',
        'IS': 'Islandia',
        'IT': 'Italia',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordania',
        'JP': 'Japón',
        'KE': 'Kenia',
        'KG': 'Kirguistán',
        'KH': 'Camboya',
        'KI': 'Kiribati',
        'KM': 'Comoras',
        'KN': 'San Cristóbal y Nieves',
        'KP': 'Corea del Norte',
        'KR': 'Corea del Sur',
        'KW': 'Kuwait',
        'KY': 'Islas Caimán',
        'KZ': 'Kazajistán',
        'LA': 'Laos',
        'LB': 'Líbano',
        'LC': 'Santa Lucía',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesoto',
        'LT': 'Lituania',
        'LU': 'Luxemburgo',
        'LV': 'Letonia',
        'LY': 'Libia',
        'MA': 'Marruecos',
        'MC': 'Mónaco',
        'MD': 'Moldavia',
        'ME': 'Montenegro',
        'MF': 'San Martín',
        'MG': 'Madagascar',
        'MH': 'Islas Marshall',
        'MK': 'Macedonia del Norte',
        'ML': 'Mali',
        'MM': 'Myanmar (Birmania)',
        'MN': 'Mongolia',
        'MO': 'RAE de Macao (China)',
        'MP': 'Islas Marianas del Norte',
        'MQ': 'Martinica',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauricio',
        'MV': 'Maldivas',
        'MW': 'Malaui',
        'MX': 'México',
        'MY': 'Malasia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'Nueva Caledonia',
        'NE': 'Níger',
        'NF': 'Isla Norfolk',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Países Bajos',
        'NO': 'Noruega',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'Nueva Zelanda',
        'OM': 'Omán',
        'PA': 'Panamá',
        'PE': 'Perú',
        'PF': 'Polinesia Francesa',
        'PG': 'Papúa Nueva Guinea',
        'PH': 'Filipinas',
        'PK': 'Pakistán',
        'PL': 'Polonia',
        'PM': 'San Pedro y Miquelón',
        'PN': 'Islas Pitcairn',
        'PR': 'Puerto Rico',
        'PS': 'Territorios Palestinos',
        'PT': 'Portugal',
        'PW': 'Palaos',
        'PY': 'Paraguay',
        'QA': 'Catar',
        'RE': 'Reunión',
        'RO': 'Rumanía',
        'RS': 'Serbia',
        'RU': 'Rusia',
        'RW': 'Ruanda',
        'SA': 'Arabia Saudí',
        'SB': 'Islas Salomón',
        'SC': 'Seychelles',
        'SD': 'Sudán',
        'SE': 'Suecia',
        'SG': 'Singapur',
        'SH': 'Santa Elena',
        'SI': 'Eslovenia',
        'SJ': 'Svalbard y Jan Mayen',
        'SK': 'Eslovaquia',
        'SL': 'Sierra Leona',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Surinam',
        'SS': 'Sudán del Sur',
        'ST': 'Santo Tomé y Príncipe',
        'SV': 'El Salvador',
        'SX': 'Sint Maarten',
        'SY': 'Siria',
        'SZ': 'Esuatini',
        'TA': 'Tristán de Acuña',
        'TC': 'Islas Turcas y Caicos',
        'TD': 'Chad',
        'TF': 'Territorios Australes Franceses',
        'TG': 'Togo',
        'TH': 'Tailandia',
        'TJ': 'Tayikistán',
        'TK': 'Tokelau',
        'TL': 'Timor-Leste',
        'TM': 'Turkmenistán',
        'TN': 'Túnez',
        'TO': 'Tonga',
        'TR': 'Turquía',
        'TT': 'Trinidad y Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwán',
        'TZ': 'Tanzania',
        'UA': 'Ucrania',
        'UG': 'Uganda',
        'UM': 'Islas menores alejadas de EE. UU.',
        'US': 'Estados Unidos',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistán',
        'VA': 'Ciudad del Vaticano',
        'VC': 'San Vicente y las Granadinas',
        'VE': 'Venezuela',
        'VG': 'Islas Vírgenes Británicas',
        'VI': 'Islas Vírgenes de EE. UU.',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis y Futuna',
        'WS': 'Samoa',
        'XK': 'Kosovo',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'Sudáfrica',
        'ZM': 'Zambia',
        'ZW': 'Zimbabue',
      },
      'fa': <String, String>{
        'AC': 'جزایر آسنسیون',
        'AD': 'آندورا',
        'AE': 'امارات متحدهٔ عربی',
        'AF': 'افغانستان',
        'AG': 'آنتیگوا و باربودا',
        'AI': 'آنگویلا',
        'AL': 'آلبانی',
        'AM': 'ارمنستان',
        'AO': 'آنگولا',
        'AQ': 'جنوبگان',
        'AR': 'آرژانتین',
        'AS': 'ساموآی امریکا',
        'AT': 'اتریش',
        'AU': 'استرالیا',
        'AW': 'آروبا',
        'AX': 'جزایر آلاند',
        'AZ': 'جمهوری آذربایجان',
        'BA': 'بوسنی و هرزگوین',
        'BB': 'باربادوس',
        'BD': 'بنگلادش',
        'BE': 'بلژیک',
        'BF': 'بورکینافاسو',
        'BG': 'بلغارستان',
        'BH': 'بحرین',
        'BI': 'بوروندی',
        'BJ': 'بنین',
        'BL': 'سن بارتلمی',
        'BM': 'برمودا',
        'BN': 'برونئی',
        'BO': 'بولیوی',
        'BQ': 'جزایر کارائیب هلند',
        'BR': 'برزیل',
        'BS': 'باهاما',
        'BT': 'بوتان',
        'BV': 'جزیرهٔ بووه',
        'BW': 'بوتسوانا',
        'BY': 'بلاروس',
        'BZ': 'بلیز',
        'CA': 'کانادا',
        'CC': 'جزایر کوکوس',
        'CD': 'کنگو - کینشاسا',
        'CF': 'جمهوری افریقای مرکزی',
        'CG': 'کنگو - برازویل',
        'CH': 'سوئیس',
        'CI': 'ساحل عاج',
        'CK': 'جزایر کوک',
        'CL': 'شیلی',
        'CM': 'کامرون',
        'CN': 'چین',
        'CO': 'کلمبیا',
        'CP': 'جزایر کلیپرتون',
        'CQ': 'سارک',
        'CR': 'کاستاریکا',
        'CU': 'کوبا',
        'CV': 'کیپ‌ورد',
        'CW': 'کوراسائو',
        'CX': 'جزیرهٔ کریسمس',
        'CY': 'قبرس',
        'CZ': 'چک',
        'DE': 'آلمان',
        'DG': 'دیه‌گو گارسیا',
        'DJ': 'جیبوتی',
        'DK': 'دانمارک',
        'DM': 'دومینیکا',
        'DO': 'جمهوری دومینیکن',
        'DZ': 'الجزایر',
        'EA': 'سبته و ملیله',
        'EC': 'اکوادور',
        'EE': 'استونی',
        'EG': 'مصر',
        'EH': 'صحرای غربی',
        'ER': 'اریتره',
        'ES': 'اسپانیا',
        'ET': 'اتیوپی',
        'FI': 'فنلاند',
        'FJ': 'فیجی',
        'FK': 'جزایر فالکلند',
        'FM': 'میکرونزی',
        'FO': 'جزایر فارو',
        'FR': 'فرانسه',
        'GA': 'گابن',
        'GB': 'بریتانیا',
        'GD': 'گرنادا',
        'GE': 'گرجستان',
        'GF': 'گویان فرانسه',
        'GG': 'گرنزی',
        'GH': 'غنا',
        'GI': 'جبل‌الطارق',
        'GL': 'گرینلند',
        'GM': 'گامبیا',
        'GN': 'گینه',
        'GP': 'گوادلوپ',
        'GQ': 'گینهٔ استوایی',
        'GR': 'یونان',
        'GS': 'جورجیای جنوبی و جزایر ساندویچ جنوبی',
        'GT': 'گواتمالا',
        'GU': 'گوام',
        'GW': 'گینهٔ بیسائو',
        'GY': 'گویان',
        'HK': 'هنگ‌کنگ، منطقهٔ ویژهٔ اداری چین',
        'HM': 'هرد و جزایر مک‌دونالد',
        'HN': 'هندوراس',
        'HR': 'کرواسی',
        'HT': 'هائیتی',
        'HU': 'مجارستان',
        'IC': 'جزایر قناری',
        'ID': 'اندونزی',
        'IE': 'ایرلند',
        'IL': 'اسرائیل',
        'IM': 'جزیرهٔ من',
        'IN': 'هند',
        'IO': 'قلمرو بریتانیا در اقیانوس هند',
        'IQ': 'عراق',
        'IR': 'ایران',
        'IS': 'ایسلند',
        'IT': 'ایتالیا',
        'JE': 'جرزی',
        'JM': 'جامائیکا',
        'JO': 'اردن',
        'JP': 'ژاپن',
        'KE': 'کنیا',
        'KG': 'قرقیزستان',
        'KH': 'کامبوج',
        'KI': 'کیریباتی',
        'KM': 'کومور',
        'KN': 'سنت کیتس و نویس',
        'KP': 'کرهٔ شمالی',
        'KR': 'کرهٔ جنوبی',
        'KW': 'کویت',
        'KY': 'جزایر کِیمن',
        'KZ': 'قزاقستان',
        'LA': 'لائوس',
        'LB': 'لبنان',
        'LC': 'سنت لوسیا',
        'LI': 'لیختن‌اشتاین',
        'LK': 'سری‌لانکا',
        'LR': 'لیبریا',
        'LS': 'لسوتو',
        'LT': 'لیتوانی',
        'LU': 'لوکزامبورگ',
        'LV': 'لتونی',
        'LY': 'لیبی',
        'MA': 'مراکش',
        'MC': 'موناکو',
        'MD': 'مولداوی',
        'ME': 'مونته‌نگرو',
        'MF': 'سنت مارتین',
        'MG': 'ماداگاسکار',
        'MH': 'جزایر مارشال',
        'MK': 'مقدونیهٔ شمالی',
        'ML': 'مالی',
        'MM': 'میانمار (برمه)',
        'MN': 'مغولستان',
        'MO': 'ماکائو، منطقهٔ ویژهٔ اداری چین',
        'MP': 'جزایر ماریانای شمالی',
        'MQ': 'مارتینیک',
        'MR': 'موریتانی',
        'MS': 'مونت‌سرات',
        'MT': 'مالت',
        'MU': 'موریس',
        'MV': 'مالدیو',
        'MW': 'مالاوی',
        'MX': 'مکزیک',
        'MY': 'مالزی',
        'MZ': 'موزامبیک',
        'NA': 'نامیبیا',
        'NC': 'کالدونیای جدید',
        'NE': 'نیجر',
        'NF': 'جزیرهٔ نورفولک',
        'NG': 'نیجریه',
        'NI': 'نیکاراگوئه',
        'NL': 'هلند',
        'NO': 'نروژ',
        'NP': 'نپال',
        'NR': 'نائورو',
        'NU': 'نیوئه',
        'NZ': 'نیوزیلند',
        'OM': 'عمان',
        'PA': 'پاناما',
        'PE': 'پرو',
        'PF': 'پلی‌نزی فرانسه',
        'PG': 'پاپوا گینهٔ نو',
        'PH': 'فیلیپین',
        'PK': 'پاکستان',
        'PL': 'لهستان',
        'PM': 'سن پیر و میکلن',
        'PN': 'جزایر پیت‌کرن',
        'PR': 'پورتوریکو',
        'PS': 'سرزمین‌های فلسطینی',
        'PT': 'پرتغال',
        'PW': 'پالائو',
        'PY': 'پاراگوئه',
        'QA': 'قطر',
        'RE': 'رئونیون',
        'RO': 'رومانی',
        'RS': 'صربستان',
        'RU': 'روسیه',
        'RW': 'رواندا',
        'SA': 'عربستان سعودی',
        'SB': 'جزایر سلیمان',
        'SC': 'سیشل',
        'SD': 'سودان',
        'SE': 'سوئد',
        'SG': 'سنگاپور',
        'SH': 'سنت هلن',
        'SI': 'اسلوونی',
        'SJ': 'سوالبارد و یان ماین',
        'SK': 'اسلواکی',
        'SL': 'سیرالئون',
        'SM': 'سان‌مارینو',
        'SN': 'سنگال',
        'SO': 'سومالی',
        'SR': 'سورینام',
        'SS': 'سودان جنوبی',
        'ST': 'سائوتومه و پرینسیپ',
        'SV': 'السالوادور',
        'SX': 'سنت مارتن',
        'SY': 'سوریه',
        'SZ': 'اسواتینی',
        'TA': 'تریستان دا کونا',
        'TC': 'جزایر تورکس و کایکوس',
        'TD': 'چاد',
        'TF': 'سرزمین‌های جنوبی فرانسه',
        'TG': 'توگو',
        'TH': 'تایلند',
        'TJ': 'تاجیکستان',
        'TK': 'توکلائو',
        'TL': 'تیمور-لسته',
        'TM': 'ترکمنستان',
        'TN': 'تونس',
        'TO': 'تونگا',
        'TR': 'ترکیه',
        'TT': 'ترینیداد و توباگو',
        'TV': 'تووالو',
        'TW': 'تایوان',
        'TZ': 'تانزانیا',
        'UA': 'اوکراین',
        'UG': 'اوگاندا',
        'UM': 'جزایر دورافتادهٔ ایالات متحده',
        'US': 'ایالات متحده',
        'UY': 'اروگوئه',
        'UZ': 'ازبکستان',
        'VA': 'واتیکان',
        'VC': 'سنت وینسنت و گرنادین',
        'VE': 'ونزوئلا',
        'VG': 'جزایر ویرجین بریتانیا',
        'VI': 'جزایر ویرجین ایالات متحده',
        'VN': 'ویتنام',
        'VU': 'وانواتو',
        'WF': 'والیس و فوتونا',
        'WS': 'ساموآ',
        'XK': 'کوزوو',
        'YE': 'یمن',
        'YT': 'مایوت',
        'ZA': 'افریقای جنوبی',
        'ZM': 'زامبیا',
        'ZW': 'زیمبابوه',
      },
      'fr': <String, String>{
        'AC': 'Île de l’Ascension',
        'AD': 'Andorre',
        'AE': 'Émirats arabes unis',
        'AF': 'Afghanistan',
        'AG': 'Antigua-et-Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albanie',
        'AM': 'Arménie',
        'AO': 'Angola',
        'AQ': 'Antarctique',
        'AR': 'Argentine',
        'AS': 'Samoa américaines',
        'AT': 'Autriche',
        'AU': 'Australie',
        'AW': 'Aruba',
        'AX': 'Îles Åland',
        'AZ': 'Azerbaïdjan',
        'BA': 'Bosnie-Herzégovine',
        'BB': 'Barbade',
        'BD': 'Bangladesh',
        'BE': 'Belgique',
        'BF': 'Burkina Faso',
        'BG': 'Bulgarie',
        'BH': 'Bahreïn',
        'BI': 'Burundi',
        'BJ': 'Bénin',
        'BL': 'Saint-Barthélemy',
        'BM': 'Bermudes',
        'BN': 'Brunei',
        'BO': 'Bolivie',
        'BQ': 'Pays-Bas caribéens',
        'BR': 'Brésil',
        'BS': 'Bahamas',
        'BT': 'Bhoutan',
        'BV': 'Île Bouvet',
        'BW': 'Botswana',
        'BY': 'Biélorussie',
        'BZ': 'Belize',
        'CA': 'Canada',
        'CC': 'Îles Cocos',
        'CD': 'Congo-Kinshasa',
        'CF': 'République centrafricaine',
        'CG': 'Congo-Brazzaville',
        'CH': 'Suisse',
        'CI': 'Côte d’Ivoire',
        'CK': 'Îles Cook',
        'CL': 'Chili',
        'CM': 'Cameroun',
        'CN': 'Chine',
        'CO': 'Colombie',
        'CP': 'Île Clipperton',
        'CQ': 'Sercq',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cap-Vert',
        'CW': 'Curaçao',
        'CX': 'Île Christmas',
        'CY': 'Chypre',
        'CZ': 'Tchéquie',
        'DE': 'Allemagne',
        'DG': 'Diego Garcia',
        'DJ': 'Djibouti',
        'DK': 'Danemark',
        'DM': 'Dominique',
        'DO': 'République dominicaine',
        'DZ': 'Algérie',
        'EA': 'Ceuta et Melilla',
        'EC': 'Équateur',
        'EE': 'Estonie',
        'EG': 'Égypte',
        'EH': 'Sahara occidental',
        'ER': 'Érythrée',
        'ES': 'Espagne',
        'ET': 'Éthiopie',
        'FI': 'Finlande',
        'FJ': 'Fidji',
        'FK': 'Îles Malouines',
        'FM': 'Micronésie',
        'FO': 'Îles Féroé',
        'FR': 'France',
        'GA': 'Gabon',
        'GB': 'Royaume-Uni',
        'GD': 'Grenade',
        'GE': 'Géorgie',
        'GF': 'Guyane française',
        'GG': 'Guernesey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Groenland',
        'GM': 'Gambie',
        'GN': 'Guinée',
        'GP': 'Guadeloupe',
        'GQ': 'Guinée équatoriale',
        'GR': 'Grèce',
        'GS': 'Géorgie du Sud-et-les Îles Sandwich du Sud',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinée-Bissau',
        'GY': 'Guyana',
        'HK': 'R.A.S. chinoise de Hong Kong',
        'HM': 'Îles Heard-et-MacDonald',
        'HN': 'Honduras',
        'HR': 'Croatie',
        'HT': 'Haïti',
        'HU': 'Hongrie',
        'IC': 'Îles Canaries',
        'ID': 'Indonésie',
        'IE': 'Irlande',
        'IL': 'Israël',
        'IM': 'Île de Man',
        'IN': 'Inde',
        'IO': 'Territoire britannique de l’océan Indien',
        'IQ': 'Irak',
        'IR': 'Iran',
        'IS': 'Islande',
        'IT': 'Italie',
        'JE': 'Jersey',
        'JM': 'Jamaïque',
        'JO': 'Jordanie',
        'JP': 'Japon',
        'KE': 'Kenya',
        'KG': 'Kirghizstan',
        'KH': 'Cambodge',
        'KI': 'Kiribati',
        'KM': 'Comores',
        'KN': 'Saint-Christophe-et-Niévès',
        'KP': 'Corée du Nord',
        'KR': 'Corée du Sud',
        'KW': 'Koweït',
        'KY': 'Îles Caïmans',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Liban',
        'LC': 'Sainte-Lucie',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lituanie',
        'LU': 'Luxembourg',
        'LV': 'Lettonie',
        'LY': 'Libye',
        'MA': 'Maroc',
        'MC': 'Monaco',
        'MD': 'Moldavie',
        'ME': 'Monténégro',
        'MF': 'Saint-Martin',
        'MG': 'Madagascar',
        'MH': 'Îles Marshall',
        'MK': 'Macédoine du Nord',
        'ML': 'Mali',
        'MM': 'Myanmar (Birmanie)',
        'MN': 'Mongolie',
        'MO': 'R.A.S. chinoise de Macao',
        'MP': 'Îles Mariannes du Nord',
        'MQ': 'Martinique',
        'MR': 'Mauritanie',
        'MS': 'Montserrat',
        'MT': 'Malte',
        'MU': 'Maurice',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexique',
        'MY': 'Malaisie',
        'MZ': 'Mozambique',
        'NA': 'Namibie',
        'NC': 'Nouvelle-Calédonie',
        'NE': 'Niger',
        'NF': 'Île Norfolk',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Pays-Bas',
        'NO': 'Norvège',
        'NP': 'Népal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'Nouvelle-Zélande',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Pérou',
        'PF': 'Polynésie française',
        'PG': 'Papouasie-Nouvelle-Guinée',
        'PH': 'Philippines',
        'PK': 'Pakistan',
        'PL': 'Pologne',
        'PM': 'Saint-Pierre-et-Miquelon',
        'PN': 'Îles Pitcairn',
        'PR': 'Porto Rico',
        'PS': 'Territoires palestiniens',
        'PT': 'Portugal',
        'PW': 'Palaos',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'La Réunion',
        'RO': 'Roumanie',
        'RS': 'Serbie',
        'RU': 'Russie',
        'RW': 'Rwanda',
        'SA': 'Arabie saoudite',
        'SB': 'Îles Salomon',
        'SC': 'Seychelles',
        'SD': 'Soudan',
        'SE': 'Suède',
        'SG': 'Singapour',
        'SH': 'Sainte-Hélène',
        'SI': 'Slovénie',
        'SJ': 'Svalbard et Jan Mayen',
        'SK': 'Slovaquie',
        'SL': 'Sierra Leone',
        'SM': 'Saint-Marin',
        'SN': 'Sénégal',
        'SO': 'Somalie',
        'SR': 'Suriname',
        'SS': 'Soudan du Sud',
        'ST': 'Sao Tomé-et-Principe',
        'SV': 'Salvador',
        'SX': 'Saint-Martin (partie néerlandaise)',
        'SY': 'Syrie',
        'SZ': 'Eswatini',
        'TA': 'Tristan da Cunha',
        'TC': 'Îles Turques-et-Caïques',
        'TD': 'Tchad',
        'TF': 'Terres australes françaises',
        'TG': 'Togo',
        'TH': 'Thaïlande',
        'TJ': 'Tadjikistan',
        'TK': 'Tokelau',
        'TL': 'Timor oriental',
        'TM': 'Turkménistan',
        'TN': 'Tunisie',
        'TO': 'Tonga',
        'TR': 'Turquie',
        'TT': 'Trinité-et-Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taïwan',
        'TZ': 'Tanzanie',
        'UA': 'Ukraine',
        'UG': 'Ouganda',
        'UM': 'Îles mineures éloignées des États-Unis',
        'US': 'États-Unis',
        'UY': 'Uruguay',
        'UZ': 'Ouzbékistan',
        'VA': 'État de la Cité du Vatican',
        'VC': 'Saint-Vincent-et-les Grenadines',
        'VE': 'Venezuela',
        'VG': 'Îles Vierges britanniques',
        'VI': 'Îles Vierges des États-Unis',
        'VN': 'Viêt Nam',
        'VU': 'Vanuatu',
        'WF': 'Wallis-et-Futuna',
        'WS': 'Samoa',
        'XK': 'Kosovo',
        'YE': 'Yémen',
        'YT': 'Mayotte',
        'ZA': 'Afrique du Sud',
        'ZM': 'Zambie',
        'ZW': 'Zimbabwe',
      },
      'id': <String, String>{
        'AC': 'Pulau Ascension',
        'AD': 'Andorra',
        'AE': 'Uni Emirat Arab',
        'AF': 'Afganistan',
        'AG': 'Antigua dan Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AO': 'Angola',
        'AQ': 'Antarktika',
        'AR': 'Argentina',
        'AS': 'Samoa Amerika',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Kepulauan Aland',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia dan Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgia',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'Saint Barthélemy',
        'BM': 'Bermuda',
        'BN': 'Brunei',
        'BO': 'Bolivia',
        'BQ': 'Belanda Karibia',
        'BR': 'Brasil',
        'BS': 'Bahama',
        'BT': 'Bhutan',
        'BV': 'Pulau Bouvet',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Kanada',
        'CC': 'Kepulauan Cocos (Keeling)',
        'CD': 'Kongo - Kinshasa',
        'CF': 'Republik Afrika Tengah',
        'CG': 'Kongo - Brazzaville',
        'CH': 'Swiss',
        'CI': 'Côte d’Ivoire',
        'CK': 'Kepulauan Cook',
        'CL': 'Cile',
        'CM': 'Kamerun',
        'CN': 'Tiongkok',
        'CO': 'Kolombia',
        'CP': 'Pulau Clipperton',
        'CQ': 'Sark',
        'CR': 'Kosta Rika',
        'CU': 'Kuba',
        'CV': 'Tanjung Verde',
        'CW': 'Curaçao',
        'CX': 'Pulau Natal',
        'CY': 'Siprus',
        'CZ': 'Ceko',
        'DE': 'Jerman',
        'DG': 'Diego Garcia',
        'DJ': 'Jibuti',
        'DK': 'Denmark',
        'DM': 'Dominika',
        'DO': 'Republik Dominika',
        'DZ': 'Aljazair',
        'EA': 'Ceuta dan Melilla',
        'EC': 'Ekuador',
        'EE': 'Estonia',
        'EG': 'Mesir',
        'EH': 'Sahara Barat',
        'ER': 'Eritrea',
        'ES': 'Spanyol',
        'ET': 'Etiopia',
        'FI': 'Finlandia',
        'FJ': 'Fiji',
        'FK': 'Kepulauan Falkland',
        'FM': 'Mikronesia',
        'FO': 'Kepulauan Faroe',
        'FR': 'Prancis',
        'GA': 'Gabon',
        'GB': 'Inggris Raya',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'Guyana Prancis',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Guinea Ekuatorial',
        'GR': 'Yunani',
        'GS': 'Georgia Selatan & Kep. Sandwich Selatan',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea-Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong DAK Tiongkok',
        'HM': 'Pulau Heard dan Kepulauan McDonald',
        'HN': 'Honduras',
        'HR': 'Kroasia',
        'HT': 'Haiti',
        'HU': 'Hungaria',
        'IC': 'Kepulauan Canaria',
        'ID': 'Indonesia',
        'IE': 'Irlandia',
        'IL': 'Israel',
        'IM': 'Pulau Man',
        'IN': 'India',
        'IO': 'Wilayah Inggris di Samudra Hindia',
        'IQ': 'Irak',
        'IR': 'Iran',
        'IS': 'Islandia',
        'IT': 'Italia',
        'JE': 'Jersey',
        'JM': 'Jamaika',
        'JO': 'Yordania',
        'JP': 'Jepang',
        'KE': 'Kenya',
        'KG': 'Kirgizstan',
        'KH': 'Kamboja',
        'KI': 'Kiribati',
        'KM': 'Komoro',
        'KN': 'Saint Kitts dan Nevis',
        'KP': 'Korea Utara',
        'KR': 'Korea Selatan',
        'KW': 'Kuwait',
        'KY': 'Kepulauan Cayman',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lebanon',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lituania',
        'LU': 'Luksemburg',
        'LV': 'Latvia',
        'LY': 'Libya',
        'MA': 'Maroko',
        'MC': 'Monako',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MF': 'Saint Martin',
        'MG': 'Madagaskar',
        'MH': 'Kepulauan Marshall',
        'MK': 'Makedonia Utara',
        'ML': 'Mali',
        'MM': 'Myanmar (Burma)',
        'MN': 'Mongolia',
        'MO': 'Makau DAK Tiongkok',
        'MP': 'Kepulauan Mariana Utara',
        'MQ': 'Martinik',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maladewa',
        'MW': 'Malawi',
        'MX': 'Meksiko',
        'MY': 'Malaysia',
        'MZ': 'Mozambik',
        'NA': 'Namibia',
        'NC': 'Kaledonia Baru',
        'NE': 'Niger',
        'NF': 'Kepulauan Norfolk',
        'NG': 'Nigeria',
        'NI': 'Nikaragua',
        'NL': 'Belanda',
        'NO': 'Norwegia',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'Selandia Baru',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'Polinesia Prancis',
        'PG': 'Papua Nugini',
        'PH': 'Filipina',
        'PK': 'Pakistan',
        'PL': 'Polandia',
        'PM': 'Saint Pierre dan Miquelon',
        'PN': 'Kepulauan Pitcairn',
        'PR': 'Puerto Riko',
        'PS': 'Wilayah Palestina',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Réunion',
        'RO': 'Rumania',
        'RS': 'Serbia',
        'RU': 'Rusia',
        'RW': 'Rwanda',
        'SA': 'Arab Saudi',
        'SB': 'Kepulauan Solomon',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Swedia',
        'SG': 'Singapura',
        'SH': 'Saint Helena',
        'SI': 'Slovenia',
        'SJ': 'Kepulauan Svalbard dan Jan Mayen',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Suriname',
        'SS': 'Sudan Selatan',
        'ST': 'Sao Tome dan Principe',
        'SV': 'El Salvador',
        'SX': 'Sint Maarten',
        'SY': 'Suriah',
        'SZ': 'eSwatini',
        'TA': 'Tristan da Cunha',
        'TC': 'Kepulauan Turks dan Caicos',
        'TD': 'Chad',
        'TF': 'Wilayah Selatan Prancis',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor Leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TR': 'Turki',
        'TT': 'Trinidad dan Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraina',
        'UG': 'Uganda',
        'UM': 'Kepulauan Terluar AS',
        'US': 'Amerika Serikat',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Vatikan',
        'VC': 'Saint Vincent dan Grenadine',
        'VE': 'Venezuela',
        'VG': 'Kepulauan Virgin Britania Raya',
        'VI': 'Kepulauan Virgin Amerika Serikat',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Kepulauan Wallis dan Futuna',
        'WS': 'Samoa',
        'XK': 'Kosovo',
        'YE': 'Yaman',
        'YT': 'Mayotte',
        'ZA': 'Afrika Selatan',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe',
      },
      'ms': <String, String>{
        'AC': 'Pulau Ascension',
        'AD': 'Andorra',
        'AE': 'Emiriah Arab Bersatu',
        'AF': 'Afghanistan',
        'AG': 'Antigua dan Barbuda',
        'AI': 'Anguilla',
        'AL': 'Albania',
        'AM': 'Armenia',
        'AO': 'Angola',
        'AQ': 'Antartika',
        'AR': 'Argentina',
        'AS': 'Samoa Amerika',
        'AT': 'Austria',
        'AU': 'Australia',
        'AW': 'Aruba',
        'AX': 'Kepulauan Aland',
        'AZ': 'Azerbaijan',
        'BA': 'Bosnia dan Herzegovina',
        'BB': 'Barbados',
        'BD': 'Bangladesh',
        'BE': 'Belgium',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaria',
        'BH': 'Bahrain',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'St. Barthelemy',
        'BM': 'Bermuda',
        'BN': 'Brunei',
        'BO': 'Bolivia',
        'BQ': 'Belanda Caribbean',
        'BR': 'Brazil',
        'BS': 'Bahamas',
        'BT': 'Bhutan',
        'BV': 'Pulau Bouvet',
        'BW': 'Botswana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Kanada',
        'CC': 'Kepulauan Cocos (Keeling)',
        'CD': 'Congo - Kinshasa',
        'CF': 'Republik Afrika Tengah',
        'CG': 'Congo - Brazzaville',
        'CH': 'Switzerland',
        'CI': 'Cote d’Ivoire',
        'CK': 'Kepulauan Cook',
        'CL': 'Chile',
        'CM': 'Cameroon',
        'CN': 'China',
        'CO': 'Colombia',
        'CP': 'Pulau Clipperton',
        'CQ': 'Sark',
        'CR': 'Costa Rica',
        'CU': 'Cuba',
        'CV': 'Cape Verde',
        'CW': 'Curacao',
        'CX': 'Pulau Krismas',
        'CY': 'Cyprus',
        'CZ': 'Czechia',
        'DE': 'Jerman',
        'DG': 'Diego Garcia',
        'DJ': 'Djibouti',
        'DK': 'Denmark',
        'DM': 'Dominica',
        'DO': 'Republik Dominica',
        'DZ': 'Algeria',
        'EA': 'Ceuta dan Melilla',
        'EC': 'Ecuador',
        'EE': 'Estonia',
        'EG': 'Mesir',
        'EH': 'Sahara Barat',
        'ER': 'Eritrea',
        'ES': 'Sepanyol',
        'ET': 'Ethiopia',
        'FI': 'Finland',
        'FJ': 'Fiji',
        'FK': 'Kepulauan Falkland',
        'FM': 'Micronesia',
        'FO': 'Kepulauan Faroe',
        'FR': 'Perancis',
        'GA': 'Gabon',
        'GB': 'United Kingdom',
        'GD': 'Grenada',
        'GE': 'Georgia',
        'GF': 'Guiana Perancis',
        'GG': 'Guernsey',
        'GH': 'Ghana',
        'GI': 'Gibraltar',
        'GL': 'Greenland',
        'GM': 'Gambia',
        'GN': 'Guinea',
        'GP': 'Guadeloupe',
        'GQ': 'Guinea Khatulistiwa',
        'GR': 'Greece',
        'GS': 'Kepulauan Georgia Selatan & Sandwich Selatan',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Guinea Bissau',
        'GY': 'Guyana',
        'HK': 'Hong Kong SAR China',
        'HM': 'Kepulauan Heard & McDonald',
        'HN': 'Honduras',
        'HR': 'Croatia',
        'HT': 'Haiti',
        'HU': 'Hungary',
        'IC': 'Kepulauan Canary',
        'ID': 'Indonesia',
        'IE': 'Ireland',
        'IL': 'Israel',
        'IM': 'Isle of Man',
        'IN': 'India',
        'IO': 'Wilayah Lautan Hindi British',
        'IQ': 'Iraq',
        'IR': 'Iran',
        'IS': 'Iceland',
        'IT': 'Itali',
        'JE': 'Jersey',
        'JM': 'Jamaica',
        'JO': 'Jordan',
        'JP': 'Jepun',
        'KE': 'Kenya',
        'KG': 'Kyrgyzstan',
        'KH': 'Kemboja',
        'KI': 'Kiribati',
        'KM': 'Comoros',
        'KN': 'Saint Kitts dan Nevis',
        'KP': 'Korea Utara',
        'KR': 'Korea Selatan',
        'KW': 'Kuwait',
        'KY': 'Kepulauan Cayman',
        'KZ': 'Kazakhstan',
        'LA': 'Laos',
        'LB': 'Lubnan',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberia',
        'LS': 'Lesotho',
        'LT': 'Lithuania',
        'LU': 'Luxembourg',
        'LV': 'Latvia',
        'LY': 'Libya',
        'MA': 'Maghribi',
        'MC': 'Monaco',
        'MD': 'Moldova',
        'ME': 'Montenegro',
        'MF': 'Saint Martin',
        'MG': 'Madagaskar',
        'MH': 'Kepulauan Marshall',
        'MK': 'Macedonia Utara',
        'ML': 'Mali',
        'MM': 'Myanmar (Burma)',
        'MN': 'Mongolia',
        'MO': 'Macau SAR China',
        'MP': 'Kepulauan Mariana Utara',
        'MQ': 'Martinique',
        'MR': 'Mauritania',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldives',
        'MW': 'Malawi',
        'MX': 'Mexico',
        'MY': 'Malaysia',
        'MZ': 'Mozambique',
        'NA': 'Namibia',
        'NC': 'New Caledonia',
        'NE': 'Niger',
        'NF': 'Pulau Norfolk',
        'NG': 'Nigeria',
        'NI': 'Nicaragua',
        'NL': 'Belanda',
        'NO': 'Norway',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'New Zealand',
        'OM': 'Oman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'Polinesia Perancis',
        'PG': 'Papua New Guinea',
        'PH': 'Filipina',
        'PK': 'Pakistan',
        'PL': 'Poland',
        'PM': 'Saint Pierre dan Miquelon',
        'PN': 'Kepulauan Pitcairn',
        'PR': 'Puerto Rico',
        'PS': 'Wilayah Palestin',
        'PT': 'Portugal',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Qatar',
        'RE': 'Reunion',
        'RO': 'Romania',
        'RS': 'Serbia',
        'RU': 'Rusia',
        'RW': 'Rwanda',
        'SA': 'Arab Saudi',
        'SB': 'Kepulauan Solomon',
        'SC': 'Seychelles',
        'SD': 'Sudan',
        'SE': 'Sweden',
        'SG': 'Singapura',
        'SH': 'Saint Helena',
        'SI': 'Slovenia',
        'SJ': 'Svalbard dan Jan Mayen',
        'SK': 'Slovakia',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somalia',
        'SR': 'Surinam',
        'SS': 'Sudan Selatan',
        'ST': 'Sao Tome dan Principe',
        'SV': 'El Salvador',
        'SX': 'Sint Maarten',
        'SY': 'Syria',
        'SZ': 'Eswatini',
        'TA': 'Tristan da Cunha',
        'TC': 'Kepulauan Turks dan Caicos',
        'TD': 'Chad',
        'TF': 'Wilayah Selatan Perancis',
        'TG': 'Togo',
        'TH': 'Thailand',
        'TJ': 'Tajikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-Leste',
        'TM': 'Turkmenistan',
        'TN': 'Tunisia',
        'TO': 'Tonga',
        'TR': 'Turkiye',
        'TT': 'Trinidad dan Tobago',
        'TV': 'Tuvalu',
        'TW': 'Taiwan',
        'TZ': 'Tanzania',
        'UA': 'Ukraine',
        'UG': 'Uganda',
        'UM': 'Kepulauan Terpencil A.S.',
        'US': 'Amerika Syarikat',
        'UY': 'Uruguay',
        'UZ': 'Uzbekistan',
        'VA': 'Kota Vatican',
        'VC': 'Saint Vincent dan Grenadines',
        'VE': 'Venezuela',
        'VG': 'Kepulauan Virgin British',
        'VI': 'Kepulauan Virgin A.S.',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis dan Futuna',
        'WS': 'Samoa',
        'XK': 'Kosovo',
        'YE': 'Yaman',
        'YT': 'Mayotte',
        'ZA': 'Afrika Selatan',
        'ZM': 'Zambia',
        'ZW': 'Zimbabwe',
      },
      'pa': <String, String>{
        'AC': 'ਅਸੈਂਸ਼ਨ ਟਾਪੂ',
        'AD': 'ਅੰਡੋਰਾ',
        'AE': 'ਸੰਯੁਕਤ ਅਰਬ ਅਮੀਰਾਤ',
        'AF': 'ਅਫ਼ਗਾਨਿਸਤਾਨ',
        'AG': 'ਐਂਟੀਗੁਆ ਅਤੇ ਬਾਰਬੁਡਾ',
        'AI': 'ਅੰਗੁਇਲਾ',
        'AL': 'ਅਲਬਾਨੀਆ',
        'AM': 'ਅਰਮੀਨੀਆ',
        'AO': 'ਅੰਗੋਲਾ',
        'AQ': 'ਅੰਟਾਰਕਟਿਕਾ',
        'AR': 'ਅਰਜਨਟੀਨਾ',
        'AS': 'ਅਮੈਰੀਕਨ ਸਮੋਆ',
        'AT': 'ਆਸਟਰੀਆ',
        'AU': 'ਆਸਟ੍ਰੇਲੀਆ',
        'AW': 'ਅਰੂਬਾ',
        'AX': 'ਅਲੈਂਡ ਟਾਪੂ',
        'AZ': 'ਅਜ਼ਰਬਾਈਜਾਨ',
        'BA': 'ਬੋਸਨੀਆ ਅਤੇ ਹਰਜ਼ੇਗੋਵੀਨਾ',
        'BB': 'ਬਾਰਬਾਡੋਸ',
        'BD': 'ਬੰਗਲਾਦੇਸ਼',
        'BE': 'ਬੈਲਜੀਅਮ',
        'BF': 'ਬੁਰਕੀਨਾ ਫ਼ਾਸੋ',
        'BG': 'ਬੁਲਗਾਰੀਆ',
        'BH': 'ਬਹਿਰੀਨ',
        'BI': 'ਬੁਰੁੰਡੀ',
        'BJ': 'ਬੇਨਿਨ',
        'BL': 'ਸੇਂਟ ਬਾਰਥੇਲੇਮੀ',
        'BM': 'ਬਰਮੂਡਾ',
        'BN': 'ਬਰੂਨੇਈ',
        'BO': 'ਬੋਲੀਵੀਆ',
        'BQ': 'ਕੈਰੇਬੀਆਈ ਨੀਦਰਲੈਂਡ',
        'BR': 'ਬ੍ਰਾਜ਼ੀਲ',
        'BS': 'ਬਹਾਮਾਸ',
        'BT': 'ਭੂਟਾਨ',
        'BV': 'ਬੌਵੇਟ ਟਾਪੂ',
        'BW': 'ਬੋਤਸਵਾਨਾ',
        'BY': 'ਬੇਲਾਰੂਸ',
        'BZ': 'ਬੇਲੀਜ਼',
        'CA': 'ਕੈਨੇਡਾ',
        'CC': 'ਕੋਕੋਸ (ਕੀਲਿੰਗ) ਟਾਪੂ',
        'CD': 'ਕਾਂਗੋ - ਕਿੰਸ਼ਾਸਾ',
        'CF': 'ਕੇਂਦਰੀ ਅਫ਼ਰੀਕੀ ਗਣਰਾਜ',
        'CG': 'ਕਾਂਗੋ - ਬ੍ਰਾਜ਼ਾਵਿਲੇ',
        'CH': 'ਸਵਿਟਜ਼ਰਲੈਂਡ',
        'CI': 'ਕੋਟ ਡੀਵੋਆਰ',
        'CK': 'ਕੁੱਕ ਟਾਪੂ',
        'CL': 'ਚਿਲੀ',
        'CM': 'ਕੈਮਰੂਨ',
        'CN': 'ਚੀਨ',
        'CO': 'ਕੋਲੰਬੀਆ',
        'CP': 'ਕਲਿੱਪਰਟਨ ਟਾਪੂ',
        'CQ': 'ਸਾਰਕ',
        'CR': 'ਕੋਸਟਾ ਰੀਕਾ',
        'CU': 'ਕਿਊਬਾ',
        'CV': 'ਕੇਪ ਵਰਡੇ',
        'CW': 'ਕੁਰਾਕਾਓ',
        'CX': 'ਕ੍ਰਿਸਮਿਸ ਟਾਪੂ',
        'CY': 'ਸਾਇਪ੍ਰਸ',
        'CZ': 'ਚੈਕੀਆ',
        'DE': 'ਜਰਮਨੀ',
        'DG': 'ਡੀਇਗੋ ਗਾਰਸੀਆ',
        'DJ': 'ਜਿਬੂਤੀ',
        'DK': 'ਡੈਨਮਾਰਕ',
        'DM': 'ਡੋਮੀਨਿਕਾ',
        'DO': 'ਡੋਮੀਨਿਕਾਈ ਗਣਰਾਜ',
        'DZ': 'ਅਲਜੀਰੀਆ',
        'EA': 'ਸਿਓਟਾ ਅਤੇ ਮੇਲਿੱਲਾ',
        'EC': 'ਇਕਵੇਡੋਰ',
        'EE': 'ਇਸਟੋਨੀਆ',
        'EG': 'ਮਿਸਰ',
        'EH': 'ਪੱਛਮੀ ਸਹਾਰਾ',
        'ER': 'ਇਰੀਟ੍ਰਿਆ',
        'ES': 'ਸਪੇਨ',
        'ET': 'ਇਥੋਪੀਆ',
        'FI': 'ਫਿਨਲੈਂਡ',
        'FJ': 'ਫ਼ਿਜੀ',
        'FK': 'ਫ਼ਾਕਲੈਂਡ ਟਾਪੂ',
        'FM': 'ਮਾਇਕ੍ਰੋਨੇਸ਼ੀਆ',
        'FO': 'ਫੈਰੋ ਟਾਪੂ',
        'FR': 'ਫ਼ਰਾਂਸ',
        'GA': 'ਗਬੋਨ',
        'GB': 'ਯੂਨਾਈਟਡ ਕਿੰਗਡਮ',
        'GD': 'ਗ੍ਰੇਨਾਡਾ',
        'GE': 'ਜਾਰਜੀਆ',
        'GF': 'ਫਰੈਂਚ ਗੁਇਆਨਾ',
        'GG': 'ਗਰਨਜੀ',
        'GH': 'ਘਾਨਾ',
        'GI': 'ਜਿਬਰਾਲਟਰ',
        'GL': 'ਗ੍ਰੀਨਲੈਂਡ',
        'GM': 'ਗੈਂਬੀਆ',
        'GN': 'ਗਿਨੀ',
        'GP': 'ਗੁਆਡੇਲੋਪ',
        'GQ': 'ਭੂ-ਖੰਡੀ ਗਿਨੀ',
        'GR': 'ਗ੍ਰੀਸ',
        'GS': 'ਦੱਖਣੀ ਜਾਰਜੀਆ ਅਤੇ ਦੱਖਣੀ ਸੈਂਡਵਿਚ ਟਾਪੂ',
        'GT': 'ਗੁਆਟੇਮਾਲਾ',
        'GU': 'ਗੁਆਮ',
        'GW': 'ਗਿਨੀ-ਬਿਸਾਉ',
        'GY': 'ਗੁਯਾਨਾ',
        'HK': 'ਹਾਂਗ ਕਾਂਗ ਐਸਏਆਰ ਚੀਨ',
        'HM': 'ਹਰਡ ਤੇ ਮੈਕਡੋਨਾਲਡ ਟਾਪੂ',
        'HN': 'ਹੋਂਡੁਰਸ',
        'HR': 'ਕਰੋਏਸ਼ੀਆ',
        'HT': 'ਹੈਤੀ',
        'HU': 'ਹੰਗਰੀ',
        'IC': 'ਕੇਨਾਰੀ ਟਾਪੂ',
        'ID': 'ਇੰਡੋਨੇਸ਼ੀਆ',
        'IE': 'ਆਇਰਲੈਂਡ',
        'IL': 'ਇਜ਼ਰਾਈਲ',
        'IM': 'ਆਇਲ ਆਫ ਮੈਨ',
        'IN': 'ਭਾਰਤ',
        'IO': 'ਬਰਤਾਨਵੀ ਹਿੰਦ ਮਹਾਂਸਾਗਰ ਖਿੱਤਾ',
        'IQ': 'ਇਰਾਕ',
        'IR': 'ਈਰਾਨ',
        'IS': 'ਆਈਸਲੈਂਡ',
        'IT': 'ਇਟਲੀ',
        'JE': 'ਜਰਸੀ',
        'JM': 'ਜਮਾਇਕਾ',
        'JO': 'ਜੌਰਡਨ',
        'JP': 'ਜਪਾਨ',
        'KE': 'ਕੀਨੀਆ',
        'KG': 'ਕਿਰਗਿਜ਼ਸਤਾਨ',
        'KH': 'ਕੰਬੋਡੀਆ',
        'KI': 'ਕਿਰਬਾਤੀ',
        'KM': 'ਕੋਮੋਰੋਸ',
        'KN': 'ਸੇਂਟ ਕਿਟਸ ਐਂਡ ਨੇਵਿਸ',
        'KP': 'ਉੱਤਰੀ ਕੋਰੀਆ',
        'KR': 'ਦੱਖਣੀ ਕੋਰੀਆ',
        'KW': 'ਕੁਵੈਤ',
        'KY': 'ਕੇਮੈਨ ਟਾਪੂ',
        'KZ': 'ਕਜ਼ਾਖਸਤਾਨ',
        'LA': 'ਲਾਓਸ',
        'LB': 'ਲਿਬਨਾਨ',
        'LC': 'ਸੇਂਟ ਲੂਸੀਆ',
        'LI': 'ਲਿਚੇਂਸਟਾਇਨ',
        'LK': 'ਸ੍ਰੀ ਲੰਕਾ',
        'LR': 'ਲਾਈਬੀਰੀਆ',
        'LS': 'ਲੇਸੋਥੋ',
        'LT': 'ਲਿਥੁਆਨੀਆ',
        'LU': 'ਲਕਜ਼ਮਬਰਗ',
        'LV': 'ਲਾਤਵੀਆ',
        'LY': 'ਲੀਬੀਆ',
        'MA': 'ਮੋਰੱਕੋ',
        'MC': 'ਮੋਨਾਕੋ',
        'MD': 'ਮੋਲਡੋਵਾ',
        'ME': 'ਮੋਂਟੇਨੇਗਰੋ',
        'MF': 'ਸੇਂਟ ਮਾਰਟਿਨ',
        'MG': 'ਮੈਡਾਗਾਸਕਰ',
        'MH': 'ਮਾਰਸ਼ਲ ਟਾਪੂ',
        'MK': 'ਉੱਤਰੀ ਮੈਕਡੋਨੀਆ',
        'ML': 'ਮਾਲੀ',
        'MM': 'ਮਿਆਂਮਾਰ (ਬਰਮਾ)',
        'MN': 'ਮੰਗੋਲੀਆ',
        'MO': 'ਮਕਾਉ ਐਸਏਆਰ ਚੀਨ',
        'MP': 'ਉੱਤਰੀ ਮਾਰੀਆਨਾ ਟਾਪੂ',
        'MQ': 'ਮਾਰਟੀਨਿਕ',
        'MR': 'ਮੋਰਿਟਾਨੀਆ',
        'MS': 'ਮੋਂਟਸੇਰਾਤ',
        'MT': 'ਮਾਲਟਾ',
        'MU': 'ਮੌਰੀਸ਼ਸ',
        'MV': 'ਮਾਲਦੀਵ',
        'MW': 'ਮਲਾਵੀ',
        'MX': 'ਮੈਕਸੀਕੋ',
        'MY': 'ਮਲੇਸ਼ੀਆ',
        'MZ': 'ਮੋਜ਼ਾਮਬੀਕ',
        'NA': 'ਨਾਮੀਬੀਆ',
        'NC': 'ਨਿਊ ਕੈਲੇਡੋਨੀਆ',
        'NE': 'ਨਾਈਜਰ',
        'NF': 'ਨੋਰਫੌਕ ਟਾਪੂ',
        'NG': 'ਨਾਈਜੀਰੀਆ',
        'NI': 'ਨਿਕਾਰਾਗੁਆ',
        'NL': 'ਨੀਦਰਲੈਂਡ',
        'NO': 'ਨਾਰਵੇ',
        'NP': 'ਨੇਪਾਲ',
        'NR': 'ਨਾਉਰੂ',
        'NU': 'ਨਿਯੂ',
        'NZ': 'ਨਿਊਜ਼ੀਲੈਂਡ',
        'OM': 'ਓਮਾਨ',
        'PA': 'ਪਨਾਮਾ',
        'PE': 'ਪੇਰੂ',
        'PF': 'ਫਰੈਂਚ ਪੋਲੀਨੇਸ਼ੀਆ',
        'PG': 'ਪਾਪੂਆ ਨਿਊ ਗਿਨੀ',
        'PH': 'ਫਿਲੀਪੀਨਜ',
        'PK': 'ਪਾਕਿਸਤਾਨ',
        'PL': 'ਪੋਲੈਂਡ',
        'PM': 'ਸੇਂਟ ਪੀਅਰੇ ਐਂਡ ਮਿਕੇਲਨ',
        'PN': 'ਪਿਟਕੇਰਨ ਟਾਪੂ',
        'PR': 'ਪਿਊਰਟੋ ਰਿਕੋ',
        'PS': 'ਫਿਲਸਤੀਨੀ ਖਿੱਤੇ',
        'PT': 'ਪੁਰਤਗਾਲ',
        'PW': 'ਪਲਾਉ',
        'PY': 'ਪੈਰਾਗਵੇ',
        'QA': 'ਕਤਰ',
        'RE': 'ਰਿਯੂਨੀਅਨ',
        'RO': 'ਰੋਮਾਨੀਆ',
        'RS': 'ਸਰਬੀਆ',
        'RU': 'ਰੂਸ',
        'RW': 'ਰਵਾਂਡਾ',
        'SA': 'ਸਾਊਦੀ ਅਰਬ',
        'SB': 'ਸੋਲੋਮਨ ਟਾਪੂ',
        'SC': 'ਸੇਸ਼ਲਸ',
        'SD': 'ਸੂਡਾਨ',
        'SE': 'ਸਵੀਡਨ',
        'SG': 'ਸਿੰਗਾਪੁਰ',
        'SH': 'ਸੇਂਟ ਹੇਲੇਨਾ',
        'SI': 'ਸਲੋਵੇਨੀਆ',
        'SJ': 'ਸਵਾਲਬਰਡ ਅਤੇ ਜਾਨ ਮਾਯੇਨ',
        'SK': 'ਸਲੋਵਾਕੀਆ',
        'SL': 'ਸਿਏਰਾ ਲਿਓਨ',
        'SM': 'ਸੈਨ ਮਰੀਨੋ',
        'SN': 'ਸੇਨੇਗਲ',
        'SO': 'ਸੋਮਾਲੀਆ',
        'SR': 'ਸੂਰੀਨਾਮ',
        'SS': 'ਦੱਖਣ ਸੁਡਾਨ',
        'ST': 'ਸਾਓ ਟੋਮ ਅਤੇ ਪ੍ਰਿੰਸੀਪੇ',
        'SV': 'ਅਲ ਸਲਵਾਡੋਰ',
        'SX': 'ਸਿੰਟ ਮਾਰਟੀਨ',
        'SY': 'ਸੀਰੀਆ',
        'SZ': 'ਇਸਵਾਤੀਨੀ',
        'TA': 'ਟ੍ਰਿਸਟਾਨ ਦਾ ਕੁੰਹਾ',
        'TC': 'ਟੁਰਕਸ ਅਤੇ ਕੈਕੋਸ ਟਾਪੂ',
        'TD': 'ਚਾਡ',
        'TF': 'ਫਰੈਂਚ ਦੱਖਣੀ ਪ੍ਰਦੇਸ਼',
        'TG': 'ਟੋਗੋ',
        'TH': 'ਥਾਈਲੈਂਡ',
        'TJ': 'ਤਾਜਿਕਿਸਤਾਨ',
        'TK': 'ਟੋਕੇਲਾਉ',
        'TL': 'ਤਿਮੋਰ-ਲੇਸਤੇ',
        'TM': 'ਤੁਰਕਮੇਨਿਸਤਾਨ',
        'TN': 'ਟਿਊਨੀਸ਼ੀਆ',
        'TO': 'ਟੌਂਗਾ',
        'TR': 'ਤੁਰਕੀ',
        'TT': 'ਟ੍ਰਿਨੀਡਾਡ ਅਤੇ ਟੋਬਾਗੋ',
        'TV': 'ਟੁਵਾਲੂ',
        'TW': 'ਤਾਇਵਾਨ',
        'TZ': 'ਤਨਜ਼ਾਨੀਆ',
        'UA': 'ਯੂਕਰੇਨ',
        'UG': 'ਯੂਗਾਂਡਾ',
        'UM': 'ਯੂ.ਐੱਸ. ਦੂਰ-ਦੁਰਾਡੇ ਟਾਪੂ',
        'US': 'ਸੰਯੁਕਤ ਰਾਜ (ਅਮਰੀਕਾ)',
        'UY': 'ਉਰੂਗਵੇ',
        'UZ': 'ਉਜ਼ਬੇਕਿਸਤਾਨ',
        'VA': 'ਵੈਟੀਕਨ ਸਿਟੀ',
        'VC': 'ਸੇਂਟ ਵਿਨਸੈਂਟ ਐਂਡ ਗ੍ਰੇਨਾਡੀਨਸ',
        'VE': 'ਵੇਨੇਜ਼ੂਏਲਾ',
        'VG': 'ਬ੍ਰਿਟਿਸ਼ ਵਰਜਿਨ ਟਾਪੂ',
        'VI': 'ਯੂ ਐੱਸ ਵਰਜਿਨ ਟਾਪੂ',
        'VN': 'ਵੀਅਤਨਾਮ',
        'VU': 'ਵਾਨੂਆਟੂ',
        'WF': 'ਵਾਲਿਸ ਅਤੇ ਫੂਟੂਨਾ',
        'WS': 'ਸਾਮੋਆ',
        'XK': 'ਕੋਸੋਵੋ',
        'YE': 'ਯਮਨ',
        'YT': 'ਮਾਯੋਟੀ',
        'ZA': 'ਦੱਖਣੀ ਅਫਰੀਕਾ',
        'ZM': 'ਜ਼ਾਮਬੀਆ',
        'ZW': 'ਜ਼ਿੰਬਾਬਵੇ',
      },
      'ps': <String, String>{
        'AC': 'اسينشان ټاپو',
        'AD': 'اندورا',
        'AE': 'متحده عرب امارات',
        'AF': 'افغانستان',
        'AG': 'انټيګوا او باربودا',
        'AI': 'انګیلا',
        'AL': 'البانیه',
        'AM': 'ارمنستان',
        'AO': 'انګولا',
        'AQ': 'انتارکتیکا',
        'AR': 'ارجنټاين',
        'AS': 'امریکایی ساماوا',
        'AT': 'اتریش',
        'AU': 'آسټرالیا',
        'AW': 'آروبا',
        'AX': 'الاند ټاپوان',
        'AZ': 'اذربايجان',
        'BA': 'بوسنيا او هېرزګوينا',
        'BB': 'باربادوس',
        'BD': 'بنگله دېش',
        'BE': 'بیلجیم',
        'BF': 'بورکینا فاسو',
        'BG': 'بلغاریه',
        'BH': 'بحرين',
        'BI': 'بروندي',
        'BJ': 'بینن',
        'BL': 'سينټ بارتيلمي',
        'BM': 'برمودا',
        'BN': 'برونائي',
        'BO': 'بولیویا',
        'BQ': 'کیریبین هالینډ',
        'BR': 'برازیل',
        'BS': 'باهماس',
        'BT': 'بهوټان',
        'BV': 'بوویټ ټاپو',
        'BW': 'بوتسوانه',
        'BY': 'بیلاروس',
        'BZ': 'بلیز',
        'CA': 'کاناډا',
        'CC': 'کوکوز (کيلنګ) ټاپوګان',
        'CD': 'کانګو - کینشاسا',
        'CF': 'وسطي افريقا جمهور',
        'CG': 'کانګو - بروزوییل',
        'CH': 'سویس',
        'CI': 'د عاج ساحل',
        'CK': 'کوک ټاپوګان',
        'CL': 'چیلي',
        'CM': 'کامرون',
        'CN': 'چین',
        'CO': 'کولمبیا',
        'CP': 'د کلپرټون ټاپو',
        'CQ': 'سارک',
        'CR': 'کوستاریکا',
        'CU': 'کیوبا',
        'CV': 'کیپ ورد',
        'CW': 'کوراکاو',
        'CX': 'د کريسمس ټاپو',
        'CY': 'قبرس',
        'CZ': 'چکیا',
        'DE': 'المان',
        'DG': 'ډایګو ګارسیا',
        'DJ': 'جبوتي',
        'DK': 'ډنمارک',
        'DM': 'دومینیکا',
        'DO': 'جمهوريه ډومينيکن',
        'DZ': 'الجزایر',
        'EA': 'سيوتا او ماليلا',
        'EC': 'اکوادور',
        'EE': 'استونیا',
        'EG': 'مصر',
        'EH': 'لويديځ صحارا',
        'ER': 'اریتره',
        'ES': 'هسپانیه',
        'ET': 'حبشه',
        'FI': 'فنلینډ',
        'FJ': 'فجي',
        'FK': 'فاکلينډ ټاپوګان',
        'FM': 'میکرونیزیا',
        'FO': 'فارو ټاپو',
        'FR': 'فرانسه',
        'GA': 'ګابن',
        'GB': 'برتانیه',
        'GD': 'ګرنادا',
        'GE': 'گورجستان',
        'GF': 'فرانسوي ګانا',
        'GG': 'ګرنسي',
        'GH': 'ګانا',
        'GI': 'جبل الطارق',
        'GL': 'ګرینلینډ',
        'GM': 'ګامبیا',
        'GN': 'ګینه',
        'GP': 'ګوادلوپ',
        'GQ': 'استوایی ګیني',
        'GR': 'یونان',
        'GS': 'سويلي جارجيا او سويلي سېنډوچ ټاپوګان',
        'GT': 'ګواتیمالا',
        'GU': 'ګوام',
        'GW': 'ګینه بیسو',
        'GY': 'ګیانا',
        'HK': 'هانګ کانګ SAR چین',
        'HM': 'هارډ او ميکډانلډ ټاپوګان',
        'HN': 'هانډوراس',
        'HR': 'کرواشيا',
        'HT': 'هایټي',
        'HU': 'مجارستان',
        'IC': 'د کناري ټاپوګان',
        'ID': 'اندونیزیا',
        'IE': 'آيرلېنډ',
        'IL': 'اسراييل',
        'IM': 'د آئل آف مین',
        'IN': 'هند',
        'IO': 'د برتانوي هند سمندري سيمه',
        'IQ': 'عراق',
        'IR': 'ايران',
        'IS': 'آیسلینډ',
        'IT': 'ایټالیه',
        'JE': 'جرسی',
        'JM': 'جمیکا',
        'JO': 'اردن',
        'JP': 'جاپان',
        'KE': 'کینیا',
        'KG': 'قرغزستان',
        'KH': 'کمبودیا',
        'KI': 'کیري باتي',
        'KM': 'کوموروس',
        'KN': 'سینټ کټس او نیویس',
        'KP': 'شمالی کوریا',
        'KR': 'سویلي کوریا',
        'KW': 'کويت',
        'KY': 'کیمان ټاپوګان',
        'KZ': 'قزاقستان',
        'LA': 'لاوس',
        'LB': 'لبنان',
        'LC': 'سینټ لوسیا',
        'LI': 'لیختن اشتاین',
        'LK': 'سريلنکا',
        'LR': 'لايبيريا',
        'LS': 'لسوتو',
        'LT': 'لیتوانیا',
        'LU': 'لوګزامبورګ',
        'LV': 'ليتهويا',
        'LY': 'لیبیا',
        'MA': 'مراکش',
        'MC': 'موناکو',
        'MD': 'مولدوا',
        'ME': 'مونټینیګرو',
        'MF': 'سینټ مارټن',
        'MG': 'مدغاسکر',
        'MH': 'مارشل ټاپوګان',
        'MK': 'شمالي مقدونيه',
        'ML': 'مالي',
        'MM': 'ميانمار (برما)',
        'MN': 'منګوليا',
        'MO': 'مکاو SAR چین',
        'MP': 'شمالي ماريانا ټاپوګان',
        'MQ': 'مارټینیک',
        'MR': 'موریتانیا',
        'MS': 'مانټیسیرت',
        'MT': 'مالټا',
        'MU': 'موریشیس',
        'MV': 'مالديپ',
        'MW': 'مالاوي',
        'MX': 'میکسیکو',
        'MY': 'مالیزیا',
        'MZ': 'موزمبيق',
        'NA': 'نیمبیا',
        'NC': 'نوی کالیډونیا',
        'NE': 'نايجير',
        'NF': 'نارفولک ټاپوګان',
        'NG': 'نایجیریا',
        'NI': 'نکاراګوا',
        'NL': 'هالېنډ',
        'NO': 'ناروۍ',
        'NP': 'نیپال',
        'NR': 'نایرو',
        'NU': 'نیوو',
        'NZ': 'نیوزیلنډ',
        'OM': 'عمان',
        'PA': 'پاناما',
        'PE': 'پیرو',
        'PF': 'فرانسوي پولينيسيا',
        'PG': 'پاپوا نيو ګيني',
        'PH': 'فلپين',
        'PK': 'پاکستان',
        'PL': 'پولنډ',
        'PM': 'سینټ پییر او میکولون',
        'PN': 'پيټکيرن ټاپوګان',
        'PR': 'پورتو ریکو',
        'PS': 'فلسطیني سيمې',
        'PT': 'پورتګال',
        'PW': 'پلاؤ',
        'PY': 'پاراګوی',
        'QA': 'قطر',
        'RE': 'ریونین',
        'RO': 'رومانیا',
        'RS': 'سربيا',
        'RU': 'روسیه',
        'RW': 'روندا',
        'SA': 'سعودي عربستان',
        'SB': 'سليمان ټاپوګان',
        'SC': 'سیچیلیس',
        'SD': 'سوډان',
        'SE': 'سویډن',
        'SG': 'سينگاپور',
        'SH': 'سینټ هیلینا',
        'SI': 'سلوانیا',
        'SJ': 'سوالبارد او جان ميين',
        'SK': 'سلواکیا',
        'SL': 'سییرا لیون',
        'SM': 'سان مارینو',
        'SN': 'سينيګال',
        'SO': 'سومالیا',
        'SR': 'سورینام',
        'SS': 'سويلي سوډان',
        'ST': 'ساو ټیم او پرنسیپ',
        'SV': 'سالوېډور',
        'SX': 'سینټ مارټین',
        'SY': 'سوریه',
        'SZ': 'اسواټيني',
        'TA': 'تریستان دا کنها',
        'TC': 'د ترکیې او کیکاسو ټاپو',
        'TD': 'چاډ',
        'TF': 'د فرانسې جنوبي سیمې',
        'TG': 'ټوګو',
        'TH': 'تهايلنډ',
        'TJ': 'تاجکستان',
        'TK': 'توکیلو',
        'TL': 'تيمور-ليسټ',
        'TM': 'تورکمنستان',
        'TN': 'تونس',
        'TO': 'تونګا',
        'TR': 'ترکي',
        'TT': 'ټرينيډاډ او ټوباګو',
        'TV': 'توالیو',
        'TW': 'تائيوان',
        'TZ': 'تنزانیا',
        'UA': 'اوکراین',
        'UG': 'یوګانډا',
        'UM': 'د متحده ایالاتو ټاپوګان',
        'US': 'متحده آيالات',
        'UY': 'یوروګوی',
        'UZ': 'اوزبکستان',
        'VA': 'واتیکان ښار',
        'VC': 'سینټ ویسنټینټ او ګرینډینز',
        'VE': 'وینزویلا',
        'VG': 'بریتانوی ویګور ټاپوګان',
        'VI': 'د متحده آيالاتو ورجن ټاپوګان',
        'VN': 'وېتنام',
        'VU': 'واناتو',
        'WF': 'والیس او فوتونا',
        'WS': 'ساماوا',
        'XK': 'کوسوو',
        'YE': 'یمن',
        'YT': 'مايوټ',
        'ZA': 'سویلي افریقا',
        'ZM': 'زیمبیا',
        'ZW': 'زیمبابوی',
      },
      'tr': <String, String>{
        'AC': 'Ascension Adası',
        'AD': 'Andorra',
        'AE': 'Birleşik Arap Emirlikleri',
        'AF': 'Afganistan',
        'AG': 'Antigua ve Barbuda',
        'AI': 'Anguilla',
        'AL': 'Arnavutluk',
        'AM': 'Ermenistan',
        'AO': 'Angola',
        'AQ': 'Antarktika',
        'AR': 'Arjantin',
        'AS': 'Amerikan Samoası',
        'AT': 'Avusturya',
        'AU': 'Avustralya',
        'AW': 'Aruba',
        'AX': 'Åland Adaları',
        'AZ': 'Azerbaycan',
        'BA': 'Bosna-Hersek',
        'BB': 'Barbados',
        'BD': 'Bangladeş',
        'BE': 'Belçika',
        'BF': 'Burkina Faso',
        'BG': 'Bulgaristan',
        'BH': 'Bahreyn',
        'BI': 'Burundi',
        'BJ': 'Benin',
        'BL': 'Saint Barthelemy',
        'BM': 'Bermuda',
        'BN': 'Brunei',
        'BO': 'Bolivya',
        'BQ': 'Karayip Hollandası',
        'BR': 'Brezilya',
        'BS': 'Bahamalar',
        'BT': 'Butan',
        'BV': 'Bouvet Adası',
        'BW': 'Botsvana',
        'BY': 'Belarus',
        'BZ': 'Belize',
        'CA': 'Kanada',
        'CC': 'Cocos (Keeling) Adaları',
        'CD': 'Kongo - Kinşasa',
        'CF': 'Orta Afrika Cumhuriyeti',
        'CG': 'Kongo - Brazavil',
        'CH': 'İsviçre',
        'CI': 'Côte d’Ivoire',
        'CK': 'Cook Adaları',
        'CL': 'Şili',
        'CM': 'Kamerun',
        'CN': 'Çin',
        'CO': 'Kolombiya',
        'CP': 'Clipperton Adası',
        'CQ': 'Sark',
        'CR': 'Kosta Rika',
        'CU': 'Küba',
        'CV': 'Cabo Verde',
        'CW': 'Curaçao',
        'CX': 'Christmas Adası',
        'CY': 'Kıbrıs',
        'CZ': 'Çekya',
        'DE': 'Almanya',
        'DG': 'Diego Garcia',
        'DJ': 'Cibuti',
        'DK': 'Danimarka',
        'DM': 'Dominika',
        'DO': 'Dominik Cumhuriyeti',
        'DZ': 'Cezayir',
        'EA': 'Ceuta ve Melilla',
        'EC': 'Ekvador',
        'EE': 'Estonya',
        'EG': 'Mısır',
        'EH': 'Batı Sahra',
        'ER': 'Eritre',
        'ES': 'İspanya',
        'ET': 'Etiyopya',
        'FI': 'Finlandiya',
        'FJ': 'Fiji',
        'FK': 'Falkland Adaları',
        'FM': 'Mikronezya',
        'FO': 'Faroe Adaları',
        'FR': 'Fransa',
        'GA': 'Gabon',
        'GB': 'Birleşik Krallık',
        'GD': 'Grenada',
        'GE': 'Gürcistan',
        'GF': 'Fransız Guyanası',
        'GG': 'Guernsey',
        'GH': 'Gana',
        'GI': 'Cebelitarık',
        'GL': 'Grönland',
        'GM': 'Gambiya',
        'GN': 'Gine',
        'GP': 'Guadeloupe',
        'GQ': 'Ekvator Ginesi',
        'GR': 'Yunanistan',
        'GS': 'Güney Georgia ve Güney Sandwich Adaları',
        'GT': 'Guatemala',
        'GU': 'Guam',
        'GW': 'Gine-Bissau',
        'GY': 'Guyana',
        'HK': 'Çin Hong Kong ÖİB',
        'HM': 'Heard Adası ve McDonald Adaları',
        'HN': 'Honduras',
        'HR': 'Hırvatistan',
        'HT': 'Haiti',
        'HU': 'Macaristan',
        'IC': 'Kanarya Adaları',
        'ID': 'Endonezya',
        'IE': 'İrlanda',
        'IL': 'İsrail',
        'IM': 'Man Adası',
        'IN': 'Hindistan',
        'IO': 'Britanya Hint Okyanusu Toprakları',
        'IQ': 'Irak',
        'IR': 'İran',
        'IS': 'İzlanda',
        'IT': 'İtalya',
        'JE': 'Jersey',
        'JM': 'Jamaika',
        'JO': 'Ürdün',
        'JP': 'Japonya',
        'KE': 'Kenya',
        'KG': 'Kırgızistan',
        'KH': 'Kamboçya',
        'KI': 'Kiribati',
        'KM': 'Komorlar',
        'KN': 'Saint Kitts ve Nevis',
        'KP': 'Kuzey Kore',
        'KR': 'Güney Kore',
        'KW': 'Kuveyt',
        'KY': 'Cayman Adaları',
        'KZ': 'Kazakistan',
        'LA': 'Laos',
        'LB': 'Lübnan',
        'LC': 'Saint Lucia',
        'LI': 'Liechtenstein',
        'LK': 'Sri Lanka',
        'LR': 'Liberya',
        'LS': 'Lesotho',
        'LT': 'Litvanya',
        'LU': 'Lüksemburg',
        'LV': 'Letonya',
        'LY': 'Libya',
        'MA': 'Fas',
        'MC': 'Monako',
        'MD': 'Moldova',
        'ME': 'Karadağ',
        'MF': 'Saint Martin',
        'MG': 'Madagaskar',
        'MH': 'Marshall Adaları',
        'MK': 'Kuzey Makedonya',
        'ML': 'Mali',
        'MM': 'Myanmar (Burma)',
        'MN': 'Moğolistan',
        'MO': 'Çin Makao ÖİB',
        'MP': 'Kuzey Mariana Adaları',
        'MQ': 'Martinik',
        'MR': 'Moritanya',
        'MS': 'Montserrat',
        'MT': 'Malta',
        'MU': 'Mauritius',
        'MV': 'Maldivler',
        'MW': 'Malavi',
        'MX': 'Meksika',
        'MY': 'Malezya',
        'MZ': 'Mozambik',
        'NA': 'Namibya',
        'NC': 'Yeni Kaledonya',
        'NE': 'Nijer',
        'NF': 'Norfolk Adası',
        'NG': 'Nijerya',
        'NI': 'Nikaragua',
        'NL': 'Hollanda',
        'NO': 'Norveç',
        'NP': 'Nepal',
        'NR': 'Nauru',
        'NU': 'Niue',
        'NZ': 'Yeni Zelanda',
        'OM': 'Umman',
        'PA': 'Panama',
        'PE': 'Peru',
        'PF': 'Fransız Polinezyası',
        'PG': 'Papua Yeni Gine',
        'PH': 'Filipinler',
        'PK': 'Pakistan',
        'PL': 'Polonya',
        'PM': 'Saint Pierre ve Miquelon',
        'PN': 'Pitcairn Adaları',
        'PR': 'Porto Riko',
        'PS': 'Filistin Bölgeleri',
        'PT': 'Portekiz',
        'PW': 'Palau',
        'PY': 'Paraguay',
        'QA': 'Katar',
        'RE': 'Reunion',
        'RO': 'Romanya',
        'RS': 'Sırbistan',
        'RU': 'Rusya',
        'RW': 'Ruanda',
        'SA': 'Suudi Arabistan',
        'SB': 'Solomon Adaları',
        'SC': 'Seyşeller',
        'SD': 'Sudan',
        'SE': 'İsveç',
        'SG': 'Singapur',
        'SH': 'Saint Helena',
        'SI': 'Slovenya',
        'SJ': 'Svalbard ve Jan Mayen',
        'SK': 'Slovakya',
        'SL': 'Sierra Leone',
        'SM': 'San Marino',
        'SN': 'Senegal',
        'SO': 'Somali',
        'SR': 'Surinam',
        'SS': 'Güney Sudan',
        'ST': 'Sao Tome ve Principe',
        'SV': 'El Salvador',
        'SX': 'Sint Maarten',
        'SY': 'Suriye',
        'SZ': 'Esvatini',
        'TA': 'Tristan da Cunha',
        'TC': 'Turks ve Caicos Adaları',
        'TD': 'Çad',
        'TF': 'Fransız Güney Toprakları',
        'TG': 'Togo',
        'TH': 'Tayland',
        'TJ': 'Tacikistan',
        'TK': 'Tokelau',
        'TL': 'Timor-Leste',
        'TM': 'Türkmenistan',
        'TN': 'Tunus',
        'TO': 'Tonga',
        'TR': 'Türkiye',
        'TT': 'Trinidad ve Tobago',
        'TV': 'Tuvalu',
        'TW': 'Tayvan',
        'TZ': 'Tanzanya',
        'UA': 'Ukrayna',
        'UG': 'Uganda',
        'UM': 'ABD Küçük Harici Adaları',
        'US': 'Amerika Birleşik Devletleri',
        'UY': 'Uruguay',
        'UZ': 'Özbekistan',
        'VA': 'Vatikan',
        'VC': 'Saint Vincent ve Grenadinler',
        'VE': 'Venezuela',
        'VG': 'Britanya Virjin Adaları',
        'VI': 'ABD Virjin Adaları',
        'VN': 'Vietnam',
        'VU': 'Vanuatu',
        'WF': 'Wallis ve Futuna',
        'WS': 'Samoa',
        'XK': 'Kosova',
        'YE': 'Yemen',
        'YT': 'Mayotte',
        'ZA': 'Güney Afrika',
        'ZM': 'Zambiya',
        'ZW': 'Zimbabve',
      },
      'ur': <String, String>{
        'AC': 'اسینشن آئلینڈ',
        'AD': 'انڈورا',
        'AE': 'متحدہ عرب امارات',
        'AF': 'افغانستان',
        'AG': 'انٹیگوا اور باربودا',
        'AI': 'انگوئیلا',
        'AL': 'البانیہ',
        'AM': 'آرمینیا',
        'AO': 'انگولا',
        'AQ': 'انٹارکٹیکا',
        'AR': 'ارجنٹینا',
        'AS': 'امریکی ساموآ',
        'AT': 'آسٹریا',
        'AU': 'آسٹریلیا',
        'AW': 'اروبا',
        'AX': 'آلینڈ آئلینڈز',
        'AZ': 'آذربائیجان',
        'BA': 'بوسنیا اور ہرزیگووینا',
        'BB': 'بارباڈوس',
        'BD': 'بنگلہ دیش',
        'BE': 'بیلجیم',
        'BF': 'برکینا فاسو',
        'BG': 'بلغاریہ',
        'BH': 'بحرین',
        'BI': 'برونڈی',
        'BJ': 'بینن',
        'BL': 'سینٹ برتھلیمی',
        'BM': 'برمودا',
        'BN': 'برونائی',
        'BO': 'بولیویا',
        'BQ': 'کریبیائی نیدرلینڈز',
        'BR': 'برازیل',
        'BS': 'بہاماس',
        'BT': 'بھوٹان',
        'BV': 'بؤویٹ آئلینڈ',
        'BW': 'بوتسوانا',
        'BY': 'بیلاروس',
        'BZ': 'بیلائز',
        'CA': 'کینیڈا',
        'CC': 'کوکوس (کیلنگ) جزائر',
        'CD': 'کانگو - کنشاسا',
        'CF': 'وسط افریقی جمہوریہ',
        'CG': 'کانگو - برازاویلے',
        'CH': 'سوئٹزر لینڈ',
        'CI': 'کوٹ ڈی آئیوری',
        'CK': 'کک آئلینڈز',
        'CL': 'چلی',
        'CM': 'کیمرون',
        'CN': 'چین',
        'CO': 'کولمبیا',
        'CP': 'کلپرٹن آئلینڈ',
        'CQ': 'سارک',
        'CR': 'کوسٹا ریکا',
        'CU': 'کیوبا',
        'CV': 'کیپ ورڈی',
        'CW': 'کیوراکاؤ',
        'CX': 'جزیرہ کرسمس',
        'CY': 'قبرص',
        'CZ': 'چیکیا',
        'DE': 'جرمنی',
        'DG': 'ڈائجو گارسیا',
        'DJ': 'جبوتی',
        'DK': 'ڈنمارک',
        'DM': 'ڈومنیکا',
        'DO': 'جمہوریہ ڈومينيکن',
        'DZ': 'الجیریا',
        'EA': 'سیئوٹا اور میلیلا',
        'EC': 'ایکواڈور',
        'EE': 'اسٹونیا',
        'EG': 'مصر',
        'EH': 'مغربی صحارا',
        'ER': 'اریٹیریا',
        'ES': 'ہسپانیہ',
        'ET': 'ایتھوپیا',
        'FI': 'فن لینڈ',
        'FJ': 'فجی',
        'FK': 'فاکلینڈ جزائر',
        'FM': 'مائکرونیشیا',
        'FO': 'جزائر فارو',
        'FR': 'فرانس',
        'GA': 'گیبون',
        'GB': 'سلطنت متحدہ',
        'GD': 'گریناڈا',
        'GE': 'جارجیا',
        'GF': 'فرینچ گیانا',
        'GG': 'گوئرنسی',
        'GH': 'گھانا',
        'GI': 'جبل الطارق',
        'GL': 'گرین لینڈ',
        'GM': 'گیمبیا',
        'GN': 'گنی',
        'GP': 'گواڈیلوپ',
        'GQ': 'استوائی گیانا',
        'GR': 'یونان',
        'GS': 'جنوبی جارجیا اور جنوبی سینڈوچ جزائر',
        'GT': 'گواٹے مالا',
        'GU': 'گوام',
        'GW': 'گنی بساؤ',
        'GY': 'گیانا',
        'HK': 'ہانگ کانگ SAR چین',
        'HM': 'ہیرڈ جزیرہ و میکڈولینڈ جزائر',
        'HN': 'ہونڈاروس',
        'HR': 'کروشیا',
        'HT': 'ہیٹی',
        'HU': 'ہنگری',
        'IC': 'کینری آئلینڈز',
        'ID': 'انڈونیشیا',
        'IE': 'آئرلینڈ',
        'IL': 'اسرائیل',
        'IM': 'آئل آف مین',
        'IN': 'بھارت',
        'IO': 'برطانوی بحر ہند کا علاقہ',
        'IQ': 'عراق',
        'IR': 'ایران',
        'IS': 'آئس لینڈ',
        'IT': 'اٹلی',
        'JE': 'جرسی',
        'JM': 'جمائیکا',
        'JO': 'اردن',
        'JP': 'جاپان',
        'KE': 'کینیا',
        'KG': 'کرغزستان',
        'KH': 'کمبوڈیا',
        'KI': 'کریباتی',
        'KM': 'کوموروس',
        'KN': 'سینٹ کٹس اور نیویس',
        'KP': 'شمالی کوریا',
        'KR': 'جنوبی کوریا',
        'KW': 'کویت',
        'KY': 'کیمین آئلینڈز',
        'KZ': 'قزاخستان',
        'LA': 'لاؤس',
        'LB': 'لبنان',
        'LC': 'سینٹ لوسیا',
        'LI': 'لیشٹنسٹائن',
        'LK': 'سری لنکا',
        'LR': 'لائبیریا',
        'LS': 'لیسوتھو',
        'LT': 'لیتھونیا',
        'LU': 'لکسمبرگ',
        'LV': 'لٹویا',
        'LY': 'لیبیا',
        'MA': 'مراکش',
        'MC': 'موناکو',
        'MD': 'مالدووا',
        'ME': 'مونٹے نیگرو',
        'MF': 'سینٹ مارٹن',
        'MG': 'مڈغاسکر',
        'MH': 'مارشل آئلینڈز',
        'MK': 'شمالی مقدونیہ',
        'ML': 'مالی',
        'MM': 'میانمار (برما)',
        'MN': 'منگولیا',
        'MO': 'مکاؤ SAR چین',
        'MP': 'شمالی ماریانا آئلینڈز',
        'MQ': 'مارٹینک',
        'MR': 'موریطانیہ',
        'MS': 'مونٹسیراٹ',
        'MT': 'مالٹا',
        'MU': 'ماریشس',
        'MV': 'مالدیپ',
        'MW': 'ملاوی',
        'MX': 'میکسیکو',
        'MY': 'ملائشیا',
        'MZ': 'موزمبیق',
        'NA': 'نامیبیا',
        'NC': 'نیو کلیڈونیا',
        'NE': 'نائجر',
        'NF': 'نارفوک آئلینڈ',
        'NG': 'نائجیریا',
        'NI': 'نکاراگووا',
        'NL': 'نیدر لینڈز',
        'NO': 'ناروے',
        'NP': 'نیپال',
        'NR': 'نؤرو',
        'NU': 'نیئو',
        'NZ': 'نیوزی لینڈ',
        'OM': 'عمان',
        'PA': 'پانامہ',
        'PE': 'پیرو',
        'PF': 'فرانسیسی پولینیشیا',
        'PG': 'پاپوآ نیو گنی',
        'PH': 'فلپائن',
        'PK': 'پاکستان',
        'PL': 'پولینڈ',
        'PM': 'سینٹ پیئر اور میکلیئون',
        'PN': 'پٹکائرن جزائر',
        'PR': 'پیورٹو ریکو',
        'PS': 'فلسطینی خطے',
        'PT': 'پرتگال',
        'PW': 'پلاؤ',
        'PY': 'پیراگوئے',
        'QA': 'قطر',
        'RE': 'ری یونین',
        'RO': 'رومانیہ',
        'RS': 'سربیا',
        'RU': 'روس',
        'RW': 'روانڈا',
        'SA': 'سعودی عرب',
        'SB': 'سولومن آئلینڈز',
        'SC': 'سشلیز',
        'SD': 'سوڈان',
        'SE': 'سویڈن',
        'SG': 'سنگاپور',
        'SH': 'سینٹ ہیلینا',
        'SI': 'سلووینیا',
        'SJ': 'سوالبرڈ اور جان ماین',
        'SK': 'سلوواکیہ',
        'SL': 'سیرالیون',
        'SM': 'سان مارینو',
        'SN': 'سینیگل',
        'SO': 'صومالیہ',
        'SR': 'سورینام',
        'SS': 'جنوبی سوڈان',
        'ST': 'ساؤ ٹومے اور پرنسپے',
        'SV': 'ال سلواڈور',
        'SX': 'سنٹ مارٹن',
        'SY': 'شام',
        'SZ': 'سواتنی',
        'TA': 'ٹرسٹن ڈا کیونہا',
        'TC': 'ٹرکس اور کیکوس جزائر',
        'TD': 'چاڈ',
        'TF': 'فرانسیسی جنوبی خطے',
        'TG': 'ٹوگو',
        'TH': 'تھائی لینڈ',
        'TJ': 'تاجکستان',
        'TK': 'ٹوکیلاؤ',
        'TL': 'تیمور لیسٹ',
        'TM': 'ترکمانستان',
        'TN': 'تونس',
        'TO': 'ٹونگا',
        'TR': 'ترکیہ',
        'TT': 'ترینیداد اور ٹوباگو',
        'TV': 'ٹووالو',
        'TW': 'تائیوان',
        'TZ': 'تنزانیہ',
        'UA': 'یوکرین',
        'UG': 'یوگنڈا',
        'UM': 'امریکہ سے باہر کے چھوٹے جزائز',
        'US': 'ریاست ہائے متحدہ امریکہ',
        'UY': 'یوروگوئے',
        'UZ': 'ازبکستان',
        'VA': 'ویٹیکن سٹی',
        'VC': 'سینٹ ونسنٹ اور گرینیڈائنز',
        'VE': 'وینزوئیلا',
        'VG': 'برٹش ورجن آئلینڈز',
        'VI': 'امریکی ورجن آئلینڈز',
        'VN': 'ویتنام',
        'VU': 'وینوآٹو',
        'WF': 'ویلیز اور فیوٹیونا',
        'WS': 'ساموآ',
        'XK': 'کوسووو',
        'YE': 'یمن',
        'YT': 'مایوٹ',
        'ZA': 'جنوبی افریقہ',
        'ZM': 'زامبیا',
        'ZW': 'زمبابوے',
      },
    };
