import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings)!;

  static const List<Locale> supportedLocales = <Locale>[
    Locale('de'),
    Locale('en'),
    Locale('ar'),
    Locale('ur'),
    Locale('ps'),
  ];

  static const Map<String, Map<String, String>> _values = {
    'de': {
      'appName': 'Salaty',
      'tagline': 'Weniger Ablenkung. Mehr Salah.',
      'getStarted': "Los geht's",
      'home': 'Home',
      'tracker': 'Tracker',
      'qibla': 'Qibla',
      'settings': 'Einstellungen',
      'nextPrayer': 'Nächstes Gebet',
      'today': 'Heute',
      'prayed': 'Gebetet',
      'snoozed': 'Verschoben',
      'skipped': 'Übersprungen',
      'missed': 'Nicht bestätigt',
      'upcoming': 'Bevorstehend',
      'active': 'Aktiv',
      'pending': 'Prayer Focus',
      'refresh': 'Aktualisieren',
      'location': 'Standort',
      'useLocation': 'Standort verwenden',
      'chooseCity': 'Stadt auswählen',
      'city': 'Stadt',
      'country': 'Land',
      'continue': 'Weiter',
      'back': 'Zurück',
      'prayerTimes': 'Gebetszeiten',
      'timesQuestion':
          'Stimmen diese Zeiten ungefähr mit deiner Moschee überein?',
      'yes': 'Ja',
      'adjust': 'Anpassen',
      'graceQuestion': 'Wann sollen wir dich stärker erinnern?',
      'minutesAfter': 'Minuten nach Gebetsbeginn',
      'distractions': 'Welche Apps lenken dich häufig ab?',
      'focusExplain': 'Prayer Focus hilft dir, Ablenkungen für ein paar Minuten auszuschalten. Du behältst immer die Kontrolle.',
      'enableFocus': 'Prayer Focus aktivieren',
      'permissions': 'Berechtigungen',
      'permissionExplain': 'Wir fragen Berechtigungen erst dann an, wenn sie für eine Funktion gebraucht werden.',
      'finish': 'Fertig',
      'confirmPrayer': 'Wallah, ich habe gebetet',
      'snooze': '20 Minuten später erinnern',
      'snoozeIn': 'In {minutes} Minuten erinnern',
      'skipToday': 'Heute überspringen',
      'skipConfirmTitle': 'Erinnerung beenden?',
      'skipConfirmBody':
          'Möchtest du die Erinnerung für dieses Gebet wirklich beenden?',
      'noPrayLater': 'Nein, ich bete noch',
      'yesEnd': 'Ja, Erinnerung beenden',
      'emergencyUnlock': 'Notfall – Focus Mode beenden',
      'emergencyBody': 'Prayer Focus wird sofort beendet. Das Gebet wird dabei nicht als übersprungen markiert.',
      'focusTitle': 'Zeit für {prayer}',
      'focusBody': 'Du wolltest dir Zeit für dein Gebet nehmen. Lege dein Handy für ein paar Minuten weg und bete.',
      'accepted': 'Alhamdulillah 🤍',
      'week': 'Diese Woche',
      'month': 'Monat',
      'confirmedPrayers': 'Bestätigte Gebete',
      'calculationMethod': 'Berechnungsmethode',
      'madhhab': 'Asr-Berechnung',
      'standard': 'Standard',
      'hanafi': 'Hanafi',
      'highLatitude': 'Hohe Breitengrade',
      'gracePeriod': 'Grace Period',
      'snoozeDuration': 'Snooze-Dauer',
      'confirmationText': 'Bestätigungstext',
      'focusMode': 'Prayer Focus',
      'softReminder': 'Sanfte Erinnerung nach Überspringen',
      'theme': 'Darstellung',
      'system': 'System',
      'light': 'Hell',
      'dark': 'Dunkel',
      'language': 'Sprache',
      'german': 'Deutsch',
      'english': 'Englisch',
      'arabic': 'Arabisch',
      'notificationPermission': 'Benachrichtigungen erlauben',
      'exactAlarmPermission': 'Präzise Erinnerungen erlauben',
      'focusAuthorization': 'Focus-Berechtigung einrichten',
      'selectApps': 'Ablenkende Apps auswählen',
      'individualAppsOnly': 'Wähle nur einzelne ablenkende Apps aus. Ganze Kategorien werden aus Sicherheitsgründen nicht blockiert. Lass Salaty und wichtige Apps wie Telefon, Karten oder medizinische Apps ungewählt.',
      'focusFallback': 'Auf diesem Gerät ist systemweites App-Shielding nicht verfügbar. Der sichere In-App-Focus bleibt aktiv.',
      'qiblaDirection': 'Qibla-Richtung',
      'calibrate': 'Bewege dein Handy in Form einer Acht, wenn der Kompass ungenau wirkt.',
      'noCompass': 'Kein Kompass-Sensor verfügbar. Die Qibla-Richtung wird in Grad angezeigt.',
      'needLocation': 'Bitte zuerst einen Standort festlegen.',
      'offlineCache': 'Offline-Cache wird verwendet.',
      'retry': 'Erneut versuchen',
      'noData': 'Für heute sind keine zuverlässigen Gebetszeiten gespeichert.',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'manualAdjustments': 'Minutenkorrekturen',
      'maxSnoozes': 'Maximale Snoozes',
      'unlimited': 'Unbegrenzt',
      'genericError': 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
      'locationError': 'Der Standort konnte nicht bestimmt werden. Du kannst stattdessen eine Stadt auswählen.',
      'networkError': 'Die Gebetszeiten konnten gerade nicht geladen werden. Gespeicherte Daten werden verwendet, wenn sie verfügbar sind.',
      'prayerDataError': 'Die Gebetszeiten konnten nicht zuverlässig verarbeitet werden. Bitte versuche es erneut.',
      'snoozeUnavailable': 'Dieses Gebet kann nicht weiter verschoben werden.',
      'prayerFirst': 'Gebet zuerst, Handy danach.',
      'heading': 'Ausrichtung',
      'minutesValue': '{value} Min.',
    },
    'en': {
      'appName': 'Salaty',
      'tagline': 'Less distraction. More Salah.',
      'getStarted': 'Get started',
      'home': 'Home',
      'tracker': 'Tracker',
      'qibla': 'Qibla',
      'settings': 'Settings',
      'nextPrayer': 'Next prayer',
      'today': 'Today',
      'prayed': 'Prayed',
      'snoozed': 'Snoozed',
      'skipped': 'Skipped',
      'missed': 'Not confirmed',
      'upcoming': 'Upcoming',
      'active': 'Active',
      'pending': 'Prayer Focus',
      'refresh': 'Refresh',
      'location': 'Location',
      'useLocation': 'Use my location',
      'chooseCity': 'Choose city',
      'city': 'City',
      'country': 'Country',
      'continue': 'Continue',
      'back': 'Back',
      'prayerTimes': 'Prayer times',
      'timesQuestion': 'Do these times roughly match your local mosque?',
      'yes': 'Yes',
      'adjust': 'Adjust',
      'graceQuestion': 'When should we remind you more strongly?',
      'minutesAfter': 'minutes after prayer begins',
      'distractions': 'Which apps often distract you?',
      'focusExplain': 'Prayer Focus helps you reduce distractions for a few minutes. You always remain in control.',
      'enableFocus': 'Enable Prayer Focus',
      'permissions': 'Permissions',
      'permissionExplain':
          'We only request permissions when a feature actually needs them.',
      'finish': 'Finish',
      'confirmPrayer': 'I have prayed',
      'snooze': 'Remind me in 20 minutes',
      'snoozeIn': 'Remind me in {minutes} minutes',
      'skipToday': 'Skip today',
      'skipConfirmTitle': 'End reminder?',
      'skipConfirmBody': 'Do you really want to end reminders for this prayer?',
      'noPrayLater': 'No, I will pray',
      'yesEnd': 'Yes, end reminder',
      'emergencyUnlock': 'Emergency – end Focus Mode',
      'emergencyBody': 'Prayer Focus ends immediately. The prayer will not be marked as skipped.',
      'focusTitle': 'Time for {prayer}',
      'focusBody': 'You wanted to make time for prayer. Put your phone down for a few minutes and pray.',
      'accepted': 'Alhamdulillah 🤍',
      'week': 'This week',
      'month': 'Month',
      'confirmedPrayers': 'Confirmed prayers',
      'calculationMethod': 'Calculation method',
      'madhhab': 'Asr calculation',
      'standard': 'Standard',
      'hanafi': 'Hanafi',
      'highLatitude': 'High latitude rule',
      'gracePeriod': 'Grace period',
      'snoozeDuration': 'Snooze duration',
      'confirmationText': 'Confirmation text',
      'focusMode': 'Prayer Focus',
      'softReminder': 'Gentle reminder after skip',
      'theme': 'Appearance',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'german': 'German',
      'english': 'English',
      'arabic': 'Arabic',
      'notificationPermission': 'Allow notifications',
      'exactAlarmPermission': 'Allow precise reminders',
      'focusAuthorization': 'Set up Focus permission',
      'selectApps': 'Select distracting apps',
      'individualAppsOnly': 'Select only individual distracting apps. Whole categories are not blocked for safety. Leave Salaty and essential apps such as Phone, Maps or medical apps unselected.',
      'focusFallback': 'System-wide app shielding is not available on this device. Safe in-app Focus remains active.',
      'qiblaDirection': 'Qibla direction',
      'calibrate':
          'Move your phone in a figure eight if the compass seems inaccurate.',
      'noCompass':
          'No compass sensor is available. Qibla is still shown in degrees.',
      'needLocation': 'Please set a location first.',
      'offlineCache': 'Using offline cache.',
      'retry': 'Try again',
      'noData': 'No reliable prayer times are stored for today.',
      'save': 'Save',
      'cancel': 'Cancel',
      'manualAdjustments': 'Minute adjustments',
      'maxSnoozes': 'Maximum snoozes',
      'unlimited': 'Unlimited',
      'genericError': 'Something went wrong. Please try again.',
      'locationError': 'Your location could not be determined. You can choose a city instead.',
      'networkError': 'Prayer times could not be loaded right now. Cached data will be used when available.',
      'prayerDataError':
          'Prayer times could not be processed reliably. Please try again.',
      'snoozeUnavailable': 'This prayer cannot be snoozed any further.',
      'prayerFirst': 'Prayer first, phone second.',
      'heading': 'Heading',
      'minutesValue': '{value} min',
    },
    'ar': {
      'appName': 'صلاتي',
      'tagline': 'تشتيت أقل. صلاة أكثر.',
      'getStarted': 'ابدأ',
      'home': 'الرئيسية',
      'tracker': 'المتابعة',
      'qibla': 'القبلة',
      'settings': 'الإعدادات',
      'nextPrayer': 'الصلاة القادمة',
      'today': 'اليوم',
      'prayed': 'تمت الصلاة',
      'snoozed': 'مؤجل',
      'skipped': 'تم الإنهاء',
      'missed': 'غير مؤكد',
      'upcoming': 'قادمة',
      'active': 'حان وقتها',
      'pending': 'تركيز الصلاة',
      'refresh': 'تحديث',
      'location': 'الموقع',
      'useLocation': 'استخدم موقعي',
      'chooseCity': 'اختر مدينة',
      'city': 'المدينة',
      'country': 'الدولة',
      'continue': 'متابعة',
      'back': 'رجوع',
      'prayerTimes': 'مواقيت الصلاة',
      'timesQuestion': 'هل تتوافق هذه الأوقات تقريبًا مع مسجدك؟',
      'yes': 'نعم',
      'adjust': 'تعديل',
      'graceQuestion': 'متى تريد تذكيرًا أقوى؟',
      'minutesAfter': 'دقيقة بعد دخول وقت الصلاة',
      'distractions': 'ما التطبيقات التي تشتتك غالبًا؟',
      'focusExplain': 'يساعدك وضع تركيز الصلاة على تقليل المشتتات لبضع دقائق، وتبقى أنت المتحكم دائمًا.',
      'enableFocus': 'تفعيل تركيز الصلاة',
      'permissions': 'الأذونات',
      'permissionExplain': 'نطلب الأذونات فقط عندما تحتاجها ميزة معينة.',
      'finish': 'إنهاء',
      'confirmPrayer': 'لقد صليت',
      'snooze': 'ذكرني بعد 20 دقيقة',
      'snoozeIn': 'ذكّرني بعد {minutes} دقيقة',
      'skipToday': 'إنهاء تذكير اليوم',
      'skipConfirmTitle': 'إنهاء التذكير؟',
      'skipConfirmBody': 'هل تريد فعلًا إنهاء التذكيرات لهذه الصلاة؟',
      'noPrayLater': 'لا، سأصلي',
      'yesEnd': 'نعم، أنهِ التذكير',
      'emergencyUnlock': 'طوارئ – إنهاء وضع التركيز',
      'emergencyBody':
          'سيتم إنهاء وضع التركيز فورًا، ولن يتم تسجيل الصلاة على أنها متخطاة.',
      'focusTitle': 'حان وقت {prayer}',
      'focusBody': 'أردت أن تخصص وقتًا للصلاة. اترك الهاتف لبضع دقائق وصلِّ.',
      'accepted': 'الحمد لله 🤍',
      'week': 'هذا الأسبوع',
      'month': 'الشهر',
      'confirmedPrayers': 'الصلوات المؤكدة',
      'calculationMethod': 'طريقة الحساب',
      'madhhab': 'حساب العصر',
      'standard': 'قياسي',
      'hanafi': 'حنفي',
      'highLatitude': 'قاعدة خطوط العرض العليا',
      'gracePeriod': 'فترة السماح',
      'snoozeDuration': 'مدة التأجيل',
      'confirmationText': 'نص التأكيد',
      'focusMode': 'تركيز الصلاة',
      'softReminder': 'تذكير لطيف بعد الإنهاء',
      'theme': 'المظهر',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'language': 'اللغة',
      'german': 'الألمانية',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'notificationPermission': 'السماح بالإشعارات',
      'exactAlarmPermission': 'السماح بالتذكيرات الدقيقة',
      'focusAuthorization': 'إعداد إذن التركيز',
      'selectApps': 'اختر التطبيقات المشتتة',
      'individualAppsOnly': 'اختر تطبيقات مشتتة منفردة فقط. لا يتم حجب فئات كاملة لأسباب تتعلق بالسلامة. اترك تطبيق صلاتي والتطبيقات الأساسية مثل الهاتف والخرائط والتطبيقات الطبية دون تحديد.',
      'focusFallback': 'حجب التطبيقات على مستوى النظام غير متاح على هذا الجهاز. يبقى وضع التركيز داخل التطبيق فعالًا.',
      'qiblaDirection': 'اتجاه القبلة',
      'calibrate': 'حرّك هاتفك على شكل رقم ثمانية إذا بدا البوصلة غير دقيقة.',
      'noCompass': 'لا يوجد مستشعر بوصلة. سيظهر اتجاه القبلة بالدرجات.',
      'needLocation': 'حدد موقعًا أولًا.',
      'offlineCache': 'يتم استخدام البيانات المحفوظة دون اتصال.',
      'retry': 'حاول مجددًا',
      'noData': 'لا توجد مواقيت صلاة موثوقة محفوظة لليوم.',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'manualAdjustments': 'تعديلات الدقائق',
      'maxSnoozes': 'أقصى عدد للتأجيل',
      'unlimited': 'بلا حد',
      'genericError': 'حدث خطأ ما. حاول مرة أخرى.',
      'locationError': 'تعذر تحديد موقعك. يمكنك اختيار مدينة بدلًا من ذلك.',
      'networkError': 'تعذر تحميل مواقيت الصلاة الآن. سيتم استخدام البيانات المحفوظة إن كانت متاحة.',
      'prayerDataError': 'تعذر معالجة مواقيت الصلاة بشكل موثوق. حاول مرة أخرى.',
      'snoozeUnavailable': 'لا يمكن تأجيل تذكير هذه الصلاة أكثر.',
      'prayerFirst': 'الصلاة أولًا، ثم الهاتف.',
      'heading': 'اتجاه الهاتف',
      'minutesValue': '{value} دقيقة',
    },
    'ur': {
      'appName': 'صلاتی',
      'tagline': 'کم توجہ بھٹکنا۔ زیادہ نماز۔',
      'getStarted': 'شروع کریں',
      'home': 'ہوم',
      'tracker': 'ریکارڈ',
      'qibla': 'قبلہ',
      'settings': 'ترتیبات',
      'nextPrayer': 'اگلی نماز',
      'today': 'آج',
      'prayed': 'نماز پڑھی',
      'snoozed': 'موخر',
      'skipped': 'چھوڑ دیا',
      'missed': 'تصدیق نہیں ہوئی',
      'upcoming': 'آنے والی',
      'active': 'فعال',
      'pending': 'نماز توجہ',
      'refresh': 'تازہ کریں',
      'location': 'مقام',
      'useLocation': 'میرا مقام استعمال کریں',
      'chooseCity': 'شہر منتخب کریں',
      'city': 'شہر',
      'country': 'ملک',
      'continue': 'جاری رکھیں',
      'back': 'واپس',
      'prayerTimes': 'نماز کے اوقات',
      'timesQuestion': 'کیا یہ اوقات تقریباً آپ کی مقامی مسجد سے ملتے ہیں؟',
      'yes': 'ہاں',
      'adjust': 'تبدیل کریں',
      'graceQuestion': 'ہم آپ کو زیادہ مضبوطی سے کب یاد دلائیں؟',
      'minutesAfter': 'نماز شروع ہونے کے بعد منٹ',
      'distractions': 'کون سی ایپس اکثر آپ کی توجہ بھٹکاتی ہیں؟',
      'focusExplain': 'نماز توجہ چند منٹ کے لیے توجہ بھٹکنے سے بچاتی ہے۔ اختیار ہمیشہ آپ کے پاس ہے۔',
      'enableFocus': 'نماز توجہ فعال کریں',
      'permissions': 'اجازتیں',
      'permissionExplain':
          'ہم صرف اس وقت اجازت مانگتے ہیں جب کسی خصوصیت کو اس کی ضرورت ہو۔',
      'finish': 'مکمل',
      'confirmPrayer': 'میں نے نماز پڑھی ہے',
      'snooze': '20 منٹ بعد یاد دلائیں',
      'snoozeIn': '{minutes} منٹ بعد یاد دلائیں',
      'skipToday': 'آج چھوڑ دیں',
      'skipConfirmTitle': 'یاد دہانی بند کریں؟',
      'skipConfirmBody':
          'کیا آپ واقعی اس نماز کی یاد دہانیاں بند کرنا چاہتے ہیں؟',
      'noPrayLater': 'نہیں، میں نماز پڑھوں گا',
      'yesEnd': 'ہاں، یاد دہانی بند کریں',
      'emergencyUnlock': 'ایمرجنسی – توجہ موڈ بند کریں',
      'emergencyBody':
          'نماز توجہ فوراً ختم ہو جائے گی۔ نماز کو چھوڑا ہوا نشان نہیں لگے گا۔',
      'focusTitle': '{prayer} کا وقت',
      'focusBody': 'آپ نے نماز کے لیے وقت نکالنا چاہا تھا۔ فون چند منٹ کے لیے رکھ دیں اور نماز پڑھیں۔',
      'accepted': 'الحمدللہ 🤍',
      'week': 'اس ہفتے',
      'month': 'مہینہ',
      'confirmedPrayers': 'تصدیق شدہ نمازیں',
      'calculationMethod': 'حساب کا طریقہ',
      'madhhab': 'عصر کا حساب',
      'standard': 'معیاری',
      'hanafi': 'حنفی',
      'highLatitude': 'بلند عرض البلد کا اصول',
      'gracePeriod': 'مہلت کی مدت',
      'snoozeDuration': 'موخر کرنے کی مدت',
      'confirmationText': 'تصدیقی متن',
      'focusMode': 'نماز توجہ',
      'softReminder': 'چھوڑنے کے بعد نرم یاد دہانی',
      'theme': 'ظاہری شکل',
      'system': 'سسٹم',
      'light': 'روشن',
      'dark': 'تاریک',
      'language': 'زبان',
      'german': 'جرمن',
      'english': 'انگریزی',
      'arabic': 'عربی',
      'urdu': 'اردو',
      'pashto': 'پشتو',
      'notificationPermission': 'اطلاعات کی اجازت دیں',
      'exactAlarmPermission': 'درست یاددہانیوں کی اجازت دیں',
      'focusAuthorization': 'توجہ کی اجازت ترتیب دیں',
      'selectApps': 'توجہ بھٹکانے والی ایپس منتخب کریں',
      'individualAppsOnly': 'صرف انفرادی توجہ بھٹکانے والی ایپس منتخب کریں۔ حفاظت کے لیے پوری اقسام بلاک نہیں کی جاتیں۔ صلاتی اور فون، نقشے یا طبی ایپس جیسی ضروری ایپس کو منتخب نہ کریں۔',
      'focusFallback': 'اس آلے پر سسٹم بھر میں ایپس کو روکنا دستیاب نہیں۔ محفوظ اندرونِ ایپ توجہ فعال رہتی ہے۔',
      'qiblaDirection': 'قبلہ کی سمت',
      'calibrate': 'اگر قطب نما غلط لگے تو فون کو آٹھ کی شکل میں حرکت دیں۔',
      'noCompass': 'قطب نما سینسر دستیاب نہیں۔ قبلہ کی سمت پھر بھی درجوں میں دکھائی جاتی ہے۔',
      'needLocation': 'پہلے ایک مقام مقرر کریں۔',
      'offlineCache': 'آف لائن محفوظ ڈیٹا استعمال ہو رہا ہے۔',
      'retry': 'دوبارہ کوشش کریں',
      'noData': 'آج کے لیے نماز کے قابلِ اعتماد اوقات محفوظ نہیں ہیں۔',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ',
      'manualAdjustments': 'منٹ کی تبدیلیاں',
      'maxSnoozes': 'زیادہ سے زیادہ موخر کرنا',
      'unlimited': 'لامحدود',
      'genericError': 'کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔',
      'locationError':
          'آپ کا مقام معلوم نہیں ہو سکا۔ آپ اس کے بجائے شہر منتخب کر سکتے ہیں۔',
      'networkError': 'نماز کے اوقات ابھی لوڈ نہیں ہو سکے۔ دستیاب ہونے پر محفوظ ڈیٹا استعمال ہوگا۔',
      'prayerDataError': 'نماز کے اوقات قابل اعتماد طور پر پراسیس نہیں ہو سکے۔ براہ کرم دوبارہ کوشش کریں۔',
      'snoozeUnavailable': 'اس نماز کو مزید موخر نہیں کیا جا سکتا۔',
      'prayerFirst': 'پہلے نماز، پھر فون۔',
      'heading': 'سمت',
      'minutesValue': '{value} منٹ',
    },
    'ps': {
      'appName': 'صلاتي',
      'tagline': 'لږ ګډوډي. ډېره لمونځ.',
      'getStarted': 'پیل کړئ',
      'home': 'کور',
      'tracker': 'څارونکی',
      'qibla': 'قبله',
      'settings': 'امستنې',
      'nextPrayer': 'راتلونکی لمونځ',
      'today': 'نن',
      'prayed': 'لمونځ وشو',
      'snoozed': 'ځنډول شوی',
      'skipped': 'تېر شوی',
      'missed': 'تایید نه شو',
      'upcoming': 'راتلونکی',
      'active': 'فعال',
      'pending': 'د لمانځه تمرکز',
      'refresh': 'تازه کړئ',
      'location': 'ځای',
      'useLocation': 'زما ځای وکاروئ',
      'chooseCity': 'ښار وټاکئ',
      'city': 'ښار',
      'country': 'هېواد',
      'continue': 'دوام ورکړئ',
      'back': 'بېرته',
      'prayerTimes': 'د لمانځه وختونه',
      'timesQuestion': 'ایا دا وختونه نږدې ستاسو له جومات سره سمون لري؟',
      'yes': 'هو',
      'adjust': 'سمول',
      'graceQuestion': 'کله مو په ډېر ټینګار یاد کړو؟',
      'minutesAfter': 'د لمانځه له پیله وروسته دقیقې',
      'distractions': 'کوم اپلیکیشنونه مو ډېر پام اړوي؟',
      'focusExplain': 'د لمانځه تمرکز له څو دقیقو لپاره ګډوډي کموي. کنټرول تل ستاسو په لاس کې دی.',
      'enableFocus': 'د لمانځه تمرکز فعال کړئ',
      'permissions': 'اجازې',
      'permissionExplain':
          'موږ یوازې هغه وخت اجازه غواړو چې کومه ځانګړنه ورته اړتیا ولري.',
      'finish': 'پای',
      'confirmPrayer': 'ما لمونځ کړی دی',
      'snooze': 'په ۲۰ دقیقو کې مې یاد کړئ',
      'snoozeIn': 'په {minutes} دقیقو کې مې یاد کړئ',
      'skipToday': 'نن پرېږدئ',
      'skipConfirmTitle': 'یادونه پای ته ورسوئ؟',
      'skipConfirmBody': 'ایا رښتیا غواړئ د دې لمانځه یادونې پای ته ورسوئ؟',
      'noPrayLater': 'نه، لمونځ به وکړم',
      'yesEnd': 'هو، یادونه پای ته ورسوئ',
      'emergencyUnlock': 'بیړنی – د تمرکز حالت بند کړئ',
      'emergencyBody':
          'د لمانځه تمرکز سمدستي ختمېږي. لمونځ به پرېښودل شوی ونه ګڼل شي.',
      'focusTitle': 'د {prayer} وخت',
      'focusBody': 'تاسو غوښتل لمانځه ته وخت ځانګړی کړئ. فون د څو دقیقو لپاره کېږدئ او لمونځ وکړئ.',
      'accepted': 'الحمدلله 🤍',
      'week': 'دا اونۍ',
      'month': 'میاشت',
      'confirmedPrayers': 'تایید شوي لمونځونه',
      'calculationMethod': 'د محاسبې طریقه',
      'madhhab': 'د مازدیګر محاسبه',
      'standard': 'معیاري',
      'hanafi': 'حنفي',
      'highLatitude': 'د لوړې عرض البلد قاعده',
      'gracePeriod': 'د ځنډ موده',
      'snoozeDuration': 'د ځنډولو موده',
      'confirmationText': 'د تایید متن',
      'focusMode': 'د لمانځه تمرکز',
      'softReminder': 'له پرېښودو وروسته نرمه یادونه',
      'theme': 'بڼه',
      'system': 'سیستم',
      'light': 'روښانه',
      'dark': 'تیاره',
      'language': 'ژبه',
      'german': 'جرمني',
      'english': 'انګلیسي',
      'arabic': 'عربي',
      'urdu': 'اردو',
      'pashto': 'پښتو',
      'notificationPermission': 'خبرتیاوو ته اجازه ورکړئ',
      'exactAlarmPermission': 'دقیقو یادونو ته اجازه ورکړئ',
      'focusAuthorization': 'د تمرکز اجازه برابره کړئ',
      'selectApps': 'ګډوډوونکي اپلیکیشنونه وټاکئ',
      'individualAppsOnly': 'یوازې انفرادي ګډوډوونکي اپلیکیشنونه وټاکئ. د خوندیتوب لپاره ټولې کټګورۍ نه بندېږي. صلاتي او اړین اپلیکیشنونه لکه تلیفون، نقشې یا طبي اپلیکیشنونه مه ټاکئ.',
      'focusFallback': 'په دې وسیله کې د ټول سیستم د اپلیکیشنونو بندول نشته. خوندي د اپلیکیشن دننه تمرکز فعال پاتې کېږي.',
      'qiblaDirection': 'د قبلې لوری',
      'calibrate': 'که قطب نما ناسمه ښکاري، فون د اته په بڼه وخوځوئ.',
      'noCompass': 'د قطب نما حسګر نشته. د قبلې لوری بیا هم په درجو ښودل کېږي.',
      'needLocation': 'لومړی یو ځای وټاکئ.',
      'offlineCache': 'افلاین زیرمه کارول کېږي.',
      'retry': 'بیا هڅه وکړئ',
      'noData': 'د نن لپاره د لمانځه باوري وختونه نشته.',
      'save': 'ساتل',
      'cancel': 'لغوه',
      'manualAdjustments': 'د دقیقو سمون',
      'maxSnoozes': 'اعظمي ځنډول',
      'unlimited': 'نامحدود',
      'genericError': 'یوه ستونزه پېښه شوه. بیا هڅه وکړئ.',
      'locationError': 'ستاسو ځای ونه موندل شو. پر ځای یې ښار ټاکلی شئ.',
      'networkError': 'د لمانځه وختونه اوس نه شي پورته کېدای. که موجود وي زیرمه شوې معلومات کارېږي.',
      'prayerDataError':
          'د لمانځه وختونه په باوري توګه پروسس نه شول. بیا هڅه وکړئ.',
      'snoozeUnavailable': 'دا لمونځ نور نه شي ځنډېدای.',
      'prayerFirst': 'لومړی لمونځ، بیا فون.',
      'heading': 'لوری',
      'minutesValue': '{value} دقیقې',
    },
  };

  String t(
    String key, {
    Map<String, String> params = const <String, String>{},
  }) {
    String value =
        _values[locale.languageCode]?[key] ?? _values['en']?[key] ?? key;
    for (final MapEntry<String, String> entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }

  /// Formats every user-visible number using the active app language.
  ///
  /// `intl` localizes punctuation, while Arabic, Urdu and Pashto also use
  /// their familiar digit shapes so no Latin digits leak into the interface.
  String number(num value) {
    final String formatted = NumberFormat.decimalPattern(locale.languageCode)
        .format(value);
    const Map<String, String> western = <String, String>{
      '0': '٠',
      '1': '١',
      '2': '٢',
      '3': '٣',
      '4': '٤',
      '5': '٥',
      '6': '٦',
      '7': '٧',
      '8': '٨',
      '9': '٩',
    };
    const Map<String, String> eastern = <String, String>{
      '0': '۰',
      '1': '۱',
      '2': '۲',
      '3': '۳',
      '4': '۴',
      '5': '۵',
      '6': '۶',
      '7': '۷',
      '8': '۸',
      '9': '۹',
    };
    final Map<String, String>? digits = switch (locale.languageCode) {
      'ar' => western,
      'ur' || 'ps' => eastern,
      _ => null,
    };
    if (digits == null) return formatted;
    return formatted.splitMapJoin(
      RegExp('[0-9]'),
      onMatch: (Match match) => digits[match.group(0)]!,
    );
  }

  String minutes(num value) =>
      t('minutesValue', params: <String, String>{'value': number(value)});

  String date(DateTime value, {required String pattern}) {
    final String formatted = DateFormat(
      pattern,
      locale.languageCode,
    ).format(value);
    return _localizeDigits(formatted);
  }

  String time(DateTime value) =>
      _localizeDigits(DateFormat.Hm(locale.languageCode).format(value));

  String _localizeDigits(String value) {
    if (locale.languageCode == 'de' || locale.languageCode == 'en') {
      return value;
    }
    return value.replaceAllMapped(RegExp('[0-9]'), (Match match) {
      final String digit = match.group(0)!;
      return number(int.parse(digit));
    });
  }
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (Locale item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture<AppStrings>(AppStrings(locale));

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppStrings> old) => false;
}
