import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:salah_focus/app/localization/app_language.dart';
import 'package:salah_focus/app/localization/additional_translations.dart';

class AppStrings {
  AppStrings(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppStrings> delegate =
      _AppStringsDelegate();

  /// Flutter has no built-in Pashto Cupertino catalog. The app uses its own
  /// translated strings, while this fallback supplies framework-only labels.
  static const LocalizationsDelegate<CupertinoLocalizations>
  cupertinoFallbackDelegate = _PashtoCupertinoLocalizationsDelegate();

  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings)!;

  static const List<Locale> supportedLocales = supportedAppLocales;

  static const Map<String, Map<String, String>> _values = {
    ...additionalTranslations,
    'de': {
      'markAsPrayed': 'Als gebetet markieren',
      'snoozeAction': 'Später erinnern',
      'alhamdulillah': 'Alhamdulillah',
      'fullScreenAlarmPermission': 'Vollbild-Erinnerungen erlauben',
      'fullScreenAlarmsEnabled': 'Vollbild-Erinnerungen sind aktiviert',
      'fullScreenAlarmsDisabled': 'Vollbild-Erinnerungen sind deaktiviert',
      'fullScreenAlarmPermissionHelp': 'Erlaube Gebetserinnerungen, den Bildschirm einzuschalten und bei gesperrtem Gerät im Vollbild zu erscheinen. Android kann bei entsperrtem Gerät stattdessen eine Benachrichtigung anzeigen. Ohne diese Berechtigung erhältst du weiterhin normale Benachrichtigungen.',
      'openFullScreenAlarmSettings':
          'Vollbild-Zugriff in Systemeinstellungen öffnen',
      'appName': 'Salaty',
      'tagline': 'Weniger Ablenkung. Mehr Salah.',
      'getStarted': "Los geht's",
      'home': 'Home',
      'tracker': 'Tracker',
      'qibla': 'Qibla',
      'settings': 'Einstellungen',
      'nextPrayer': 'Nächstes Gebet',
      'today': 'Heute',
      'yesterday': 'Gestern',
      'dayBeforeYesterday': 'Vorgestern',
      'edited': 'Nachträglich bearbeitet',
      'confirmPrayerRecordTitle': 'Gebet bestätigen?',
      'confirmPrayerRecordBody': '{prayer} am {date} als gebetet markieren?',
      'undoPrayerRecordTitle': 'Bestätigung zurücknehmen?',
      'undoPrayerRecordBody':
          '{prayer} am {date} wieder als nicht bestätigt markieren?',
      'prayed': 'Gebetet',
      'snoozed': 'Verschoben',
      'skipped': 'Übersprungen',
      'missed': 'Nicht bestätigt',
      'upcoming': 'Bevorstehend',
      'active': 'Aktiv',
      'pending': 'Erinnerung offen',
      'refresh': 'Aktualisieren',
      'location': 'Standort',
      'currentLocation': 'Aktueller Standort',
      'useLocation': 'Standort verwenden',
      'chooseCity': 'Stadt auswählen',
      'city': 'Stadt',
      'country': 'Land',
      'continue': 'Weiter',
      'back': 'Zurück',
      'prayerTimes': 'Gebetszeiten',
      'prayerReminders': 'Gebetserinnerungen',
      'timesQuestion':
          'Stimmen diese Zeiten ungefähr mit deiner Moschee überein?',
      'yes': 'Ja',
      'adjust': 'Anpassen',
      'graceQuestion': 'Wann sollen wir dich stärker erinnern?',
      'minutesAfter': 'Minuten nach Gebetsbeginn',
      'permissions': 'Berechtigungen',
      'permissionExplain': 'Wir fragen Berechtigungen erst dann an, wenn sie für eine Funktion gebraucht werden.',
      'finish': 'Fertig',
      'confirmPrayer': 'Ich habe gebetet',
      'snooze': '20 Minuten später erinnern',
      'snoozeIn': 'In {minutes} Minuten erinnern',
      'skipToday': 'Heute überspringen',
      'skipConfirmTitle': 'Erinnerung beenden?',
      'skipConfirmBody':
          'Möchtest du die Erinnerung für dieses Gebet wirklich beenden?',
      'noPrayLater': 'Nein, ich bete noch',
      'yesEnd': 'Ja, Erinnerung beenden',
      'reminderBody': 'Du wolltest dir Zeit für dein Gebet nehmen. Lege dein Handy für ein paar Minuten weg und bete.',
      'accepted': 'Alhamdulillah 🤍',
      'week': 'Diese Woche',
      'month': 'Monat',
      'confirmedPrayers': 'Bestätigte Gebete',
      'monthInfo': 'Über die Monatsübersicht',
      'monthInfoTitle': 'Was zeigt der Monat?',
      'monthInfoOverview': 'Jedes Feld steht für einen Tag dieses Monats und zeigt, wie viele der fünf Gebete du in der App bestätigt hast.',
      'monthCountHelp': 'Die erste Zahl zeigt die bestätigten Gebete. Die Gesamtzahl ist immer fünf.',
      'monthAllConfirmedHelp': 'Alle fünf Gebete bestätigt',
      'monthPartiallyConfirmedHelp': 'Einige, aber nicht alle Gebete bestätigt',
      'monthNoneConfirmedHelp': 'An einem vergangenen Tag kein Gebet bestätigt',
      'monthFutureHelp': 'Heute oder ein zukünftiger Tag ohne Bestätigung',
      'monthTodayOutlineHelp': 'Der Rahmen markiert den heutigen Tag.',
      'settingsInfo': 'Hilfe zu den Einstellungen',
      'settingsInfoTitle': 'Einstellungen erklärt',
      'trackerInfo': 'Über Gebetsstatus',
      'trackerInfoTitle': 'Was bedeuten die Statusangaben?',
      'trackerInfoIntro': '„Bestätigt“ bedeutet, dass du ein Gebet in der App als gebetet markiert hast. Es ist deine persönliche Aufzeichnung; die App bewertet oder überprüft dein Gebet nicht.',
      'close': 'Schließen',
      'statusUpcomingHelp': 'Die Gebetszeit hat noch nicht begonnen.',
      'statusActiveHelp':
          'Die Gebetszeit hat begonnen und die Erinnerungsfrist läuft.',
      'statusPendingHelp': 'Die Erinnerungsfrist ist abgelaufen. Die App wartet darauf, dass du das Gebet als gebetet markierst oder die Erinnerung verschiebst.',
      'statusSnoozedHelp':
          'Du hast die App gebeten, dich später noch einmal zu erinnern.',
      'statusPrayedHelp': 'Du hast dieses Gebet als gebetet markiert. Im Tracker zählt es als bestätigtes Gebet.',
      'statusSkippedHelp': 'Du hast die Erinnerungen für dieses Gebet beendet, ohne es als gebetet zu markieren.',
      'statusMissedHelp': 'Der Erfassungszeitraum endete, ohne dass das Gebet in der App bestätigt wurde.',
      'calculationMethod': 'Berechnungsmethode',
      'calculationMethodHelp': 'Wähle die Methode deiner Moschee oder islamischen Autorität. Sie beeinflusst vor allem Fajr und Ischa.',
      'madhhab': 'Asr-Berechnung',
      'asrCalculationHelp': 'Diese Einstellung ändert, wie der Beginn von Asr berechnet wird. Wähle die Regel deiner Moschee oder Rechtsschule.',
      'standard': 'Standard',
      'standardAsrHelp': 'Asr beginnt, wenn der Schatten eines Gegenstands zusätzlich zum Mittagsschatten seiner Länge entspricht.',
      'hanafi': 'Hanafi',
      'hanafiAsrHelp': 'Asr beginnt, wenn der Schatten eines Gegenstands zusätzlich zum Mittagsschatten doppelt so lang ist.',
      'highLatitude': 'Hohe Breitengrade',
      'highLatitudeHelp': 'Diese Regel schätzt Fajr und Ischa an Orten, an denen die Dämmerung sehr lange dauert oder nicht vollständig verschwindet. Verwende die Empfehlung deiner Moschee.',
      'highLatitudeMiddleOfNightHelp':
          'Verwendet die Mitte zwischen Sonnenuntergang und Sonnenaufgang.',
      'highLatitudeOneSeventhHelp':
          'Verwendet ein Siebtel der Nacht für die Dämmerungszeit.',
      'highLatitudeAngleBasedHelp': 'Verwendet den Sonnenwinkel der gewählten Berechnungsmethode, um die Dämmerungszeit zu schätzen.',
      'gracePeriod': 'Erinnerungsfrist',
      'snoozeDuration': 'Snooze-Dauer',
      'confirmationText': 'Bestätigungstext',
      'softReminder': 'Sanfte Erinnerung nach Überspringen',
      'theme': 'Darstellung',
      'system': 'System',
      'light': 'Hell',
      'dark': 'Dunkel',
      'systemThemeHelp': 'Übernimmt automatisch die helle oder dunkle Darstellung deines Geräts.',
      'lightThemeHelp': 'Verwendet immer die helle Darstellung.',
      'darkThemeHelp': 'Verwendet immer die dunkle Darstellung.',
      'language': 'Sprache',
      'languageSelect': 'Sprache wählen',
      'languageHelp': 'Ändert die Sprache der gesamten App. Du kannst sie jederzeit wieder wechseln.',
      'languageChoose': 'Wähle die Sprache für Salaty.',
      'german': 'Deutsch',
      'english': 'Englisch',
      'arabic': 'Arabisch',
      'notificationPermission': 'Benachrichtigungen erlauben',
      'notificationsEnabled': 'Benachrichtigungen sind aktiviert',
      'notificationsDisabled': 'Benachrichtigungen sind deaktiviert',
      'notificationPermissionHelp': 'Erhalte Erinnerungen zu deinen Gebetszeiten. Du kannst die Berechtigung in den Systemeinstellungen ändern.',
      'openSystemSettings': 'Systemeinstellungen öffnen',
      'systemSettingsAppearance': 'Die Systemeinstellungen öffnen sich außerhalb der App und verwenden die Darstellung deines Geräts.',
      'exactAlarmPermission': 'Präzise Erinnerungen erlauben',
      'exactAlarmsEnabled': 'Präzise Erinnerungen sind aktiviert',
      'exactAlarmsDisabled': 'Präzise Erinnerungen sind deaktiviert',
      'exactAlarmPermissionHelp': 'Diese Berechtigung ermöglicht Erinnerungen zur genauen Gebetszeit. Du kannst sie in den Systemeinstellungen unter „Alarme und Erinnerungen“ ändern.',
      'qiblaDirection': 'Qibla-Richtung',
      'calibrate': 'Bewege dein Handy in Form einer Acht, wenn der Kompass ungenau wirkt.',
      'noCompass': 'Kein Kompass-Sensor verfügbar. Die Qibla-Richtung wird in Grad angezeigt.',
      'needLocation': 'Bitte zuerst einen Standort festlegen.',
      'offlineCache': 'Offline-Cache wird verwendet.',
      'retry': 'Erneut versuchen',
      'noData': 'Für heute sind keine zuverlässigen Gebetszeiten gespeichert.',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'manualAdjustments': 'Minutenkorrekturen',
      'minuteAdjustmentsHelp': 'Mit Plus oder Minus passt du einzelne Gebetszeiten an deine Moschee an. Positive Minuten machen die Zeit später, negative früher. Erinnerungen verwenden die angepasste Zeit.',
      'locationHelp': 'Wird verwendet, um die Gebetszeiten und die Qibla-Richtung für deinen Ort zu berechnen.',
      'gracePeriodHelp': 'So lange wartet die App nach Beginn der Gebetszeit, bevor sie fragt, ob du gebetet hast.',
      'snoozeDurationHelp': 'So lange wartet die App nach „Später erinnern“, bevor sie dich erneut erinnert.',
      'maxSnoozesHelp': 'Legt fest, wie oft du eine Gebetserinnerung verschieben kannst. Unbegrenzt erlaubt dies bis zum nächsten Gebet.',
      'softReminderHelp': 'Sendet 45 Minuten später eine sanfte Erinnerung, wenn du eine Erinnerung beendest, ohne das Gebet als gebetet zu markieren.',
      'confirmationTextHelp': 'Dieser Text wird angezeigt, nachdem du ein Gebet als gebetet markierst. Du kannst ihn nach Wunsch ändern.',
      'maxSnoozes': 'Maximale Snoozes',
      'unlimited': 'Unbegrenzt',
      'genericError': 'Etwas ist schiefgelaufen. Bitte versuche es erneut.',
      'locationError': 'Der Standort konnte nicht bestimmt werden. Du kannst stattdessen eine Stadt auswählen.',
      'networkError': 'Die Gebetszeiten konnten gerade nicht geladen werden. Gespeicherte Daten werden verwendet, wenn sie verfügbar sind.',
      'prayerDataError': 'Die Gebetszeiten konnten nicht zuverlässig verarbeitet werden. Bitte versuche es erneut.',
      'snoozeUnavailable': 'Dieses Gebet kann nicht weiter verschoben werden.',
      'prayerFirst': 'Gebet zuerst, Handy danach.',
      'heading': 'Ausrichtung',
      'minutesValue': '{value} Min.',
    },
    'en': {
      'markAsPrayed': 'Mark as Prayed',
      'snoozeAction': 'Snooze',
      'alhamdulillah': 'Alhamdulillah',
      'fullScreenAlarmPermission': 'Allow full-screen reminders',
      'fullScreenAlarmsEnabled': 'Full-screen reminders are enabled',
      'fullScreenAlarmsDisabled': 'Full-screen reminders are disabled',
      'fullScreenAlarmPermissionHelp': 'Allow prayer reminders to wake the screen and appear full-screen when your device is locked. Android may show a notification instead while your device is unlocked. Without this permission, you still receive regular notifications.',
      'openFullScreenAlarmSettings':
          'Open full-screen access in system settings',
      'appName': 'Salaty',
      'tagline': 'Less distraction. More Salah.',
      'getStarted': 'Get started',
      'home': 'Home',
      'tracker': 'Tracker',
      'qibla': 'Qibla',
      'settings': 'Settings',
      'nextPrayer': 'Next prayer',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'dayBeforeYesterday': 'The day before yesterday',
      'edited': 'Manually edited',
      'confirmPrayerRecordTitle': 'Confirm prayer?',
      'confirmPrayerRecordBody': 'Mark {prayer} on {date} as prayed?',
      'undoPrayerRecordTitle': 'Undo confirmation?',
      'undoPrayerRecordBody': 'Mark {prayer} on {date} as not confirmed again?',
      'prayed': 'Prayed',
      'snoozed': 'Snoozed',
      'skipped': 'Skipped',
      'missed': 'Not confirmed',
      'upcoming': 'Upcoming',
      'active': 'Active',
      'pending': 'Reminder pending',
      'refresh': 'Refresh',
      'location': 'Location',
      'currentLocation': 'Current location',
      'useLocation': 'Use my location',
      'chooseCity': 'Choose city',
      'city': 'City',
      'country': 'Country',
      'continue': 'Continue',
      'back': 'Back',
      'prayerTimes': 'Prayer times',
      'prayerReminders': 'Prayer reminders',
      'timesQuestion': 'Do these times roughly match your local mosque?',
      'yes': 'Yes',
      'adjust': 'Adjust',
      'graceQuestion': 'When should we remind you more strongly?',
      'minutesAfter': 'minutes after prayer begins',
      'permissions': 'Permissions',
      'permissionExplain':
          'We only request permissions when a feature actually needs them.',
      'finish': 'Finish',
      'confirmPrayer': 'I have prayed',
      'snooze': 'Remind me in 20 minutes',
      'snoozeIn': 'Remind me in {minutes} minutes',
      'skipToday': 'Skip today',
      'skipConfirmTitle': 'End reminder?',
      'skipConfirmBody': 'Do you really want to end reminders for this prayer?',
      'noPrayLater': 'No, I will pray',
      'yesEnd': 'Yes, end reminder',
      'reminderBody': 'You wanted to make time for prayer. Put your phone down for a few minutes and pray.',
      'accepted': 'Alhamdulillah 🤍',
      'week': 'This week',
      'month': 'Month',
      'confirmedPrayers': 'Confirmed prayers',
      'monthInfo': 'About the monthly overview',
      'monthInfoTitle': 'What does the month show?',
      'monthInfoOverview': 'Each field is one day in this month. It shows how many of the five prayers you confirmed in the app.',
      'monthCountHelp': 'The first number is the prayers you confirmed. The total is always five.',
      'monthAllConfirmedHelp': 'All five prayers confirmed',
      'monthPartiallyConfirmedHelp': 'Some, but not all, prayers confirmed',
      'monthNoneConfirmedHelp': 'No prayer confirmed on a past day',
      'monthFutureHelp': 'Today or a future day with no confirmation yet',
      'monthTodayOutlineHelp': 'The outline marks today.',
      'settingsInfo': 'Help with settings',
      'settingsInfoTitle': 'Settings explained',
      'trackerInfo': 'About prayer statuses',
      'trackerInfoTitle': 'What do the statuses mean?',
      'trackerInfoIntro': '“Confirmed” means that you marked a prayer as prayed in the app. It is your personal record; the app does not judge or verify your prayer.',
      'close': 'Close',
      'statusUpcomingHelp': 'The prayer time has not started yet.',
      'statusActiveHelp': 'The prayer time has started and the reminder grace period is running.',
      'statusPendingHelp': 'The grace period has ended. The app is waiting for you to mark the prayer as prayed or snooze the reminder.',
      'statusSnoozedHelp': 'You asked the app to remind you again later.',
      'statusPrayedHelp': 'You marked this prayer as prayed. It counts as a confirmed prayer in the tracker.',
      'statusSkippedHelp':
          'You ended reminders for this prayer without marking it as prayed.',
      'statusMissedHelp': 'The tracking time ended without the prayer being confirmed in the app.',
      'calculationMethod': 'Calculation method',
      'calculationMethodHelp': 'Choose the method used by your local mosque or Islamic authority. It mainly affects the Fajr and Isha times.',
      'madhhab': 'Asr calculation',
      'asrCalculationHelp': 'This setting changes how the start of Asr is calculated. Choose the rule followed by your mosque or school of thought.',
      'standard': 'Standard',
      'standardAsrHelp': 'Asr begins when an object’s shadow equals its length, in addition to the midday shadow.',
      'hanafi': 'Hanafi',
      'hanafiAsrHelp': 'Asr begins when an object’s shadow is twice its length, in addition to the midday shadow.',
      'highLatitude': 'High latitude rule',
      'highLatitudeHelp': 'This rule estimates Fajr and Isha in places where twilight lasts unusually long or never fully disappears. Use the rule recommended by your local mosque.',
      'highLatitudeMiddleOfNightHelp':
          'Uses the middle point between sunset and sunrise.',
      'highLatitudeOneSeventhHelp':
          'Uses one seventh of the night for the twilight period.',
      'highLatitudeAngleBasedHelp': 'Uses the selected calculation method’s sun angle to estimate the twilight period.',
      'gracePeriod': 'Grace period',
      'snoozeDuration': 'Snooze duration',
      'confirmationText': 'Confirmation text',
      'softReminder': 'Gentle reminder after skip',
      'theme': 'Appearance',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'systemThemeHelp':
          'Uses your device’s light or dark appearance automatically.',
      'lightThemeHelp': 'Always uses the light appearance.',
      'darkThemeHelp': 'Always uses the dark appearance.',
      'language': 'Language',
      'languageSelect': 'Choose language',
      'languageHelp': 'Changes the language used throughout the app. You can switch it again at any time.',
      'languageChoose': 'Choose the language for Salaty.',
      'german': 'German',
      'english': 'English',
      'arabic': 'Arabic',
      'notificationPermission': 'Allow notifications',
      'notificationsEnabled': 'Notifications are enabled',
      'notificationsDisabled': 'Notifications are disabled',
      'notificationPermissionHelp': 'Receive reminders for your prayer times. You can change this permission in system settings.',
      'openSystemSettings': 'Open system settings',
      'systemSettingsAppearance': 'System settings open outside the app and use your device’s appearance.',
      'exactAlarmPermission': 'Allow precise reminders',
      'exactAlarmsEnabled': 'Precise reminders are enabled',
      'exactAlarmsDisabled': 'Precise reminders are disabled',
      'exactAlarmPermissionHelp': 'This permission enables reminders at the exact prayer time. You can change it under “Alarms & reminders” in system settings.',
      'qiblaDirection': 'Qibla direction',
      'calibrate':
          'Move your phone in a figure eight if the compass seems inaccurate.',
      'noCompass':
          'No compass sensor is available. Qibla is still shown in degrees.',
      'needLocation': 'Please set a location first.',
      'offlineCache': 'Using offline cache.',
      'retry': 'Try again',
      'noData': 'No reliable prayer times are stored for today.',
      'save': 'Save',
      'cancel': 'Cancel',
      'manualAdjustments': 'Minute adjustments',
      'minuteAdjustmentsHelp': 'Use plus or minus to move an individual prayer time so it matches your local mosque. Positive minutes make it later; negative minutes make it earlier. Reminders follow the adjusted time.',
      'locationHelp': 'Used to calculate prayer times and the Qibla direction for your location.',
      'gracePeriodHelp': 'How long the app waits after a prayer time begins before asking whether you have prayed.',
      'snoozeDurationHelp': 'How long the app waits before reminding you again after you choose Snooze.',
      'maxSnoozesHelp': 'How many times you can postpone one prayer reminder. Unlimited allows snoozing until the next prayer.',
      'softReminderHelp': 'Sends one gentle follow-up 45 minutes later if you end a reminder without marking the prayer as prayed.',
      'confirmationTextHelp': 'This text appears after you mark a prayer as prayed. You can change it to wording that is meaningful to you.',
      'maxSnoozes': 'Maximum snoozes',
      'unlimited': 'Unlimited',
      'genericError': 'Something went wrong. Please try again.',
      'locationError': 'Your location could not be determined. You can choose a city instead.',
      'networkError': 'Prayer times could not be loaded right now. Cached data will be used when available.',
      'prayerDataError':
          'Prayer times could not be processed reliably. Please try again.',
      'snoozeUnavailable': 'This prayer cannot be snoozed any further.',
      'prayerFirst': 'Prayer first, phone second.',
      'heading': 'Heading',
      'minutesValue': '{value} min',
    },
    'ar': {
      'markAsPrayed': 'تسجيل الصلاة كمؤداة',
      'snoozeAction': 'تأجيل',
      'alhamdulillah': 'الحمد لله',
      'fullScreenAlarmPermission': 'السماح بالتذكيرات بملء الشاشة',
      'fullScreenAlarmsEnabled': 'التذكيرات بملء الشاشة مفعّلة',
      'fullScreenAlarmsDisabled': 'التذكيرات بملء الشاشة غير مفعّلة',
      'fullScreenAlarmPermissionHelp': 'اسمح لتذكيرات الصلاة بتشغيل الشاشة والظهور بملء الشاشة عندما يكون جهازك مقفلاً. قد يعرض أندرويد إشعاراً بدلاً من ذلك عند فتح القفل. ستستمر في تلقي الإشعارات العادية دون هذا الإذن.',
      'openFullScreenAlarmSettings': 'فتح إذن ملء الشاشة في إعدادات النظام',
      'appName': 'صلاتي',
      'tagline': 'تشتيت أقل. صلاة أكثر.',
      'getStarted': 'ابدأ',
      'home': 'الرئيسية',
      'tracker': 'المتابعة',
      'qibla': 'القبلة',
      'settings': 'الإعدادات',
      'nextPrayer': 'الصلاة القادمة',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'dayBeforeYesterday': 'أول أمس',
      'edited': 'تم التعديل يدويًا',
      'confirmPrayerRecordTitle': 'تأكيد الصلاة؟',
      'confirmPrayerRecordBody':
          'هل تريد تسجيل صلاة {prayer} بتاريخ {date} على أنها أُدّيت؟',
      'undoPrayerRecordTitle': 'التراجع عن التأكيد؟',
      'undoPrayerRecordBody': 'هل تريد تسجيل صلاة {prayer} بتاريخ {date} على أنها غير مؤكدة مجددًا؟',
      'prayed': 'تمت الصلاة',
      'snoozed': 'مؤجل',
      'skipped': 'تم الإنهاء',
      'missed': 'غير مؤكد',
      'upcoming': 'قادمة',
      'active': 'حان وقتها',
      'pending': 'تذكير مفتوح',
      'refresh': 'تحديث',
      'location': 'الموقع',
      'currentLocation': 'الموقع الحالي',
      'useLocation': 'استخدم موقعي',
      'chooseCity': 'اختر مدينة',
      'city': 'المدينة',
      'country': 'الدولة',
      'continue': 'متابعة',
      'back': 'رجوع',
      'prayerTimes': 'مواقيت الصلاة',
      'prayerReminders': 'تذكيرات الصلاة',
      'timesQuestion': 'هل تتوافق هذه الأوقات تقريبًا مع مسجدك؟',
      'yes': 'نعم',
      'adjust': 'تعديل',
      'graceQuestion': 'متى تريد تذكيرًا أقوى؟',
      'minutesAfter': 'دقيقة بعد دخول وقت الصلاة',
      'permissions': 'الأذونات',
      'permissionExplain': 'نطلب الأذونات فقط عندما تحتاجها ميزة معينة.',
      'finish': 'إنهاء',
      'confirmPrayer': 'لقد صليت',
      'snooze': 'ذكرني بعد 20 دقيقة',
      'snoozeIn': 'ذكّرني بعد {minutes} دقيقة',
      'skipToday': 'إنهاء تذكير اليوم',
      'skipConfirmTitle': 'إنهاء التذكير؟',
      'skipConfirmBody': 'هل تريد فعلًا إنهاء التذكيرات لهذه الصلاة؟',
      'noPrayLater': 'لا، سأصلي',
      'yesEnd': 'نعم، أنهِ التذكير',
      'reminderBody':
          'أردت أن تخصص وقتًا للصلاة. اترك الهاتف لبضع دقائق وصلِّ.',
      'accepted': 'الحمد لله 🤍',
      'week': 'هذا الأسبوع',
      'month': 'الشهر',
      'confirmedPrayers': 'الصلوات المؤكدة',
      'monthInfo': 'حول النظرة الشهرية',
      'monthInfoTitle': 'ماذا يعرض الشهر؟',
      'monthInfoOverview': 'يمثل كل مربع يومًا من هذا الشهر، ويعرض عدد الصلوات التي أكّدت أداءها في التطبيق من أصل خمس.',
      'monthCountHelp':
          'الرقم الأول هو عدد الصلوات المؤكدة، والمجموع دائمًا خمس صلوات.',
      'monthAllConfirmedHelp': 'تم تأكيد الصلوات الخمس كلها',
      'monthPartiallyConfirmedHelp': 'تم تأكيد بعض الصلوات فقط',
      'monthNoneConfirmedHelp': 'لم تُؤكَّد أي صلاة في يوم مضى',
      'monthFutureHelp': 'اليوم أو يوم قادم بلا تأكيد حتى الآن',
      'monthTodayOutlineHelp': 'الإطار يحدد يومنا هذا.',
      'settingsInfo': 'مساعدة حول الإعدادات',
      'settingsInfoTitle': 'شرح الإعدادات',
      'trackerInfo': 'حول حالات الصلاة',
      'trackerInfoTitle': 'ماذا تعني الحالات؟',
      'trackerInfoIntro': 'تعني «مؤكدة» أنك وضعت علامة «تمت الصلاة» في التطبيق. هذا سجل شخصي لك؛ لا يحكم التطبيق على صلاتك ولا يتحقق منها.',
      'close': 'إغلاق',
      'statusUpcomingHelp': 'لم يدخل وقت الصلاة بعد.',
      'statusActiveHelp': 'دخل وقت الصلاة، وما زالت مهلة التذكير جارية.',
      'statusPendingHelp': 'انتهت مهلة التذكير. ينتظر التطبيق أن تضع علامة «تمت الصلاة» أو تؤجل التذكير.',
      'statusSnoozedHelp': 'طلبت من التطبيق أن يذكّرك مرة أخرى لاحقًا.',
      'statusPrayedHelp':
          'وضعت علامة أن هذه الصلاة قد أُديت. وتُحسب صلاة مؤكدة في المتابعة.',
      'statusSkippedHelp': 'أنهيت تذكيرات هذه الصلاة دون وضع علامة أنها أُديت.',
      'statusMissedHelp': 'انتهت مدة المتابعة دون تأكيد الصلاة في التطبيق.',
      'calculationMethod': 'طريقة الحساب',
      'calculationMethodHelp': 'اختر الطريقة التي يستخدمها مسجدك أو الجهة الإسلامية المحلية. تؤثر أساسًا في وقتي الفجر والعشاء.',
      'madhhab': 'حساب العصر',
      'asrCalculationHelp': 'يغيّر هذا الإعداد طريقة حساب بداية وقت العصر. اختر القاعدة التي يتبعها مسجدك أو مذهبك.',
      'standard': 'قياسي',
      'standardAsrHelp':
          'يبدأ العصر عندما يصبح ظل الشيء مساويًا لطوله، إضافة إلى ظل الزوال.',
      'hanafi': 'حنفي',
      'hanafiAsrHelp':
          'يبدأ العصر عندما يصبح ظل الشيء ضعف طوله، إضافة إلى ظل الزوال.',
      'highLatitude': 'قاعدة خطوط العرض العليا',
      'highLatitudeHelp': 'تقدّر هذه القاعدة وقتي الفجر والعشاء في الأماكن التي يطول فيها الشفق جدًا أو لا يختفي تمامًا. اتبع ما يوصي به مسجدك المحلي.',
      'highLatitudeMiddleOfNightHelp':
          'تستخدم منتصف الوقت بين غروب الشمس وشروقها.',
      'highLatitudeOneSeventhHelp': 'تستخدم سُبع الليل لفترة الشفق.',
      'highLatitudeAngleBasedHelp':
          'تستخدم زاوية الشمس في طريقة الحساب المختارة لتقدير فترة الشفق.',
      'gracePeriod': 'فترة السماح',
      'snoozeDuration': 'مدة التأجيل',
      'confirmationText': 'نص التأكيد',
      'softReminder': 'تذكير لطيف بعد الإنهاء',
      'theme': 'المظهر',
      'system': 'النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'systemThemeHelp': 'يتبع المظهر الفاتح أو الداكن في جهازك تلقائيًا.',
      'lightThemeHelp': 'يستخدم المظهر الفاتح دائمًا.',
      'darkThemeHelp': 'يستخدم المظهر الداكن دائمًا.',
      'language': 'اللغة',
      'languageSelect': 'اختر اللغة',
      'languageHelp': 'يغيّر اللغة المستخدمة في التطبيق كله. يمكنك تغييرها مرة أخرى في أي وقت.',
      'languageChoose': 'اختر لغة تطبيق صلاتي.',
      'german': 'الألمانية',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'notificationPermission': 'السماح بالإشعارات',
      'notificationsEnabled': 'الإشعارات مفعّلة',
      'notificationsDisabled': 'الإشعارات معطّلة',
      'notificationPermissionHelp': 'تلقَّ تذكيرات بمواقيت صلاتك. يمكنك تغيير هذا الإذن في إعدادات النظام.',
      'openSystemSettings': 'فتح إعدادات النظام',
      'systemSettingsAppearance':
          'تُفتح إعدادات النظام خارج التطبيق وتستخدم مظهر جهازك.',
      'exactAlarmPermission': 'السماح بالتذكيرات الدقيقة',
      'exactAlarmsEnabled': 'التذكيرات الدقيقة مفعّلة',
      'exactAlarmsDisabled': 'التذكيرات الدقيقة معطّلة',
      'exactAlarmPermissionHelp': 'يتيح هذا الإذن التذكير في وقت الصلاة بالضبط. يمكنك تغييره ضمن «المنبّهات والتذكيرات» في إعدادات النظام.',
      'qiblaDirection': 'اتجاه القبلة',
      'calibrate': 'حرّك هاتفك على شكل رقم ثمانية إذا بدا البوصلة غير دقيقة.',
      'noCompass': 'لا يوجد مستشعر بوصلة. سيظهر اتجاه القبلة بالدرجات.',
      'needLocation': 'حدد موقعًا أولًا.',
      'offlineCache': 'يتم استخدام البيانات المحفوظة دون اتصال.',
      'retry': 'حاول مجددًا',
      'noData': 'لا توجد مواقيت صلاة موثوقة محفوظة لليوم.',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'manualAdjustments': 'تعديلات الدقائق',
      'minuteAdjustmentsHelp': 'استخدم زائد أو ناقص لمطابقة وقت كل صلاة مع مسجدك المحلي. الدقائق الموجبة تؤخر الوقت والسالبة تقدمه. تتبع التذكيرات الوقت المعدّل.',
      'locationHelp': 'يُستخدم لحساب مواقيت الصلاة واتجاه القبلة في موقعك.',
      'gracePeriodHelp': 'الفترة التي ينتظرها التطبيق بعد دخول وقت الصلاة قبل أن يسألك إن كنت قد صليت.',
      'snoozeDurationHelp': 'المدة التي ينتظرها التطبيق قبل أن يذكّرك مرة أخرى بعد اختيار «ذكّرني لاحقًا».',
      'maxSnoozesHelp': 'يحدد عدد مرات تأجيل تذكير الصلاة الواحدة. يتيح خيار «بلا حد» التأجيل حتى الصلاة التالية.',
      'softReminderHelp': 'يرسل تذكيرًا لطيفًا بعد 45 دقيقة إذا أنهيت التذكير دون وضع علامة أن الصلاة أُديت.',
      'confirmationTextHelp': 'يظهر هذا النص بعد وضع علامة أن الصلاة أُديت. يمكنك تغييره إلى عبارة تناسبك.',
      'maxSnoozes': 'أقصى عدد للتأجيل',
      'unlimited': 'بلا حد',
      'genericError': 'حدث خطأ ما. حاول مرة أخرى.',
      'locationError': 'تعذر تحديد موقعك. يمكنك اختيار مدينة بدلًا من ذلك.',
      'networkError': 'تعذر تحميل مواقيت الصلاة الآن. سيتم استخدام البيانات المحفوظة إن كانت متاحة.',
      'prayerDataError': 'تعذر معالجة مواقيت الصلاة بشكل موثوق. حاول مرة أخرى.',
      'snoozeUnavailable': 'لا يمكن تأجيل تذكير هذه الصلاة أكثر.',
      'prayerFirst': 'الصلاة أولًا، ثم الهاتف.',
      'heading': 'اتجاه الهاتف',
      'minutesValue': '{value} دقيقة',
    },
    'ur': {
      'markAsPrayed': 'نماز ادا شدہ درج کریں',
      'snoozeAction': 'ملتوی کریں',
      'alhamdulillah': 'الحمدللہ',
      'fullScreenAlarmPermission': 'پوری اسکرین کی یاددہانیوں کی اجازت دیں',
      'fullScreenAlarmsEnabled': 'پوری اسکرین کی یاددہانیاں فعال ہیں',
      'fullScreenAlarmsDisabled': 'پوری اسکرین کی یاددہانیاں غیر فعال ہیں',
      'fullScreenAlarmPermissionHelp': 'نماز کی یاددہانیوں کو اسکرین روشن کرنے اور مقفل آلے پر پوری اسکرین میں دکھنے کی اجازت دیں۔ آلہ کھلا ہونے پر اینڈرائیڈ اس کے بجائے اطلاع دکھا سکتا ہے۔ اس اجازت کے بغیر بھی عام اطلاعات موصول ہوتی رہیں گی۔',
      'openFullScreenAlarmSettings':
          'سسٹم کی ترتیبات میں پوری اسکرین کی اجازت کھولیں',
      'appName': 'صلاتی',
      'tagline': 'کم توجہ بھٹکنا۔ زیادہ نماز۔',
      'getStarted': 'شروع کریں',
      'home': 'ہوم',
      'tracker': 'ریکارڈ',
      'qibla': 'قبلہ',
      'settings': 'ترتیبات',
      'nextPrayer': 'اگلی نماز',
      'today': 'آج',
      'yesterday': 'گزشتہ روز',
      'dayBeforeYesterday': 'دو دن پہلے',
      'edited': 'دستی طور پر ترمیم شدہ',
      'confirmPrayerRecordTitle': 'نماز کی تصدیق کریں؟',
      'confirmPrayerRecordBody':
          'کیا {date} کی {prayer} کو ادا شدہ درج کرنا چاہتے ہیں؟',
      'undoPrayerRecordTitle': 'تصدیق واپس لیں؟',
      'undoPrayerRecordBody':
          'کیا {date} کی {prayer} کو دوبارہ غیر تصدیق شدہ درج کرنا چاہتے ہیں؟',
      'prayed': 'نماز پڑھی',
      'snoozed': 'موخر',
      'skipped': 'چھوڑ دیا',
      'missed': 'تصدیق نہیں ہوئی',
      'upcoming': 'آنے والی',
      'active': 'فعال',
      'pending': 'یاد دہانی زیرِ عمل',
      'refresh': 'تازہ کریں',
      'location': 'مقام',
      'currentLocation': 'موجودہ مقام',
      'useLocation': 'میرا مقام استعمال کریں',
      'chooseCity': 'شہر منتخب کریں',
      'city': 'شہر',
      'country': 'ملک',
      'continue': 'جاری رکھیں',
      'back': 'واپس',
      'prayerTimes': 'نماز کے اوقات',
      'prayerReminders': 'نماز کی یاد دہانیاں',
      'timesQuestion': 'کیا یہ اوقات تقریباً آپ کی مقامی مسجد سے ملتے ہیں؟',
      'yes': 'ہاں',
      'adjust': 'تبدیل کریں',
      'graceQuestion': 'ہم آپ کو زیادہ مضبوطی سے کب یاد دلائیں؟',
      'minutesAfter': 'نماز شروع ہونے کے بعد منٹ',
      'permissions': 'اجازتیں',
      'permissionExplain':
          'ہم صرف اس وقت اجازت مانگتے ہیں جب کسی خصوصیت کو اس کی ضرورت ہو۔',
      'finish': 'مکمل',
      'confirmPrayer': 'میں نے نماز پڑھی ہے',
      'snooze': '20 منٹ بعد یاد دلائیں',
      'snoozeIn': '{minutes} منٹ بعد یاد دلائیں',
      'skipToday': 'آج چھوڑ دیں',
      'skipConfirmTitle': 'یاد دہانی بند کریں؟',
      'skipConfirmBody':
          'کیا آپ واقعی اس نماز کی یاد دہانیاں بند کرنا چاہتے ہیں؟',
      'noPrayLater': 'نہیں، میں نماز پڑھوں گا',
      'yesEnd': 'ہاں، یاد دہانی بند کریں',
      'reminderBody': 'آپ نے نماز کے لیے وقت نکالنا چاہا تھا۔ فون چند منٹ کے لیے رکھ دیں اور نماز پڑھیں۔',
      'accepted': 'الحمدللہ 🤍',
      'week': 'اس ہفتے',
      'month': 'مہینہ',
      'confirmedPrayers': 'تصدیق شدہ نمازیں',
      'monthInfo': 'ماہانہ جائزے کے بارے میں',
      'monthInfoTitle': 'مہینہ کیا دکھاتا ہے؟',
      'monthInfoOverview': 'ہر خانہ اس مہینے کا ایک دن ہے۔ یہ دکھاتا ہے کہ پانچ میں سے کتنی نمازوں کی آپ نے ایپ میں تصدیق کی۔',
      'monthCountHelp':
          'پہلا عدد تصدیق شدہ نمازوں کی تعداد ہے۔ کل تعداد ہمیشہ پانچ ہے۔',
      'monthAllConfirmedHelp': 'پانچوں نمازیں تصدیق شدہ ہیں',
      'monthPartiallyConfirmedHelp': 'کچھ نمازیں تصدیق شدہ ہیں، سب نہیں',
      'monthNoneConfirmedHelp': 'گزشتہ دن کی کوئی نماز تصدیق شدہ نہیں',
      'monthFutureHelp': 'آج یا آنے والا دن، ابھی کوئی تصدیق نہیں',
      'monthTodayOutlineHelp': 'حاشیہ آج کے دن کو ظاہر کرتا ہے۔',
      'settingsInfo': 'ترتیبات کے بارے میں مدد',
      'settingsInfoTitle': 'ترتیبات کی وضاحت',
      'trackerInfo': 'نماز کی حالتوں کے بارے میں',
      'trackerInfoTitle': 'حالتوں کا کیا مطلب ہے؟',
      'trackerInfoIntro': '«تصدیق شدہ» کا مطلب ہے کہ آپ نے ایپ میں نماز کو پڑھی ہوئی نشان زد کیا ہے۔ یہ آپ کا ذاتی ریکارڈ ہے؛ ایپ آپ کی نماز کا فیصلہ یا تصدیق نہیں کرتی۔',
      'close': 'بند کریں',
      'statusUpcomingHelp': 'نماز کا وقت ابھی شروع نہیں ہوا۔',
      'statusActiveHelp':
          'نماز کا وقت شروع ہو گیا ہے اور یاد دہانی کی مہلت جاری ہے۔',
      'statusPendingHelp': 'یاد دہانی کی مہلت ختم ہو گئی ہے۔ ایپ آپ کے نماز پڑھی ہوئی نشان زد کرنے یا یاد دہانی موخر کرنے کا انتظار کر رہی ہے۔',
      'statusSnoozedHelp':
          'آپ نے ایپ سے کہا ہے کہ وہ بعد میں دوبارہ یاد دلائے۔',
      'statusPrayedHelp': 'آپ نے اس نماز کو پڑھی ہوئی نشان زد کیا ہے۔ یہ ریکارڈ میں تصدیق شدہ نماز شمار ہوتی ہے۔',
      'statusSkippedHelp': 'آپ نے نماز کو پڑھی ہوئی نشان زد کیے بغیر اس کی یاد دہانیاں بند کر دیں۔',
      'statusMissedHelp':
          'ایپ میں نماز کی تصدیق ہوئے بغیر ریکارڈ رکھنے کا وقت ختم ہو گیا۔',
      'calculationMethod': 'حساب کا طریقہ',
      'calculationMethodHelp': 'اپنی مقامی مسجد یا اسلامی ادارے کا استعمال کردہ طریقہ منتخب کریں۔ اس کا زیادہ اثر فجر اور عشاء کے اوقات پر ہوتا ہے۔',
      'madhhab': 'عصر کا حساب',
      'asrCalculationHelp': 'یہ ترتیب عصر کے آغاز کا حساب بدلتی ہے۔ اپنی مسجد یا فقہی مسلک کا اصول منتخب کریں۔',
      'standard': 'معیاری',
      'standardAsrHelp': 'عصر اس وقت شروع ہوتی ہے جب کسی چیز کا سایہ، زوال کے سائے کے علاوہ، اس کی لمبائی کے برابر ہو۔',
      'hanafi': 'حنفی',
      'hanafiAsrHelp': 'عصر اس وقت شروع ہوتی ہے جب کسی چیز کا سایہ، زوال کے سائے کے علاوہ، اس کی لمبائی سے دوگنا ہو۔',
      'highLatitude': 'بلند عرض البلد کا اصول',
      'highLatitudeHelp': 'یہ اصول ان جگہوں پر فجر اور عشاء کا اندازہ لگاتا ہے جہاں شفق بہت دیر رہتی ہے یا مکمل طور پر ختم نہیں ہوتی۔ اپنی مقامی مسجد کی سفارش استعمال کریں۔',
      'highLatitudeMiddleOfNightHelp':
          'غروبِ آفتاب اور طلوعِ آفتاب کے درمیان آدھا وقت استعمال کرتا ہے۔',
      'highLatitudeOneSeventhHelp':
          'شفق کے وقت کے لیے رات کا ساتواں حصہ استعمال کرتا ہے۔',
      'highLatitudeAngleBasedHelp': 'شفق کے وقت کا اندازہ لگانے کے لیے منتخب طریقۂ حساب کا شمسی زاویہ استعمال کرتا ہے۔',
      'gracePeriod': 'مہلت کی مدت',
      'snoozeDuration': 'موخر کرنے کی مدت',
      'confirmationText': 'تصدیقی متن',
      'softReminder': 'چھوڑنے کے بعد نرم یاد دہانی',
      'theme': 'ظاہری شکل',
      'system': 'سسٹم',
      'light': 'روشن',
      'dark': 'تاریک',
      'systemThemeHelp':
          'آپ کے آلے کی روشن یا تاریک ظاہری شکل خودکار طور پر استعمال کرتا ہے۔',
      'lightThemeHelp': 'ہمیشہ روشن ظاہری شکل استعمال کرتا ہے۔',
      'darkThemeHelp': 'ہمیشہ تاریک ظاہری شکل استعمال کرتا ہے۔',
      'language': 'زبان',
      'languageSelect': 'زبان منتخب کریں',
      'languageHelp': 'پوری ایپ کی زبان تبدیل کرتا ہے۔ آپ اسے کسی بھی وقت دوبارہ بدل سکتے ہیں۔',
      'languageChoose': 'صلاتی کے لیے زبان منتخب کریں۔',
      'german': 'جرمن',
      'english': 'انگریزی',
      'arabic': 'عربی',
      'urdu': 'اردو',
      'pashto': 'پشتو',
      'notificationPermission': 'اطلاعات کی اجازت دیں',
      'notificationsEnabled': 'اطلاعات فعال ہیں',
      'notificationsDisabled': 'اطلاعات غیر فعال ہیں',
      'notificationPermissionHelp': 'نماز کے اوقات کی یاد دہانیاں حاصل کریں۔ آپ سسٹم کی ترتیبات میں یہ اجازت تبدیل کر سکتے ہیں۔',
      'openSystemSettings': 'سسٹم کی ترتیبات کھولیں',
      'systemSettingsAppearance': 'سسٹم کی ترتیبات ایپ سے باہر کھلتی ہیں اور آپ کے آلے کی ظاہری شکل استعمال کرتی ہیں۔',
      'exactAlarmPermission': 'درست یاددہانیوں کی اجازت دیں',
      'exactAlarmsEnabled': 'عین وقت کی یاد دہانیاں فعال ہیں',
      'exactAlarmsDisabled': 'عین وقت کی یاد دہانیاں غیر فعال ہیں',
      'exactAlarmPermissionHelp': 'یہ اجازت نماز کے عین وقت پر یاد دہانیاں بھیجنے کے لیے ہے۔ اسے سسٹم کی ترتیبات میں «الارم اور یاد دہانیاں» کے تحت تبدیل کر سکتے ہیں۔',
      'qiblaDirection': 'قبلہ کی سمت',
      'calibrate': 'اگر قطب نما غلط لگے تو فون کو آٹھ کی شکل میں حرکت دیں۔',
      'noCompass': 'قطب نما سینسر دستیاب نہیں۔ قبلہ کی سمت پھر بھی درجوں میں دکھائی جاتی ہے۔',
      'needLocation': 'پہلے ایک مقام مقرر کریں۔',
      'offlineCache': 'آف لائن محفوظ ڈیٹا استعمال ہو رہا ہے۔',
      'retry': 'دوبارہ کوشش کریں',
      'noData': 'آج کے لیے نماز کے قابلِ اعتماد اوقات محفوظ نہیں ہیں۔',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ',
      'manualAdjustments': 'منٹ کی تبدیلیاں',
      'minuteAdjustmentsHelp': 'ہر نماز کا وقت مقامی مسجد سے ملانے کے لیے جمع یا تفریق استعمال کریں۔ مثبت منٹ وقت کو بعد میں اور منفی منٹ پہلے کرتے ہیں۔ یاد دہانیاں درست کیے گئے وقت کے مطابق آتی ہیں۔',
      'locationHelp': 'آپ کے مقام کے مطابق نماز کے اوقات اور قبلہ کی سمت معلوم کرنے کے لیے استعمال ہوتا ہے۔',
      'gracePeriodHelp': 'نماز کا وقت شروع ہونے کے بعد ایپ اتنی دیر انتظار کرتی ہے، پھر پوچھتی ہے کہ کیا آپ نے نماز پڑھ لی۔',
      'snoozeDurationHelp': '«بعد میں یاد دلائیں» دبانے کے بعد ایپ اتنی دیر انتظار کر کے دوبارہ یاد دلاتی ہے۔',
      'maxSnoozesHelp': 'یہ طے کرتا ہے کہ ایک نماز کی یاد دہانی کتنی بار موخر کی جا سکتی ہے۔ «لامحدود» اگلی نماز تک موخر کرنے دیتا ہے۔',
      'softReminderHelp': 'اگر آپ نماز پڑھی ہوئی نشان زد کیے بغیر یاد دہانی بند کریں تو 45 منٹ بعد ایک نرم یاد دہانی بھیجتا ہے۔',
      'confirmationTextHelp': 'یہ متن نماز کو پڑھی ہوئی نشان زد کرنے کے بعد دکھائی دیتا ہے۔ آپ اسے اپنے لیے موزوں الفاظ میں بدل سکتے ہیں۔',
      'maxSnoozes': 'زیادہ سے زیادہ موخر کرنا',
      'unlimited': 'لامحدود',
      'genericError': 'کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔',
      'locationError':
          'آپ کا مقام معلوم نہیں ہو سکا۔ آپ اس کے بجائے شہر منتخب کر سکتے ہیں۔',
      'networkError': 'نماز کے اوقات ابھی لوڈ نہیں ہو سکے۔ دستیاب ہونے پر محفوظ ڈیٹا استعمال ہوگا۔',
      'prayerDataError': 'نماز کے اوقات قابل اعتماد طور پر پراسیس نہیں ہو سکے۔ براہ کرم دوبارہ کوشش کریں۔',
      'snoozeUnavailable': 'اس نماز کو مزید موخر نہیں کیا جا سکتا۔',
      'prayerFirst': 'پہلے نماز، پھر فون۔',
      'heading': 'سمت',
      'minutesValue': '{value} منٹ',
    },
    'ps': {
      'markAsPrayed': 'لمونځ د ادا شوي په توګه ثبت کړئ',
      'snoozeAction': 'وروسته یادونه',
      'alhamdulillah': 'الحمدلله',
      'fullScreenAlarmPermission': 'د بشپړې پردې یادونو ته اجازه ورکړئ',
      'fullScreenAlarmsEnabled': 'د بشپړې پردې یادونې فعالې دي',
      'fullScreenAlarmsDisabled': 'د بشپړې پردې یادونې غیرفعالې دي',
      'fullScreenAlarmPermissionHelp': 'د لمانځه یادونو ته اجازه ورکړئ چې پرده روښانه کړي او د وسیلې د قلف پر مهال په بشپړه پرده ښکاره شي. کله چې وسیله خلاصه وي، انډرایډ ښايي پر ځای یې خبرتیا وښيي. له دې اجازې پرته به هم عادي خبرتیاوې ترلاسه کوئ.',
      'openFullScreenAlarmSettings':
          'د سیسټم په امستنو کې د بشپړې پردې اجازه پرانیزئ',
      'appName': 'صلاتي',
      'tagline': 'لږ ګډوډي. ډېره لمونځ.',
      'getStarted': 'پیل کړئ',
      'home': 'کور',
      'tracker': 'څارونکی',
      'qibla': 'قبله',
      'settings': 'امستنې',
      'nextPrayer': 'راتلونکی لمونځ',
      'today': 'نن',
      'yesterday': 'پرون',
      'dayBeforeYesterday': 'وړمه ورځ',
      'edited': 'په لاسي ډول سم شوی',
      'confirmPrayerRecordTitle': 'لمونځ تایید کړئ؟',
      'confirmPrayerRecordBody':
          'د {date} نېټې {prayer} لمونځ د ادا شوي په توګه ثبت کړئ؟',
      'undoPrayerRecordTitle': 'تایید بېرته واخلئ؟',
      'undoPrayerRecordBody':
          'د {date} نېټې {prayer} لمونځ بیا د نه تایید شوي په توګه ثبت کړئ؟',
      'prayed': 'لمونځ وشو',
      'snoozed': 'ځنډول شوی',
      'skipped': 'تېر شوی',
      'missed': 'تایید نه شو',
      'upcoming': 'راتلونکی',
      'active': 'فعال',
      'pending': 'یادونه پرانیستې ده',
      'refresh': 'تازه کړئ',
      'location': 'ځای',
      'currentLocation': 'اوسنی ځای',
      'useLocation': 'زما ځای وکاروئ',
      'chooseCity': 'ښار وټاکئ',
      'city': 'ښار',
      'country': 'هېواد',
      'continue': 'دوام ورکړئ',
      'back': 'بېرته',
      'prayerTimes': 'د لمانځه وختونه',
      'prayerReminders': 'د لمانځه یادونې',
      'timesQuestion': 'ایا دا وختونه نږدې ستاسو له جومات سره سمون لري؟',
      'yes': 'هو',
      'adjust': 'سمول',
      'graceQuestion': 'کله مو په ډېر ټینګار یاد کړو؟',
      'minutesAfter': 'د لمانځه له پیله وروسته دقیقې',
      'permissions': 'اجازې',
      'permissionExplain':
          'موږ یوازې هغه وخت اجازه غواړو چې کومه ځانګړنه ورته اړتیا ولري.',
      'finish': 'پای',
      'confirmPrayer': 'ما لمونځ کړی دی',
      'snooze': 'په ۲۰ دقیقو کې مې یاد کړئ',
      'snoozeIn': 'په {minutes} دقیقو کې مې یاد کړئ',
      'skipToday': 'نن پرېږدئ',
      'skipConfirmTitle': 'یادونه پای ته ورسوئ؟',
      'skipConfirmBody': 'ایا رښتیا غواړئ د دې لمانځه یادونې پای ته ورسوئ؟',
      'noPrayLater': 'نه، لمونځ به وکړم',
      'yesEnd': 'هو، یادونه پای ته ورسوئ',
      'reminderBody': 'تاسو غوښتل لمانځه ته وخت ځانګړی کړئ. فون د څو دقیقو لپاره کېږدئ او لمونځ وکړئ.',
      'accepted': 'الحمدلله 🤍',
      'week': 'دا اونۍ',
      'month': 'میاشت',
      'confirmedPrayers': 'تایید شوي لمونځونه',
      'monthInfo': 'د میاشتني لید په اړه',
      'monthInfoTitle': 'میاشت څه ښيي؟',
      'monthInfoOverview': 'هره خانه د دې میاشتې یوه ورځ ده. دا ښيي چې له پنځو لمونځونو مو څو په اپ کې تایید کړي دي.',
      'monthCountHelp':
          'لومړی شمېر د تایید شوو لمونځونو دی. ټول شمېر تل پنځه وي.',
      'monthAllConfirmedHelp': 'پنځه واړه لمونځونه تایید شوي',
      'monthPartiallyConfirmedHelp': 'ځینې لمونځونه تایید شوي، خو ټول نه',
      'monthNoneConfirmedHelp': 'په تېره ورځ کې هېڅ لمونځ نه دی تایید شوی',
      'monthFutureHelp': 'نن یا راتلونکې ورځ چې لا تایید نه لري',
      'monthTodayOutlineHelp': 'چوکاټ نننۍ ورځ ښيي.',
      'settingsInfo': 'د امستنو په اړه مرسته',
      'settingsInfoTitle': 'د امستنو تشریح',
      'trackerInfo': 'د لمانځه د حالتونو په اړه',
      'trackerInfoTitle': 'حالتونه څه معنا لري؟',
      'trackerInfoIntro': '«تایید شوی» یعنې تاسو په اپ کې لمونځ د ادا شوي په توګه نښه کړی. دا ستاسو شخصي ثبت دی؛ اپ ستاسو د لمانځه قضاوت یا تصدیق نه کوي.',
      'close': 'تړل',
      'statusUpcomingHelp': 'د لمانځه وخت لا نه دی پیل شوی.',
      'statusActiveHelp': 'د لمانځه وخت پیل شوی او د یادونې مهلت روان دی.',
      'statusPendingHelp': 'د یادونې مهلت پای ته رسېدلی. اپ ستاسو د تایید یا د یادونې د ځنډولو انتظار کوي.',
      'statusSnoozedHelp': 'تاسو له اپ څخه غوښتي چې وروسته بیا یادونه وکړي.',
      'statusPrayedHelp': 'تاسو دا لمونځ د ادا شوي په توګه نښه کړی. په څارونکي کې تایید شوی لمونځ شمېرل کېږي.',
      'statusSkippedHelp': 'تاسو د دې لمانځه یادونې بې له تاییده پای ته رسولې.',
      'statusMissedHelp':
          'په اپ کې د لمانځه له تایید پرته د څارنې وخت پای ته ورسېد.',
      'calculationMethod': 'د محاسبې طریقه',
      'calculationMethodHelp': 'هغه طریقه وټاکئ چې ستاسو سیمه ییز جومات یا اسلامي اداره یې کاروي. دا تر ډېره د سهار او ماخوستن پر وختونو اغېز کوي.',
      'madhhab': 'د مازدیګر محاسبه',
      'asrCalculationHelp': 'دا امستنه د مازدیګر د پیل محاسبه بدلوي. د خپل جومات یا مذهب قاعده وټاکئ.',
      'standard': 'معیاري',
      'standardAsrHelp': 'مازدیګر هغه وخت پیلېږي چې د یوه شي سیوری، د غرمې له سیوري سربېره، د هغه له اوږدوالي سره برابر شي.',
      'hanafi': 'حنفي',
      'hanafiAsrHelp': 'مازدیګر هغه وخت پیلېږي چې د یوه شي سیوری، د غرمې له سیوري سربېره، د هغه د اوږدوالي دوه برابره شي.',
      'highLatitude': 'د لوړې عرض البلد قاعده',
      'highLatitudeHelp': 'دا قاعده په هغو ځایونو کې د سهار او ماخوستن وختونه اټکلوي چې ماښامنۍ رڼا ډېره اوږده وي یا بیخي نه ورکېږي. د خپل سیمه ییز جومات سپارښتنه وکاروئ.',
      'highLatitudeMiddleOfNightHelp':
          'د لمر لوېدو او راختو ترمنځ منځنی وخت کاروي.',
      'highLatitudeOneSeventhHelp':
          'د ماښامنۍ رڼا لپاره د شپې اوومه برخه کاروي.',
      'highLatitudeAngleBasedHelp':
          'د ماښامنۍ رڼا د اټکل لپاره د ټاکل شوې محاسبې د لمر زاویه کاروي.',
      'gracePeriod': 'د ځنډ موده',
      'snoozeDuration': 'د ځنډولو موده',
      'confirmationText': 'د تایید متن',
      'softReminder': 'له پرېښودو وروسته نرمه یادونه',
      'theme': 'بڼه',
      'system': 'سیستم',
      'light': 'روښانه',
      'dark': 'تیاره',
      'systemThemeHelp':
          'ستاسو د وسیلې روښانه یا تیاره بڼه په اوتومات ډول کاروي.',
      'lightThemeHelp': 'تل روښانه بڼه کاروي.',
      'darkThemeHelp': 'تل تیاره بڼه کاروي.',
      'language': 'ژبه',
      'languageSelect': 'ژبه وټاکئ',
      'languageHelp': 'د ټول اپ ژبه بدلوي. هر وخت یې بیا بدلولی شئ.',
      'languageChoose': 'د صلاتي لپاره ژبه وټاکئ.',
      'german': 'جرمني',
      'english': 'انګلیسي',
      'arabic': 'عربي',
      'urdu': 'اردو',
      'pashto': 'پښتو',
      'notificationPermission': 'خبرتیاوو ته اجازه ورکړئ',
      'notificationsEnabled': 'خبرتیاوې فعالې دي',
      'notificationsDisabled': 'خبرتیاوې غیرفعالې دي',
      'notificationPermissionHelp': 'د لمانځه د وختونو یادونې ترلاسه کړئ. دا اجازه د سیستم په امستنو کې بدلولی شئ.',
      'openSystemSettings': 'د سیستم امستنې پرانیزئ',
      'systemSettingsAppearance': 'د سیستم امستنې له اپ څخه بهر پرانیستل کېږي او ستاسو د وسیلې بڼه کاروي.',
      'exactAlarmPermission': 'دقیقو یادونو ته اجازه ورکړئ',
      'exactAlarmsEnabled': 'پر دقیق وخت یادونې فعالې دي',
      'exactAlarmsDisabled': 'پر دقیق وخت یادونې غیرفعالې دي',
      'exactAlarmPermissionHelp': 'دا اجازه د لمانځه پر دقیق وخت یادونې ممکنوي. د سیستم په امستنو کې یې د «الارمونو او یادونو» لاندې بدلولی شئ.',
      'qiblaDirection': 'د قبلې لوری',
      'calibrate': 'که قطب نما ناسمه ښکاري، فون د اته په بڼه وخوځوئ.',
      'noCompass': 'د قطب نما حسګر نشته. د قبلې لوری بیا هم په درجو ښودل کېږي.',
      'needLocation': 'لومړی یو ځای وټاکئ.',
      'offlineCache': 'افلاین زیرمه کارول کېږي.',
      'retry': 'بیا هڅه وکړئ',
      'noData': 'د نن لپاره د لمانځه باوري وختونه نشته.',
      'save': 'ساتل',
      'cancel': 'لغوه',
      'manualAdjustments': 'د دقیقو سمون',
      'minuteAdjustmentsHelp': 'د هر لمانځه وخت له خپل جومات سره د برابرولو لپاره جمع یا منفي وکاروئ. مثبتې دقیقې وخت وروسته او منفي دقیقې مخکې کوي. یادونې د سم شوي وخت له مخې راځي.',
      'locationHelp': 'ستاسو د ځای لپاره د لمانځه وختونو او د قبلې لوري د محاسبې لپاره کارېږي.',
      'gracePeriodHelp': 'اپ د لمانځه د وخت له پیل وروسته همدومره انتظار کوي، بیا پوښتي چې لمونځ مو کړی که نه.',
      'snoozeDurationHelp': 'د «وروسته یادونه» له ټاکلو وروسته اپ همدومره انتظار کوي او بیا یادونه کوي.',
      'maxSnoozesHelp': 'ټاکي چې د یوه لمانځه یادونه څو ځله ځنډولی شئ. «نامحدود» تر راتلونکي لمانځه پورې ځنډ ته اجازه ورکوي.',
      'softReminderHelp': 'که یادونه د لمانځه له تایید پرته پای ته ورسوئ، 45 دقیقې وروسته یوه نرمه یادونه لېږي.',
      'confirmationTextHelp': 'دا متن د لمانځه له تایید وروسته ښکاري. تاسو یې په خپلو خوښو ټکو بدلولی شئ.',
      'maxSnoozes': 'اعظمي ځنډول',
      'unlimited': 'نامحدود',
      'genericError': 'یوه ستونزه پېښه شوه. بیا هڅه وکړئ.',
      'locationError': 'ستاسو ځای ونه موندل شو. پر ځای یې ښار ټاکلی شئ.',
      'networkError': 'د لمانځه وختونه اوس نه شي پورته کېدای. که موجود وي زیرمه شوې معلومات کارېږي.',
      'prayerDataError':
          'د لمانځه وختونه په باوري توګه پروسس نه شول. بیا هڅه وکړئ.',
      'snoozeUnavailable': 'دا لمونځ نور نه شي ځنډېدای.',
      'prayerFirst': 'لومړی لمونځ، بیا فون.',
      'heading': 'لوری',
      'minutesValue': '{value} دقیقې',
    },
  };

  /// Exposes the actual catalogs so tests can detect unintended fallbacks.
  @visibleForTesting
  static Map<String, Map<String, String>> get translations => _values;

  String t(
    String key, {
    Map<String, String> params = const <String, String>{},
  }) {
    if (key == 'appName') {
      return const <String, String>{
            'de': 'Mein Gebet',
            'en': 'My Prayer',
            'ar': 'صلاتي',
            'bn': 'আমার নামাজ',
            'fa': 'نماز من',
            'fr': 'Ma prière',
            'ha': "Addu'ata",
            'id': 'Salatku',
            'jv': 'Shalatku',
            'ms': 'Solatku',
            'nl': 'Mijn gebed',
            'ps': 'زما لمونځ',
            'ru': 'Моя молитва',
            'so': 'Salaaddayda',
            'sw': 'Swala yangu',
            'ce': 'Сан ламаз',
            'tr': 'Namazım',
            'ur': 'میری نماز',
            'es': 'Mi oración',
          }[locale.languageCode] ??
          'My Prayer';
    }
    String value =
        _values[locale.languageCode]?[key] ?? _values['en']?[key] ?? key;
    for (final MapEntry<String, String> entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value);
    }
    return value;
  }

  /// Formats every user-visible number using the active app language.
  ///
  /// `intl` localizes punctuation, while Arabic, Urdu and Pashto also use
  /// their familiar digit shapes so no Latin digits leak into the interface.
  String number(num value) {
    final String formatted = NumberFormat.decimalPattern(locale.languageCode)
        .format(value);
    const Map<String, String> western = <String, String>{
      '0': '٠',
      '1': '١',
      '2': '٢',
      '3': '٣',
      '4': '٤',
      '5': '٥',
      '6': '٦',
      '7': '٧',
      '8': '٨',
      '9': '٩',
    };
    const Map<String, String> eastern = <String, String>{
      '0': '۰',
      '1': '۱',
      '2': '۲',
      '3': '۳',
      '4': '۴',
      '5': '۵',
      '6': '۶',
      '7': '۷',
      '8': '۸',
      '9': '۹',
    };
    final Map<String, String>? digits = switch (locale.languageCode) {
      'ar' => western,
      'ur' || 'ps' => eastern,
      _ => null,
    };
    if (digits == null) return formatted;
    return formatted.splitMapJoin(
      RegExp('[0-9]'),
      onMatch: (Match match) => digits[match.group(0)]!,
    );
  }

  String minutes(num value) =>
      t('minutesValue', params: <String, String>{'value': number(value)});

  String date(DateTime value, {required String pattern}) {
    final String formatted = DateFormat(
      pattern,
      locale.languageCode,
    ).format(value);
    return _localizeDigits(_localizeGregorianDateWords(formatted));
  }

  String time(DateTime value) =>
      _localizeDigits(DateFormat.Hm(locale.languageCode).format(value));

  String hijriDate(String value) {
    if (!const <String>{
      'ar',
      'ur',
      'ps',
      'tr',
      'fr',
      'es',
    }.contains(locale.languageCode)) {
      return _localizeDigits(value);
    }

    const Map<String, String> arabicMonths = <String, String>{
      'Muharram': 'محرم',
      'Safar': 'صفر',
      'Rabi al-Awwal': 'ربيع الأول',
      'Rabi al-awwal': 'ربيع الأول',
      "Rabi' al-awwal": 'ربيع الأول',
      'Rabīʿ al-awwal': 'ربيع الأول',
      'Rabi al-Thani': 'ربيع الثاني',
      'Rabi al-thani': 'ربيع الثاني',
      "Rabi' al-thani": 'ربيع الثاني',
      'Rabīʿ al-thānī': 'ربيع الثاني',
      'Jumada al-Awwal': 'جمادى الأولى',
      'Jumada al-awwal': 'جمادى الأولى',
      'Jumada al-ula': 'جمادى الأولى',
      'Jumādá al-ūlá': 'جمادى الأولى',
      'Jumada al-Thani': 'جمادى الآخرة',
      'Jumada al-thani': 'جمادى الآخرة',
      'Jumada al-akhirah': 'جمادى الآخرة',
      'Jumādá al-ākhirah': 'جمادى الآخرة',
      'Rajab': 'رجب',
      'Shaban': 'شعبان',
      'Shaʿbān': 'شعبان',
      'Ramadan': 'رمضان',
      'Ramaḍān': 'رمضان',
      'Shawwal': 'شوال',
      'Shawwāl': 'شوال',
      'Dhul Qadah': 'ذو القعدة',
      'Dhu al-Qidah': 'ذو القعدة',
      'Dhū al-Qaʿdah': 'ذو القعدة',
      'Dhul Hijjah': 'ذو الحجة',
      'Dhu al-Hijjah': 'ذو الحجة',
      'Dhū al-Ḥijjah': 'ذو الحجة',
    };

    const Map<String, List<String>> monthNames = {
      'tr': [
        'Muharrem',
        'Safer',
        'Rebiülevvel',
        'Rebiülahir',
        'Cemaziyelevvel',
        'Cemaziyelahir',
        'Recep',
        'Şaban',
        'Ramazan',
        'Şevval',
        'Zilkade',
        'Zilhicce',
      ],
      'fr': [
        'Mouharram',
        'Safar',
        'Rabia al awal',
        'Rabia ath-thani',
        'Joumada al oula',
        'Joumada ath-thania',
        'Rajab',
        'Chaabane',
        'Ramadan',
        'Chawwal',
        'Dhou al qi`da',
        'Dhou al hijja',
      ],
      'es': [
        'Muharram',
        'Safar',
        'Rabi al-awwal',
        'Rabi al-thani',
        'Yumada al-ula',
        'Yumada al-ajira',
        'Rayab',
        'Shaabán',
        'Ramadán',
        'Shawwal',
        'Dhu al-qada',
        'Dhu al-hiyya',
      ],
    };
    final List<String> sourceMonths = arabicMonths.values.toSet().toList();
    final List<String>? targetMonths = monthNames[locale.languageCode];
    String localized = value;
    for (final MapEntry<String, String> entry in arabicMonths.entries) {
      final String name = targetMonths == null
          ? entry.value
          : targetMonths[sourceMonths.indexOf(entry.value)];
      localized = localized.replaceAll(entry.key, name);
    }
    return _localizeDigits(localized);
  }

  /// Physical compass positions are independent of the interface direction.
  String compassDirection(String direction) {
    const Map<String, List<String>> labels = {
      'de': ['N', 'S', 'W', 'O'],
      'en': ['N', 'S', 'W', 'E'],
      'tr': ['K', 'G', 'B', 'D'],
      'fr': ['N', 'S', 'O', 'E'],
      'es': ['N', 'S', 'O', 'E'],
      'ar': ['ش', 'ج', 'غ', 'ق'],
      'ur': ['ش', 'ج', 'مغ', 'مش'],
      'ps': ['ش', 'ج', 'ل', 'خ'],
    };
    final int index = const ['N', 'S', 'W', 'E'].indexOf(direction);
    return index < 0
        ? direction
        : (labels[locale.languageCode] ?? labels['en']!)[index];
  }

  String _localizeDigits(String value) {
    if (locale.languageCode == 'de' || locale.languageCode == 'en') {
      return value;
    }
    return value.replaceAllMapped(RegExp('[0-9]'), (Match match) {
      final String digit = match.group(0)!;
      return number(int.parse(digit));
    });
  }

  /// Keeps Gregorian day and month names in the selected app language even
  /// when a platform's date-symbol fallback returns English names.
  String _localizeGregorianDateWords(String value) {
    if (locale.languageCode != 'ar') return value;

    const Map<String, String> arabicWords = <String, String>{
      'Monday': 'الاثنين',
      'Tuesday': 'الثلاثاء',
      'Wednesday': 'الأربعاء',
      'Thursday': 'الخميس',
      'Friday': 'الجمعة',
      'Saturday': 'السبت',
      'Sunday': 'الأحد',
      'January': 'كانون الثاني',
      'February': 'شباط',
      'March': 'آذار',
      'April': 'نيسان',
      'May': 'أيار',
      'June': 'حزيران',
      'July': 'تموز',
      'August': 'آب',
      'September': 'أيلول',
      'October': 'تشرين الأول',
      'November': 'تشرين الثاني',
      'December': 'كانون الأول',
      // Arabic CLDR data normally uses these international Arabic names.
      // Replace them with the requested Levantine Gregorian month names.
      'يناير': 'كانون الثاني',
      'فبراير': 'شباط',
      'مارس': 'آذار',
      'أبريل': 'نيسان',
      'مايو': 'أيار',
      'يونيو': 'حزيران',
      'يوليو': 'تموز',
      'أغسطس': 'آب',
      'سبتمبر': 'أيلول',
      'أكتوبر': 'تشرين الأول',
      'نوفمبر': 'تشرين الثاني',
      'ديسمبر': 'كانون الأول',
    };

    String localized = value;
    for (final MapEntry<String, String> entry in arabicWords.entries) {
      localized = localized.replaceAll(entry.key, entry.value);
    }
    return localized;
  }
}

class _AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const _AppStringsDelegate();

  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (Locale item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture<AppStrings>(AppStrings(locale));

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppStrings> old) => false;
}

class _PashtoCupertinoLocalizationsDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const _PashtoCupertinoLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => locale.languageCode == 'ps';

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(
    covariant LocalizationsDelegate<CupertinoLocalizations> old,
  ) => false;
}
