/// Locale-specific date data that is not supplied by `intl`.
///
/// Keep these strings as literal UTF-8 text. In particular, native-script
/// locales must never be replaced with transliterations or escaped code units.
const Map<String, String> localizedFullDatePatterns = <String, String>{
  'ar': 'EEEE، d MMMM y',
  'bn': 'EEEE, d MMMM y',
  'de': 'EEEE, d. MMMM y',
  'en': 'EEEE, d MMMM y',
  'es': "EEEE, d 'de' MMMM 'de' y",
  'fa': 'EEEE، d MMMM y',
  'fr': 'EEEE d MMMM y',
  'id': 'EEEE, d MMMM y',
  'ms': 'EEEE, d MMMM y',
  'pa': 'EEEE، d MMMM y',
  'ps': 'EEEE، d MMMM y',
  'tr': 'd MMMM y EEEE',
  'ur': 'EEEE، d MMMM y',
};

const Map<String, String> localizedMediumDatePatterns = <String, String>{
  'de': 'd. MMMM y',
  'es': "d 'de' MMMM 'de' y",
};

/// Natural Hijri month names for every supported language, January-style
/// index order (Muharram through Dhu al-Hijjah).
const Map<String, List<String>> localizedHijriMonths = <String, List<String>>{
  'ar': <String>[
    'محرم',
    'صفر',
    'ربيع الأول',
    'ربيع الآخر',
    'جمادى الأولى',
    'جمادى الآخرة',
    'رجب',
    'شعبان',
    'رمضان',
    'شوال',
    'ذو القعدة',
    'ذو الحجة',
  ],
  'bn': <String>[
    'মুহাররম',
    'সফর',
    'রবিউল আউয়াল',
    'রবিউস সানি',
    'জমাদিউল আউয়াল',
    'জমাদিউস সানি',
    'রজব',
    'শাবান',
    'রমজান',
    'শাওয়াল',
    'জিলকদ',
    'জিলহজ',
  ],
  'de': <String>[
    'Muharram',
    'Safar',
    'Rabi al-Awwal',
    'Rabi al-Thani',
    'Dschumada al-Ula',
    'Dschumada ath-Thaniya',
    'Radschab',
    'Schaban',
    'Ramadan',
    'Schawwal',
    'Dhu al-Qada',
    'Dhu al-Hiddscha',
  ],
  'en': <String>[
    'Muharram',
    'Safar',
    'Rabi al-Awwal',
    'Rabi al-Thani',
    'Jumada al-Awwal',
    'Jumada al-Thani',
    'Rajab',
    'Shaban',
    'Ramadan',
    'Shawwal',
    'Dhu al-Qadah',
    'Dhu al-Hijjah',
  ],
  'es': <String>[
    'Muharram',
    'Safar',
    'Rabi al-Awwal',
    'Rabi al-Thani',
    'Yumada al-Awwal',
    'Yumada al-Thani',
    'Rayab',
    'Shabán',
    'Ramadán',
    'Shawwal',
    'Dhu al-Qada',
    'Dhu al-Hiyya',
  ],
  'fa': <String>[
    'محرم',
    'صفر',
    'ربیع‌الاول',
    'ربیع‌الثانی',
    'جمادی‌الاول',
    'جمادی‌الثانی',
    'رجب',
    'شعبان',
    'رمضان',
    'شوال',
    'ذی‌القعده',
    'ذی‌الحجه',
  ],
  'fr': <String>[
    'Mouharram',
    'Safar',
    'Rabia al-Awwal',
    'Rabia ath-Thani',
    'Joumada al-Oula',
    'Joumada ath-Thania',
    'Rajab',
    'Chaabane',
    'Ramadan',
    'Chawwal',
    'Dhou al-Qida',
    'Dhou al-Hijja',
  ],
  'id': <String>[
    'Muharam',
    'Safar',
    'Rabiulawal',
    'Rabiulakhir',
    'Jumadilawal',
    'Jumadilakhir',
    'Rajab',
    'Syakban',
    'Ramadan',
    'Syawal',
    'Zulkaidah',
    'Zulhijah',
  ],
  'ms': <String>[
    'Muharam',
    'Safar',
    'Rabiulawal',
    'Rabiulakhir',
    'Jamadilawal',
    'Jamadilakhir',
    'Rejab',
    'Syaaban',
    'Ramadan',
    'Syawal',
    'Zulkaedah',
    'Zulhijah',
  ],
  'pa': <String>[
    'محرم',
    'صفر',
    'ربیع الاول',
    'ربیع الثانی',
    'جمادی الاول',
    'جمادی الثانی',
    'رجب',
    'شعبان',
    'رمضان',
    'شوال',
    'ذوالقعدہ',
    'ذوالحجہ',
  ],
  'ps': <String>[
    'محرم',
    'صفر',
    'ربیع الاول',
    'ربیع الثاني',
    'جمادي الاول',
    'جمادي الثاني',
    'رجب',
    'شعبان',
    'رمضان',
    'شوال',
    'ذوالقعده',
    'ذوالحجه',
  ],
  'tr': <String>[
    'Muharrem',
    'Safer',
    'Rebiülevvel',
    'Rebiülahir',
    'Cemaziyelevvel',
    'Cemaziyelahir',
    'Recep',
    'Şaban',
    'Ramazan',
    'Şevval',
    'Zilkade',
    'Zilhicce',
  ],
  'ur': <String>[
    'محرم',
    'صفر',
    'ربیع الاول',
    'ربیع الثانی',
    'جمادی الاول',
    'جمادی الثانی',
    'رجب',
    'شعبان',
    'رمضان',
    'شوال',
    'ذوالقعدہ',
    'ذوالحجہ',
  ],
};

/// `intl` ships Punjabi Gregorian data in Gurmukhi. The app intentionally
/// supports Punjabi in Shahmukhi (`pa-Arab`), so these names are supplied in
/// the script selected by the user.
const Map<String, String> shahmukhiGregorianWords = <String, String>{
  'Monday': 'سوموار',
  'Tuesday': 'منگل',
  'Wednesday': 'بدھ',
  'Thursday': 'جمعرات',
  'Friday': 'جمعہ',
  'Saturday': 'ہفتہ',
  'Sunday': 'اتوار',
  'January': 'جنوری',
  'February': 'فروری',
  'March': 'مارچ',
  'April': 'اپریل',
  'May': 'مئی',
  'June': 'جون',
  'July': 'جولائی',
  'August': 'اگست',
  'September': 'ستمبر',
  'October': 'اکتوبر',
  'November': 'نومبر',
  'December': 'دسمبر',
};

/// Month spellings returned by different AlAdhan API versions.
const Map<String, int> hijriMonthAliases = <String, int>{
  'muharram': 1,
  'safar': 2,
  'rabi al-awwal': 3,
  "rabi' al-awwal": 3,
  'rabīʿ al-awwal': 3,
  'rabi al-thani': 4,
  'rabi al-thānī': 4,
  "rabi' al-thani": 4,
  'rabīʿ al-thānī': 4,
  'jumada al-awwal': 5,
  'jumada al-ula': 5,
  'jumādá al-ūlá': 5,
  'jumada al-thani': 6,
  'jumada al-akhirah': 6,
  'jumādá al-ākhirah': 6,
  'rajab': 7,
  'shaban': 8,
  'shaʿbān': 8,
  'ramadan': 9,
  'ramaḍān': 9,
  'shawwal': 10,
  'shawwāl': 10,
  'dhul qadah': 11,
  'dhu al-qidah': 11,
  'dhū al-qaʿdah': 11,
  'dhul hijjah': 12,
  'dhu al-hijjah': 12,
  'dhū al-ḥijjah': 12,
};
